### ISSUE TITLE
依赖管理-Python3 无法安装。

### ISSUE THREAD

**Issue by yer2018** [whyour/qinglong#1086]
ITraceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.1.1', 'console_scripts', 'pip')()
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'requests' from 'pip._vendor' (/usr/lib/python3.8/site-packages/pip/_vendor/__init__.py)

**Comment by jackadam1981** [comment]
curl -sS https://bootstrap.pypa.io/get-pip.py | python3

试试这个
我用这个解决了，但是忘记报错是什么了，也是pip什么的出错。

**Comment by HaaiSo** [comment]
我是同样的错误

**Comment by wqw999** [comment]
> 



> 卷曲－sShttps://bootstrap.pypa.io/get-pip.py|蟒蛇3
> 
> 试试这个 我用这个解决了，但是忘记报错是什么了，也是pip什么的出错。

不行

**Comment by wqw999** [comment]
不行

**Comment by jackadam1981** [comment]
还是得看具体出错是什么。
具体安装什么依赖。

**Comment by wqw999** [comment]
> 

开始安装依赖 ping3，开始时间 2022/1/25 上午12:11:56

Collecting ping3

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2a20062a00>: Failed to establish a new connection: [Errno -3] Try again')': /packages/a0/6f/649754cb387f3e5ad9ed15e22c5f6384ee4a0f250bb27ad5cf848741e6e1/ping3-3.0.2-py3-none-any.whl

  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2a20062bb0>: Failed to establish a new connection: [Errno -3] Try again')': /packages/a0/6f/649754cb387f3e5ad9ed15e22c5f6384ee4a0f250bb27ad5cf848741e6e1/ping3-3.0.2-py3-none-any.whl

  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2a20062d60>: Failed to establish a new connection: [Errno -3] Try again')': /packages/a0/6f/649754cb387f3e5ad9ed15e22c5f6384ee4a0f250bb27ad5cf848741e6e1/ping3-3.0.2-py3-none-any.whl

  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2a20062f10>: Failed to establish a new connection: [Errno -3] Try again')': /packages/a0/6f/649754cb387f3e5ad9ed15e22c5f6384ee4a0f250bb27ad5cf848741e6e1/ping3-3.0.2-py3-none-any.whl

  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2a1ffe5100>: Failed to establish a new connection: [Errno -3] Try again')': /packages/a0/6f/649754cb387f3e5ad9ed15e22c5f6384ee4a0f250bb27ad5cf848741e6e1/ping3-3.0.2-py3-none-any.whl

ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/a0/6f/649754cb387f3e5ad9ed15e22c5f6384ee4a0f250bb27ad5cf848741e6e1/ping3-3.0.2-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2a1ffe52b0>: Failed to establish a new connection: [Errno -3] Try again'))


依赖安装失败，结束时间 2022/1/25 上午12:12:35，耗时 38.906 秒
所有Python3的依赖都是这样

**Comment by HaaiSo** [comment]
pip安装任何东西都报错，更新pip也同样的错误。。。
这是安装requests：
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    load_entry_point('pip==20.1.1', 'console_scripts', 'pip3')()
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'requests' from 'pip._vendor' (/usr/lib/python3.8/site-packages/pip/_vendor/__init__.py)

**Comment by yer2018** [comment]
是在 NodeJs 中 安装的
