### ISSUE TITLE
青龙面板每天凌晨都提示服务异常，请手动执行ql check，执行后正常，第二天后又是提示如此，青龙版本为2.10.13

### ISSUE THREAD

**Issue by Air433up** [whyour/qinglong#1087]
执行ql check后日志如下
## 开始执行... 2022-01-11 09:32:33

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.f778bd55.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.20
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.40/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/javascript/javascript.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js"></script>
    <script src="/umi.c7eb612e.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   43 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
28002 root      0:00 nginx: worker process
28003 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2022-01-10T10:33:50: info:    task Aaron-lv_sync/jd_cfd.js pid: 1755 exit null signal SIGKILL
2022-01-10T10:33:50: info:    task Aaron-lv_sync/jd_cfd.js pid: 1755 closed null
2022-01-10T10:37:44: info:    task Aaron-lv_sync/jd_cfd.js pid: 1895 exit 0 signal null
2022-01-10T10:37:44: info:    task Aaron-lv_sync/jd_cfd.js pid: 1895 closed 0
2022-01-10T10:44:47: info:    task Aaron-lv_sync/jd_cfd.js pid: 2145 exit null signal SIGKILL
2022-01-10T10:44:47: info:    task Aaron-lv_sync/jd_cfd.js pid: 2145 closed null
2022-01-10T10:45:12: info:    task zero205_JD_tencent_scf_main/jd_cfd.js pid: 2288 exit null signal SIGKILL
2022-01-10T10:45:12: info:    task zero205_JD_tencent_scf_main/jd_cfd.js pid: 2288 closed null
2022-01-10T10:45:47: info:    task Aaron-lv_sync/jd_cfd.js pid: 2445 exit null signal SIGKILL
2022-01-10T10:45:47: info:    task Aaron-lv_sync/jd_cfd.js pid: 2445 closed null
2022-01-10T10:46:00: info:    task zero205_JD_tencent_scf_main/jd_cfd.js pid: 2588 exit null signal SIGKILL
2022-01-10T10:46:00: info:    task zero205_JD_tencent_scf_main/jd_cfd.js pid: 2588 closed null
2022-01-10T10:46:29: info:    task zero205_JD_tencent_scf_main/jd_zhanianshou.js pid: 2717 exit 0 signal null
2022-01-10T10:46:29: info:    task zero205_JD_tencent_scf_main/jd_zhanianshou.js pid: 2717 closed 0
2022-01-10T10:47:08: info:    task zero205_JD_tencent_scf_main/jd_zhanianshou.js pid: 2847 exit 0 signal null
2022-01-10T10:47:08: info:    task zero205_JD_tencent_scf_main/jd_zhanianshou.js pid: 2847 closed 0
2022-01-10T14:29:21: info:    task ccwav_QLScript2/jd_CkSeq.js pid: 19367 exit 0 signal null
2022-01-10T14:29:21: info:    task ccwav_QLScript2/jd_CkSeq.js pid: 19367 closed 0
2022-01-11T00:05:03: info:    ✌️ Server need close
2022-01-11T00:05:03: info:    ✌️ Server closed
2022-01-11T00:05:13:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-01-11T00:05:13:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2022-01-11T00:05:13:     at Module.load (internal/modules/cjs/loader.js:950:32)
2022-01-11T00:05:13:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-01-11T00:05:13:     at Module.require (internal/modules/cjs/loader.js:974:19)
2022-01-11T00:05:13:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-01-11T00:05:13:     at require (internal/modules/cjs/helpers.js:93:18)
2022-01-11T00:05:13:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-01-11T00:05:13:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-01-11T00:05:14: Error: ⚠️  Couldn't find .env file  ⚠️
2022-01-11T00:05:14:     at Object.<anonymous> (/ql/back/config/index.ts:36:9)
2022-01-11T00:05:14:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-01-11T00:05:14:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2022-01-11T00:05:14:     at Module.load (internal/modules/cjs/loader.js:950:32)
2022-01-11T00:05:14:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-01-11T00:05:14:     at Module.require (internal/modules/cjs/loader.js:974:19)
2022-01-11T00:05:14:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-01-11T00:05:14:     at require (internal/modules/cjs/helpers.js:93:18)
2022-01-11T00:05:14:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-01-11T00:05:14:     at Module._compile (internal/modules/cjs/loader.js:1085:14)

=====> 检测后台

=====> 后台服务异常，重置基础环境并重启后台

---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

检测到 /ql 的依赖包有变化，运行 npm install...

Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +251
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 251, reused 9, downloaded 0, added 8

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 6.17.1 → 6.25.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v6.25.1   │
   │                 Run pnpm add -g pnpm to update.                  │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Progress: resolved 251, reused 202, downloaded 0, added 195

dependencies:
+ @otplib/preset-default 12.0.1
+ @sentry/node 6.14.1
+ @sentry/tracing 6.14.1
+ body-parser 1.19.0
+ celebrate 13.0.4
+ chokidar 3.5.2
+ cors 2.8.5
+ cron-parser 3.5.0
+ dotenv 8.6.0
+ express 4.17.1
+ express-jwt 6.1.0
+ express-urlrewrite 1.4.0
+ got 11.8.2
+ hpagent 0.1.2
+ iconv-lite 0.6.3
+ jsonwebtoken 8.5.1
+ lodash 4.17.21
+ nedb 1.8.0
+ node-fetch 2.6.5
+ node-schedule 2.0.0
+ nodemailer 6.7.0
+ p-queue 6.6.2
+ reflect-metadata 0.1.13
+ serve-handler 6.1.3
+ sockjs 0.3.21
+ typedi 0.8.0
+ uuid 8.3.2
+ winston 3.3.3
+ yargs 17.3.1

 WARN  "prepare" script of "@" inside "/ql" is skipped as the working directory seems suspicious. To run this lifecycle script anyway, use "--unsafe-perm".
Progress: resolved 251, reused 251, downloaded 0, added 251, done
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

检测到 /ql/scripts 的依赖包有变化，运行 npm install...

Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +211
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /ql/scripts/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 211, reused 209, downloaded 0, added 209

dependencies:
+ crypto-js 4.1.1
+ download 8.0.0
+ got 11.8.3
+ http-server 0.12.3
+ qrcode-terminal 0.12.0
+ request 2.88.2
+ tough-cookie 4.0.0
+ tunnel 0.0.6
+ ws 7.5.6

Progress: resolved 211, reused 211, downloaded 0, added 211, done
---> 脚本依赖安装完成

=====> 检测结束

**Comment by tanranran** [comment]
+1 而且会把磁盘跑满，检查了下，会生成一堆core.数字 的文件

![image](https://user-images.githubusercontent.com/5227840/149630711-9ef0c912-a606-4394-9d1e-eb51d57c50f1.png)

**Comment by Air433up** [comment]
> 我也遇到这个阵仗啦，请问楼主找到解决方法了吗？

设置Linux crontab定时任务，每天凌晨自动执行ql check命令，目前只有这个解决办法了

**Comment by MangoDong** [comment]
我也遇到了  求问！！
