### ISSUE TITLE
消息推送报错 

### ISSUE THREAD

**Issue by Acr05s** [whyour/qinglong#110]
oot@0e87d70c34fc:/ql $ notify test test
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/ql/scripts/sendNotify.js'
Require stack:
- /ql/shell/notify.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ql/shell/notify.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/shell/notify.js' ]

**Comment by Acr05s** [comment]
重新拉了docker 解决了
