### ISSUE TITLE
服务异常,请手动执行ql check检查服务状态

### ISSUE THREAD

**Issue by githubwjh** [whyour/qinglong#1139]
打开面板显示“服务异常,请手动执行ql check检查服务状态”，ql check修复后还是提示，重启也不行。但是脚本是在运行的，有消息推送，就是面板打不开。幸苦大佬查BUG

**Comment by bertms** [comment]
保存自己的配置文件人，然后删除docker重新安装

**Comment by asqw77918** [comment]
重新安装还是一样的异常，有谁解决了吗

**Comment by whyour** [comment]
@asqw77918 有问题贴日志  /root/.pm2/logs/panel-error.log

**Comment by FreyFei** [comment]
> 重新安装还是一样的异常，有谁解决了吗

更新镜像之后再ql check

**Comment by gituib** [comment]
docker logs  + 容器名 看看是不是跟我这个报错一样
![image](https://user-images.githubusercontent.com/35016327/152726982-2474a223-10ab-4927-9274-5c7657914027.png)


是的话按这个方法来搞：
删除重新安装一下安装的命令带上这个参数 --privileged=true
注：--privileged，该参数可以设置是否给docker容器特权，如果该参数为true，使得docker容器内的root权限为宿主机的root权限，而非只是容器内的root权限

docker run -dit -v $pwd/ql/config:/ql/config -v $pwd/ql/log:/ql/log -v $pwd/ql/db:/ql/db -v $pwd/ql/scripts:/ql/scripts -v $pwd/ql/jbot:/ql/jbot -v $pwd/ql/repo:/ql/repo -p 5700:5700 -e ENABLE_HANGUP=true -e ENABLE_WEB_PANEL=true --privileged=true --name qinglong --hostname qinglong --restart always whyour/qinglong:latest

**Comment by doghappy** [comment]
```
[root@zxz ~]# tail -n 100 panel-error.log
2022-02-06T01:20:15:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2022-02-06T01:20:15:   code: 'MODULE_NOT_FOUND',
2022-02-06T01:20:15:   requireStack: [ '/ql/build/app.js' ]
2022-02-06T01:20:15: }
2022-02-06T01:20:16: Error: Cannot find module 'reflect-metadata'
2022-02-06T01:20:16: Require stack:
2022-02-06T01:20:16: - /ql/build/app.js
2022-02-06T01:20:16:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2022-02-06T01:20:16:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2022-02-06T01:20:16:     at require (internal/modules/cjs/helpers.js:92:18)
2022-02-06T01:20:16:     at Object.<anonymous> (/ql/back/app.ts:1:1)
2022-02-06T01:20:16:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-02-06T01:20:16:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2022-02-06T01:20:16:     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-02-06T01:20:16:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-02-06T01:20:16:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2022-02-06T01:20:16:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2022-02-06T01:20:16:   code: 'MODULE_NOT_FOUND',
2022-02-06T01:20:16:   requireStack: [ '/ql/build/app.js' ]
2022-02-06T01:20:16: }
2022-02-06T01:20:17: Error: Cannot find module 'reflect-metadata'
2022-02-06T01:20:17: Require stack:
2022-02-06T01:20:17: - /ql/build/app.js
2022-02-06T01:20:17:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2022-02-06T01:20:17:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2022-02-06T01:20:17:     at require (internal/modules/cjs/helpers.js:92:18)
2022-02-06T01:20:17:     at Object.<anonymous> (/ql/back/app.ts:1:1)
2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-02-06T01:20:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2022-02-06T01:20:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-02-06T01:20:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-02-06T01:20:17:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2022-02-06T01:20:17:   code: 'MODULE_NOT_FOUND',
2022-02-06T01:20:17:   requireStack: [ '/ql/build/app.js' ]
2022-02-06T01:20:17: }
2022-02-06T01:20:17: Error: Cannot find module 'reflect-metadata'
2022-02-06T01:20:17: Require stack:
2022-02-06T01:20:17: - /ql/build/app.js
2022-02-06T01:20:17:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2022-02-06T01:20:17:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2022-02-06T01:20:17:     at require (internal/modules/cjs/helpers.js:92:18)
2022-02-06T01:20:17:     at Object.<anonymous> (/ql/back/app.ts:1:1)
2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-02-06T01:20:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2022-02-06T01:20:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-02-06T01:20:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-02-06T01:20:17:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2022-02-06T01:20:17:   code: 'MODULE_NOT_FOUND',
2022-02-06T01:20:17:   requireStack: [ '/ql/build/app.js' ]
2022-02-06T01:20:17: }
2022-02-06T01:20:17: Error: Cannot find module 'reflect-metadata'
2022-02-06T01:20:17: Require stack:
2022-02-06T01:20:17: - /ql/build/app.js
2022-02-06T01:20:17:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2022-02-06T01:20:17:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2022-02-06T01:20:17:     at require (internal/modules/cjs/helpers.js:92:18)
2022-02-06T01:20:17:     at Object.<anonymous> (/ql/back/app.ts:1:1)
2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-02-06T01:20:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2022-02-06T01:20:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-02-06T01:20:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-02-06T01:20:17:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2022-02-06T01:20:17:   code: 'MODULE_NOT_FOUND',
2022-02-06T01:20:17:   requireStack: [ '/ql/build/app.js' ]
2022-02-06T01:20:17: }
2022-02-06T01:20:18: Error: Cannot find module 'reflect-metadata'
2022-02-06T01:20:18: Require stack:
2022-02-06T01:20:18: - /ql/build/app.js
2022-02-06T01:20:18:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2022-02-06T01:20:18:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2022-02-06T01:20:18:     at require (internal/modules/cjs/helpers.js:92:18)
2022-02-06T01:20:18:     at Object.<anonymous> (/ql/back/app.ts:1:1)
2022-02-06T01:20:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-02-06T01:20:18:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2022-02-06T01:20:18:     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-02-06T01:20:18:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-02-06T01:20:18:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2022-02-06T01:20:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2022-02-06T01:20:18:   code: 'MODULE_NOT_FOUND',
2022-02-06T01:20:18:   requireStack: [ '/ql/build/app.js' ]
2022-02-06T01:20:18: }
2022-02-06T01:20:18: Error: Cannot find module 'reflect-metadata'
2022-02-06T01:20:18: Require stack:
2022-02-06T01:20:18: - /ql/build/app.js
2022-02-06T01:20:18:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2022-02-06T01:20:18:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2022-02-06T01:20:18:     at require (internal/modules/cjs/helpers.js:92:18)
2022-02-06T01:20:18:     at Object.<anonymous> (/ql/back/app.ts:1:1)
2022-02-06T01:20:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-02-06T01:20:18:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2022-02-06T01:20:18:     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-02-06T01:20:18:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-02-06T01:20:18:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2022-02-06T01:20:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
2022-02-06T01:20:18:   code: 'MODULE_NOT_FOUND',
2022-02-06T01:20:18:   requireStack: [ '/ql/build/app.js' ]
2022-02-06T01:20:18: }
```

**Comment by bibubi** [comment]
我也是

> ```
> [root@zxz ~]# tail -n 100 panel-error.log
> 2022-02-06T01:20:15:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
> 2022-02-06T01:20:15:   code: 'MODULE_NOT_FOUND',
> 2022-02-06T01:20:15:   requireStack: [ '/ql/build/app.js' ]
> 2022-02-06T01:20:15: }
> 2022-02-06T01:20:16: Error: Cannot find module 'reflect-metadata'
> 2022-02-06T01:20:16: Require stack:
> 2022-02-06T01:20:16: - /ql/build/app.js
> 2022-02-06T01:20:16:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
> 2022-02-06T01:20:16:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
> 2022-02-06T01:20:16:     at require (internal/modules/cjs/helpers.js:92:18)
> 2022-02-06T01:20:16:     at Object.<anonymous> (/ql/back/app.ts:1:1)
> 2022-02-06T01:20:16:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
> 2022-02-06T01:20:16:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> 2022-02-06T01:20:16:     at Module.load (internal/modules/cjs/loader.js:937:32)
> 2022-02-06T01:20:16:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> 2022-02-06T01:20:16:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
> 2022-02-06T01:20:16:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
> 2022-02-06T01:20:16:   code: 'MODULE_NOT_FOUND',
> 2022-02-06T01:20:16:   requireStack: [ '/ql/build/app.js' ]
> 2022-02-06T01:20:16: }
> 2022-02-06T01:20:17: Error: Cannot find module 'reflect-metadata'
> 2022-02-06T01:20:17: Require stack:
> 2022-02-06T01:20:17: - /ql/build/app.js
> 2022-02-06T01:20:17:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
> 2022-02-06T01:20:17:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
> 2022-02-06T01:20:17:     at require (internal/modules/cjs/helpers.js:92:18)
> 2022-02-06T01:20:17:     at Object.<anonymous> (/ql/back/app.ts:1:1)
> 2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
> 2022-02-06T01:20:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> 2022-02-06T01:20:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
> 2022-02-06T01:20:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> 2022-02-06T01:20:17:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
> 2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
> 2022-02-06T01:20:17:   code: 'MODULE_NOT_FOUND',
> 2022-02-06T01:20:17:   requireStack: [ '/ql/build/app.js' ]
> 2022-02-06T01:20:17: }
> 2022-02-06T01:20:17: Error: Cannot find module 'reflect-metadata'
> 2022-02-06T01:20:17: Require stack:
> 2022-02-06T01:20:17: - /ql/build/app.js
> 2022-02-06T01:20:17:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
> 2022-02-06T01:20:17:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
> 2022-02-06T01:20:17:     at require (internal/modules/cjs/helpers.js:92:18)
> 2022-02-06T01:20:17:     at Object.<anonymous> (/ql/back/app.ts:1:1)
> 2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
> 2022-02-06T01:20:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> 2022-02-06T01:20:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
> 2022-02-06T01:20:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> 2022-02-06T01:20:17:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
> 2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
> 2022-02-06T01:20:17:   code: 'MODULE_NOT_FOUND',
> 2022-02-06T01:20:17:   requireStack: [ '/ql/build/app.js' ]
> 2022-02-06T01:20:17: }
> 2022-02-06T01:20:17: Error: Cannot find module 'reflect-metadata'
> 2022-02-06T01:20:17: Require stack:
> 2022-02-06T01:20:17: - /ql/build/app.js
> 2022-02-06T01:20:17:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
> 2022-02-06T01:20:17:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
> 2022-02-06T01:20:17:     at require (internal/modules/cjs/helpers.js:92:18)
> 2022-02-06T01:20:17:     at Object.<anonymous> (/ql/back/app.ts:1:1)
> 2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
> 2022-02-06T01:20:17:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> 2022-02-06T01:20:17:     at Module.load (internal/modules/cjs/loader.js:937:32)
> 2022-02-06T01:20:17:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> 2022-02-06T01:20:17:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
> 2022-02-06T01:20:17:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
> 2022-02-06T01:20:17:   code: 'MODULE_NOT_FOUND',
> 2022-02-06T01:20:17:   requireStack: [ '/ql/build/app.js' ]
> 2022-02-06T01:20:17: }
> 2022-02-06T01:20:18: Error: Cannot find module 'reflect-metadata'
> 2022-02-06T01:20:18: Require stack:
> 2022-02-06T01:20:18: - /ql/build/app.js
> 2022-02-06T01:20:18:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
> 2022-02-06T01:20:18:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
> 2022-02-06T01:20:18:     at require (internal/modules/cjs/helpers.js:92:18)
> 2022-02-06T01:20:18:     at Object.<anonymous> (/ql/back/app.ts:1:1)
> 2022-02-06T01:20:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
> 2022-02-06T01:20:18:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> 2022-02-06T01:20:18:     at Module.load (internal/modules/cjs/loader.js:937:32)
> 2022-02-06T01:20:18:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> 2022-02-06T01:20:18:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
> 2022-02-06T01:20:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
> 2022-02-06T01:20:18:   code: 'MODULE_NOT_FOUND',
> 2022-02-06T01:20:18:   requireStack: [ '/ql/build/app.js' ]
> 2022-02-06T01:20:18: }
> 2022-02-06T01:20:18: Error: Cannot find module 'reflect-metadata'
> 2022-02-06T01:20:18: Require stack:
> 2022-02-06T01:20:18: - /ql/build/app.js
> 2022-02-06T01:20:18:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
> 2022-02-06T01:20:18:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
> 2022-02-06T01:20:18:     at require (internal/modules/cjs/helpers.js:92:18)
> 2022-02-06T01:20:18:     at Object.<anonymous> (/ql/back/app.ts:1:1)
> 2022-02-06T01:20:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
> 2022-02-06T01:20:18:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> 2022-02-06T01:20:18:     at Module.load (internal/modules/cjs/loader.js:937:32)
> 2022-02-06T01:20:18:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> 2022-02-06T01:20:18:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.1/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
> 2022-02-06T01:20:18:     at Module._compile (internal/modules/cjs/loader.js:1072:14) {
> 2022-02-06T01:20:18:   code: 'MODULE_NOT_FOUND',
> 2022-02-06T01:20:18:   requireStack: [ '/ql/build/app.js' ]
> 2022-02-06T01:20:18: }
> ```

我也是这个问题

**Comment by bertms** [comment]
直接删除所有容器，从0开始来，我是这样解决的，记得提前备份你config文件夹

**Comment by xufeiwu123** [comment]
![111838a031417541](https://user-images.githubusercontent.com/34909400/153706052-b59c9d28-f1d3-4331-8e0e-82ab0d493770.png)
我的是这样
