### ISSUE TITLE
在容器内执行 ql update，提示Cannot find module 'body-parser'

### ISSUE THREAD

**Issue by Nicolas-Gong** [whyour/qinglong#1205]
`
2022-03-04T20:22:00: Error: Cannot find module 'body-parser'
2022-03-04T20:22:00: Require stack:
2022-03-04T20:22:00: - /ql/build/loaders/express.js
2022-03-04T20:22:00: - /ql/build/loaders/app.js
2022-03-04T20:22:00: - /ql/build/app.js
2022-03-04T20:22:00:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2022-03-04T20:22:00:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2022-03-04T20:22:00:     at require (node:internal/modules/cjs/helpers:102:18)
2022-03-04T20:22:00:     at Object.<anonymous> (/ql/back/loaders/express.ts:2:1)
2022-03-04T20:22:00:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
2022-03-04T20:22:00:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
2022-03-04T20:22:00:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-03-04T20:22:00:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-03-04T20:22:00:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-03-04T20:22:00:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-03-04T20:22:00:     at require (node:internal/modules/cjs/helpers:102:18)
2022-03-04T20:22:00:     at Object.<anonymous> (/ql/back/loaders/app.ts:1:1)
2022-03-04T20:22:00:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
2022-03-04T20:22:00:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
2022-03-04T20:22:00:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-03-04T20:22:00:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-03-04T20:22:00:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-03-04T20:22:00:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-03-04T20:22:00:     at require (node:internal/modules/cjs/helpers:102:18)
2022-03-04T20:22:00:     at startServer (/ql/back/app.ts:18:9) {
2022-03-04T20:22:00:   code: 'MODULE_NOT_FOUND',
2022-03-04T20:22:00:   requireStack: [
2022-03-04T20:22:00:     '/ql/build/loaders/express.js',
2022-03-04T20:22:00:     '/ql/build/loaders/app.js',
2022-03-04T20:22:00:     '/ql/build/app.js'
2022-03-04T20:22:00:   ]
2022-03-04T20:22:00: }
2022-03-04T20:22:00: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-03-04T20:22:00: Error: Cannot find module 'body-parser'
2022-03-04T20:22:00: Require stack:
2022-03-04T20:22:00: - /ql/build/loaders/express.js
2022-03-04T20:22:00: - /ql/build/loaders/app.js
2022-03-04T20:22:00: - /ql/build/app.js
2022-03-04T20:22:00:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2022-03-04T20:22:00:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2022-03-04T20:22:00:     at require (node:internal/modules/cjs/helpers:102:18)
2022-03-04T20:22:00:     at Object.<anonymous> (/ql/back/loaders/express.ts:2:1)
2022-03-04T20:22:00:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
2022-03-04T20:22:00:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
2022-03-04T20:22:00:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-03-04T20:22:00:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-03-04T20:22:00:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-03-04T20:22:00:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-03-04T20:22:00:     at require (node:internal/modules/cjs/helpers:102:18)
2022-03-04T20:22:00:     at Object.<anonymous> (/ql/back/loaders/app.ts:1:1)
2022-03-04T20:22:00:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
2022-03-04T20:22:00:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
2022-03-04T20:22:00:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-03-04T20:22:00:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-03-04T20:22:00:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-03-04T20:22:00:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-03-04T20:22:00:     at require (node:internal/modules/cjs/helpers:102:18)
2022-03-04T20:22:00:     at startServer (/ql/back/app.ts:18:9)

=====> 检测后台

{"code":200,"data":{"username":"root"}}

=====> 后台服务启动正常

=====> 检测结束

## 执行结束... 2022-03-04 20:34:00  耗时 3 秒
`

手动在ql目录下安装了ql check还是报错，然后又去scripts内安装了下ql check还是报错，不知道为啥。。。

**Comment by cc9014** [comment]
意思就是缺少'body-parser'这个模块。我看了下我的/ql文件夹里面是有body-parser的。你要么手动装一个再试试。
[https://www.npmjs.com/package/body-parser](url)

**Comment by Nicolas-Gong** [comment]
> 意思就是缺少'body-parser'这个模块。我看了下我的/ql文件夹里面是有body-parser的。你要么手动装一个再试试。 [https://www.npmjs.com/package/body-parser](url)

![image](https://user-images.githubusercontent.com/23067153/156956628-f85cc9e6-9cc5-497e-aff2-f2287a42da42.png)
手动安装了个几次，还是报这个错误，然后我到ql/node_modules下看到实际是有这个模块的。

**Comment by Nicolas-Gong** [comment]
> 意思就是缺少'body-parser'这个模块。我看了下我的/ql文件夹里面是有body-parser的。你要么手动装一个再试试。 [https://www.npmjs.com/package/body-parser](url)

强迫症看着太难受了，今天重装镜像后就没这个问题了。
