### ISSUE TITLE
npm ERR! Cannot read properties of null (reading 'matches')

### ISSUE THREAD

**Issue by netlovehf** [whyour/qinglong#1235]
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-17T02_10_17_406Z-debug-0.log

**Comment by netlovehf** [comment]
6433 verbose stack TypeError: Cannot read properties of null (reading 'matches')
16433 verbose stack     at Link.matches (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1090:41)
16433 verbose stack     at Link.canDedupe (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1044:15)
16433 verbose stack     at PlaceDep.pruneDedupable (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:465:14)
16433 verbose stack     at PlaceDep.placeInTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:326:14)
16433 verbose stack     at PlaceDep.place (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:214:10)
16433 verbose stack     at new PlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:71:10)
16433 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:964:31
16433 verbose stack     at Array.map (<anonymous>)
16433 verbose stack     at Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:964:8)
16433 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
16434 verbose cwd /ql/scripts
16435 verbose Linux 5.10.0-12-amd64
16436 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas" "--build-from-source"
16437 verbose node v17.5.0
16438 verbose npm  v8.5.5
16439 error Cannot read properties of null (reading 'matches')
16440 verbose exit 1
16441 timing npm Completed in 150113ms
16442 verbose unfinished npm timer reify 1647574599139
16443 verbose unfinished npm timer reify:loadTrees 1647574599171
16444 verbose unfinished npm timer idealTree:buildDeps 1647574601570
16445 verbose unfinished npm timer idealTree:node_modules/.pnpm/registry.npmmirror.com+ajv@6.12.6/node_modules/ajv 1647574664695
16446 verbose unfinished npm timer idealTree:node_modules/.pnpm/registry.npmmirror.com+mkdirp@0.5.5/node_modules/tap 1647574718028
16447 verbose unfinished npm timer idealTree:node_modules/@marionebl/sander 1647574748261
16448 verbose code 1
16449 error A complete log of this run can be found in:
16449 error     /root/.npm/_logs/2022-03-18T03_36_38_220Z-debug-0.log
