### ISSUE TITLE
报错信息：Couldn't find .env file 

### ISSUE THREAD

**Issue by SouthWindLoki** [whyour/qinglong#1286]
28|panel   | 2022-03-29T04:27:40: Error: ⚠️  Couldn't find .env file  ⚠️
28|panel   | 2022-03-29T04:27:40:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
28|panel   | 2022-03-29T04:27:40:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
28|panel   | 2022-03-29T04:27:40:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
28|panel   | 2022-03-29T04:27:40:     at Module.load (node:internal/modules/cjs/loader:975:32)
28|panel   | 2022-03-29T04:27:40:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
28|panel   | 2022-03-29T04:27:40:     at Module.require (node:internal/modules/cjs/loader:999:19)
28|panel   | 2022-03-29T04:27:40:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
28|panel   | 2022-03-29T04:27:40:     at require (node:internal/modules/cjs/helpers:102:18)
28|panel   | 2022-03-29T04:27:40:     at Object.<anonymous> (/ql/back/app.ts:3:1)
28|panel   | 2022-03-29T04:27:40:     at Module._compile (node:internal/modules/cjs/loader:1099:14)

**Comment by vc5** [comment]
```
11|panel   | 2022-03-29T04:13:14: info:    ✌️ Server need close
11|panel   | 2022-03-29T04:13:14: info:    ✌️ Server closed
11|panel   | 2022-03-29T23:12:50: info:    ✌️ Init file down
11|panel   | 2022-03-29T23:12:50: info:    ✌️ Sentry loaded
11|panel   | 2022-03-29T23:12:50: info:    ✌️ DB loaded
11|panel   | 2022-03-29T23:12:51: info:    ✌️ Dependency Injector loaded
11|panel   | 2022-03-29T23:12:51: info:    ✌️ Express loaded
11|panel   | 2022-03-29T23:12:51: info:    [创建interval任务]，任务ID: 15，任务名: 删除日志，执行命令: ql rmlog 7
11|panel   | 2022-03-29T23:12:51: info:    ✌️ init data loaded
11|panel   | 2022-03-29T23:12:51: info:    ✌️ link deps
11|panel   | 2022-03-29T23:12:51: info:    ✌️ Sock loaded
11|panel   | 2022-03-29T23:12:51: info:    
11|panel   | 2022-03-29T23:12:51:       ################################################
11|panel   | 2022-03-29T23:12:51:       🛡️  Server listening on port: 5600 🛡️
11|panel   | 2022-03-29T23:12:51:       ################################################
11|panel   | 2022-03-29T23:12:51:     
11|panel   | 2022-03-29T23:14:22: info:    task shufflewzc_faker2_main/jd_cash.js pid: 22323 exit 0 signal null
11|panel   | 2022-03-29T23:14:22: info:    task shufflewzc_faker2_main/jd_cash.js pid: 22323 closed 0
11|panel   | 2022-03-30T04:13:13: info:    ✌️ Server need close
11|panel   | 2022-03-30T04:13:13: info:    ✌️ Server closed

/root/.pm2/logs/panel-error.log last 500 lines:
11|panel   | 2022-03-28T04:13:15:     at Module.require (node:internal/modules/cjs/loader:999:19)
11|panel   | 2022-03-28T04:13:15:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
11|panel   | 2022-03-28T04:13:15:     at require (node:internal/modules/cjs/helpers:102:18)
11|panel   | 2022-03-28T04:13:15:     at Object.<anonymous> (/ql/back/app.ts:3:1)
11|panel   | 2022-03-28T04:13:15:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
11|panel   | 2022-03-28T04:13:15: Error: ⚠️  Couldn't find .env file  ⚠️
11|panel   | 2022-03-28T04:13:15:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
11|panel   | 2022-03-28T04:13:15:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
11|panel   | 2022-03-28T04:13:15:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
11|panel   | 2022-03-28T04:13:15:     at Module.load (node:internal/modules/cjs/loader:975:32)
11|panel   | 2022-03-28T04:13:15:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
11|panel   | 2022-03-28T04:13:15:     at Module.require (node:internal/modules/cjs/loader:999:19)
11|panel   | 2022-03-28T04:13:15:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
11|panel   | 2022-03-28T04:13:15:     at require (node:internal/modules/cjs/helpers:102:18)
11|panel   | 2022-03-28T04:13:15:     at Object.<anonymous> (/ql/back/app.ts:3:1)
11|panel   | 2022-03-28T04:13:15:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
```
类似的问题，每天都会出现，必须要`ql check`才能恢复

**Comment by SouthWindLoki** [comment]
> 
是的，是丢失了什么文件了吗

**Comment by guakeliao** [comment]
我也是这个情况。每天得check一次才能进去

**Comment by gyq180** [comment]
一样一样

**Comment by vc5** [comment]
经过检查，在面板无法进入，并报错` Couldn't find .env **file`时，进入容器终端，发现.env文件是存在的，初步判断面板运行过程中**当前目录**出现了异常

**Comment by guakeliao** [comment]
容器重启之后，直接报错了。错误信息也没有，尝试了ql check 都无效
![image](https://user-images.githubusercontent.com/9064387/164953560-6d40d6c6-5385-4d8a-af75-bcc435a64d89.png)

**Comment by huxc573** [comment]
一样的情况，实际上任务好像还在跑。能收到通知。每次需要停止容器，等CPU掉下来再重启，才能成功进入面板界面。
