### ISSUE TITLE
群晖docker+青龙，安装dotneta 安装不了

### ISSUE THREAD

**Issue by Unicorni** [whyour/qinglong#1312]
你好，作者，我是用家庭NAS群晖docker+青龙面板，在运行哔哩哔哩那个脚本时，需要安装dotneta ，这个依赖，还有运行脚本的时候，总报这个错误。
日志-bili测试ck
## 开始执行... 2022-04-08 10:49:50

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_test.sh: line 8: 27489 Aborted                 dotnet run --project ./src/Ray.BiliBiliTool.Console --ENVIRONMENT=Production --runTasks=Test

## 执行结束... 2022-04-08 10:49:54 耗时 4 秒

教程地址：https://www.dzdxtd.com/archives/213

2.还有米游社教程地址：https://www.kejiwanjia.com/jiaocheng/46595.html
报：
日志-米游社单用户
## 开始执行... 2022-04-08 11:01:17

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 86, in <module>
    status_code, message = main()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/main.py", line 17, in main
    config.load_config()
  File "/ql/data/scripts/Womsxd_AutoMihoyoBBS/config.py", line 45, in load_config
    with open(config_Path, "r") as f:
NotADirectoryError: [Errno 20] Not a directory: '/ql/data/scripts/Womsxd_AutoMihoyoBBS/config/config.json'

## 执行结束... 2022-04-08 11:01:23 耗时 6 秒

谢谢作者帮忙看一看，还望指点^ω^

**Comment by cc9014** [comment]
> Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.

看第一行的意思，需要先自己用包管理器安装libicu，然后再往后走。

**Comment by hahashifeng** [comment]
你把面板上的Linux依赖删掉，然后再运行这个就可以了，亲测已搞定

**Comment by yehuzhucha** [comment]
> 你把面板上的Linux依赖删掉，然后再运行这个就可以了，亲测已搞定

可用，非常感谢！
