### ISSUE TITLE
重启后青龙服务错误，和清空 logs 数值有关吗

### ISSUE THREAD

**Issue by miaoermua** [whyour/qinglong#1319]
在一次重启后青龙面板显示服务错误；大概和设置清空 logs 有关不知道是不是 Bug，昨天设置的 20 多天就清空 logs，今天机器出了点问题重启就这样了，烦请修复不知道这样交 issues 正确不多多理解。

环境：
Docker 青龙 v2.12.1
Operating System: Ubuntu 20.04.3 LTS
Kernel: Linux 5.4.0-107-generic

脚本内容打星号、近乎相同的log打省略号处理

错误：
```logs
pm2 logs panel
[TAILING] Tailing last 500 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-out.log last 500 lines:
1|panel    | 2022-04-07T23:28:50: info:    task **/**.js pid: 40624 exit 0 signal null

…………

1|panel    | 2022-04-09T11:18:33: info:    task **/**.js pid: 63471 closed 0
1|panel    | 2022-04-09T11:23:06: info:    [取消interval任务]，任务ID: 10，任务名：删除日志
1|panel    | 2022-04-09T11:23:06: info:    [创建interval任务]，任务ID: 10，任务名: 删除日志，执行命令: ql rmlog 30
1|panel    | 2022-04-09T11:23:06: error:   🔥 error: Error: Due to setInterval limitations, no intervals longer than 24.85 days can be scheduled correctly. Please create LongIntervalJob instead.
1|panel    | 2022-04-09T11:23:06:     at SimpleIntervalJob.start (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalJob.js:16:19)
1|panel    | 2022-04-09T11:23:06:     at SimpleIntervalEngine.add (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalEngine.js:12:13)
1|panel    | 2022-04-09T11:23:06:     at ToadScheduler.addIntervalJob (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/toadScheduler.js:20:43)
1|panel    | 2022-04-09T11:23:06:     at ScheduleService.createIntervalTask (/ql/back/services/schedule.ts:128:27)
1|panel    | 2022-04-09T11:23:06:     at SystemService.updateLogRemoveFrequency (/ql/back/services/system.ts:71:34)
1|panel    | 2022-04-09T11:23:06:     at /ql/back/api/system.ts:74:24 {
1|panel    | 2022-04-09T11:23:06:   [stack]: 'Error: Due to setInterval limitations, no intervals longer than 24.85 days can be scheduled correctly. Please create LongIntervalJob instead.\n' +
1|panel    | 2022-04-09T11:23:06:     '    at SimpleIntervalJob.start (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalJob.js:16:19)\n' +
1|panel    | 2022-04-09T11:23:06:     '    at SimpleIntervalEngine.add (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalEngine.js:12:13)\n' +
1|panel    | 2022-04-09T11:23:06:     '    at ToadScheduler.addIntervalJob (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/toadScheduler.js:20:43)\n' +
1|panel    | 2022-04-09T11:23:06:     '    at ScheduleService.createIntervalTask (/ql/back/services/schedule.ts:128:27)\n' +
1|panel    | 2022-04-09T11:23:06:     '    at SystemService.updateLogRemoveFrequency (/ql/back/services/system.ts:71:34)\n' +
1|panel    | 2022-04-09T11:23:06:     '    at /ql/back/api/system.ts:74:24',
1|panel    | 2022-04-09T11:23:06:   [message]: 'Due to setInterval limitations, no intervals longer than 24.85 days can be scheduled correctly. Please create LongIntervalJob instead.'
1|panel    | 2022-04-09T11:23:06: }
1|panel    | 2022-04-09T11:23:12: info:    [取消interval任务]，任务ID: 10，任务名：删除日志
1|panel    | 2022-04-09T11:23:12: info:    [创建interval任务]，任务ID: 10，任务名: 删除日志，执行命令: ql rmlog 20
1|panel    | 2022-04-09T15:20:04: info:    task **/**.js pid: 73901 exit 0 signal null

……

1|panel    | 2022-04-10T23:55:06: info:    [创建interval任务]，任务ID: 10，任务名: 删除日志，执行命令: ql rmlog 30
1|panel    | 2022-04-10T23:57:27: info:    ✌️ Init file down
1|panel    | 2022-04-10T23:57:28: info:    ✌️ Sentry loaded
1|panel    | 2022-04-10T23:57:29: info:    ✌️ DB loaded
1|panel    | 2022-04-10T23:57:29: info:    ✌️ Dependency Injector loaded
1|panel    | 2022-04-10T23:57:30: info:    ✌️ Express loaded
1|panel    | 2022-04-10T23:57:30: info:    [创建interval任务]，任务ID: 10，任务名: 删除日志，执行命令: ql rmlog 30
1|panel    | 2022-04-11T00:00:29: info:    ✌️ Init file down
1|panel    | 2022-04-11T00:00:29: info:    ✌️ Sentry loaded
1|panel    | 2022-04-11T00:00:30: info:    ✌️ DB loaded
1|panel    | 2022-04-11T00:00:31: info:    ✌️ Dependency Injector loaded
1|panel    | 2022-04-11T00:00:31: info:    ✌️ Express loaded
1|panel    | 2022-04-11T00:00:31: info:    [创建interval任务]，任务ID: 10，任务名: 删除日志，执行命令: ql rmlog 30
1|panel    | 2022-04-11T00:22:44: info:    ✌️ Init file down
1|panel    | 2022-04-11T00:22:46: info:    ✌️ Sentry loaded
1|panel    | 2022-04-11T00:22:49: info:    ✌️ DB loaded
1|panel    | 2022-04-11T00:22:51: info:    ✌️ Dependency Injector loaded
1|panel    | 2022-04-11T00:22:51: info:    ✌️ Express loaded
1|panel    | 2022-04-11T00:22:52: info:    [创建interval任务]，任务ID: 10，任务名: 删除日志，执行命令: ql rmlog 30

/root/.pm2/logs/panel-error.log last 500 lines:
1|panel    | 2022-04-10T23:51:05: Error: Due to setInterval limitations, no intervals longer than 24.85 days can be scheduled correctly. Please create LongIntervalJob instead.
1|panel    | 2022-04-10T23:51:05:     at SimpleIntervalJob.start (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalJob.js:16:19)
1|panel    | 2022-04-10T23:51:05:     at SimpleIntervalEngine.add (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalEngine.js:12:13)
1|panel    | 2022-04-10T23:51:05:     at ToadScheduler.addIntervalJob (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/toadScheduler.js:20:43)
1|panel    | 2022-04-10T23:51:05:     at ScheduleService.createIntervalTask (/ql/back/services/schedule.ts:128:27)
1|panel    | 2022-04-10T23:51:05:     at exports.default (/ql/back/loaders/initData.ts:131:27)
1|panel    | 2022-04-10T23:51:05:     at Object.exports.default (/ql/back/loaders/app.ts:17:3)
1|panel    | 2022-04-10T23:51:05:     at startServer (/ql/back/app.ts:18:3)
1|panel    | 2022-04-10T23:51:05: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
1|panel    | 2022-04-10T23:51:05: Error: Due to setInterval limitations, no intervals longer than 24.85 days can be scheduled correctly. Please create LongIntervalJob instead.
1|panel    | 2022-04-10T23:51:05:     at SimpleIntervalJob.start (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalJob.js:16:19)
1|panel    | 2022-04-10T23:51:05:     at SimpleIntervalEngine.add (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalEngine.js:12:13)
1|panel    | 2022-04-10T23:51:05:     at ToadScheduler.addIntervalJob (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/toadScheduler.js:20:43)
1|panel    | 2022-04-10T23:51:05:     at ScheduleService.createIntervalTask (/ql/back/services/schedule.ts:128:27)
1|panel    | 2022-04-10T23:51:05:     at exports.default (/ql/back/loaders/initData.ts:131:27)
1|panel    | 2022-04-10T23:51:05:     at Object.exports.default (/ql/back/loaders/app.ts:17:3)
1|panel    | 2022-04-10T23:51:05:     at startServer (/ql/back/app.ts:18:3)
1|panel    | 2022-04-10T23:52:36: Error: Due to setInterval limitations, no intervals longer than 24.85 days can be scheduled correctly. Please create LongIntervalJob instead.
1|panel    | 2022-04-10T23:52:36:     at SimpleIntervalJob.start (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalJob.js:16:19)
1|panel    | 2022-04-10T23:52:36:     at SimpleIntervalEngine.add (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalEngine.js:12:13)
1|panel    | 2022-04-10T23:52:36:     at ToadScheduler.addIntervalJob (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/toadScheduler.js:20:43)
1|panel    | 2022-04-10T23:52:36:     at ScheduleService.createIntervalTask (/ql/back/services/schedule.ts:128:27)
1|panel    | 2022-04-10T23:52:36:     at exports.default (/ql/back/loaders/initData.ts:131:27)
1|panel    | 2022-04-10T23:52:36:     at Object.exports.default (/ql/back/loaders/app.ts:17:3)
1|panel    | 2022-04-10T23:52:36:     at startServer (/ql/back/app.ts:18:3)

……

1|panel    | 2022-04-11T00:22:52: Error: Due to setInterval limitations, no intervals longer than 24.85 days can be scheduled correctly. Please create LongIntervalJob instead.
1|panel    | 2022-04-11T00:22:52:     at SimpleIntervalJob.start (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalJob.js:16:19)
1|panel    | 2022-04-11T00:22:52:     at SimpleIntervalEngine.add (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/engines/simple-interval/SimpleIntervalEngine.js:12:13)
1|panel    | 2022-04-11T00:22:52:     at ToadScheduler.addIntervalJob (/ql/node_modules/.pnpm/toad-scheduler@1.6.0/node_modules/toad-scheduler/dist/lib/toadScheduler.js:20:43)
1|panel    | 2022-04-11T00:22:52:     at ScheduleService.createIntervalTask (/ql/back/services/schedule.ts:128:27)
1|panel    | 2022-04-11T00:22:52:     at exports.default (/ql/back/loaders/initData.ts:131:27)
1|panel    | 2022-04-11T00:22:52:     at Object.exports.default (/ql/back/loaders/app.ts:17:3)
1|panel    | 2022-04-11T00:22:52:     at startServer (/ql/back/app.ts:18:3)
```

面板内配置已下载，并且重新部署

**Comment by miaoermua** [comment]
不知道是不是哪里出问题了，感觉不像是青龙的问题，还在排查中……

**Comment by Kaystar** [comment]
我之前从2.11升2.12遇到过，应该是之前在系统设置-其他设置-日志删除频率中设置了天数的问题

**Comment by miaoermua** [comment]
> 

是吧，应该就是30天喜欢凑整🤣

**Comment by Kaystar** [comment]
> > 
> 
> 是吧，应该就是30天喜欢凑整🤣

我之前也是设置的30天，要想用2.12只能从头重新来过了，不能用旧的备份文件直接升级。
尝试过回到旧版去修改日志删除频率天数，想着修改了再升级2.12，结果显示修改成功，刷新一下就还原了，无解，只能重新从头来

**Comment by miaoermua** [comment]
> > > 
> > 
> > 
> > 是吧，应该就是30天喜欢凑整🤣
> 
> 我之前也是设置的30天，要想用2.12只能从头重新来过了，不能用旧的备份文件直接升级。 尝试过回到旧版去修改日志删除频率天数，想着修改了再升级2.12，结果显示修改成功，但是刷新一下就还原回30天了，无解，只能重新从头来

希望能修了吧，没办法咯只能从零开始了

**Comment by Kaystar** [comment]
> > > > 
> > > 
> > > 
> > > 是吧，应该就是30天喜欢凑整🤣
> > 
> > 
> > 我之前也是设置的30天，要想用2.12只能从头重新来过了，不能用旧的备份文件直接升级。 尝试过回到旧版去修改日志删除频率天数，想着修改了再升级2.12，结果显示修改成功，但是刷新一下就还原回30天了，无解，只能重新从头来
> 
> 希望能修了吧，没办法咯只能从零开始了

修是不可能修的，从头来过吧

**Comment by SharpX2016** [comment]
同样问题，日志删除周期过大，设置完后再修改数值提示成功，但是一刷新就还原，重启面板就会挂掉。
而且就算正常数值只要设置过就无法修改，再修改数值提示成功，但是一刷新就还原

**Comment by miaoermua** [comment]
补 最新v2.12.2 好像修复了，但不是太敢设置了，毕竟搞废了一次
