### ISSUE TITLE
最新版启动脚本报错

### ISSUE THREAD

**Issue by oschina365** [whyour/qinglong#1321]
TypeError: Cannot read properties of null (reading '1')
    at new _0x58e1a2 (/ql/scripts/Yiov_wool/ks.js:32:9040)
    at _0x5c8b6b (/ql/scripts/Yiov_wool/ks.js:32:82287)
    at Object.EfDwn (/ql/scripts/Yiov_wool/ks.js:32:71924)
    at /ql/scripts/Yiov_wool/ks.js:32:72707
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Jingle-Pan** [comment]
修改路径/ql/data/scripts/Yiov_wool/ks.js

**Comment by Jingle-Pan** [comment]
> > 修改路径/ql/data/scripts/Yiov_wool/ks.js
> 
> 这个脚本修改什么？

1.把ks.js这个文件放到/ql/data/scripts/Yiov_wool/路径下
2.在里运行代码中找到ks.js指定路径修改
