### ISSUE TITLE
更新完之后面板进不去了 提示Couldn't find .env file

### ISSUE THREAD

**Issue by 344108150** [whyour/qinglong#1332]
大神能帮我看一下嘛

root@qinglong:/ql/data $ ql check
## 开始执行... 2022-04-15 15:08:41

=====> 开始检测
Progress: resolved 0, reused 1, downloaded 0, added 0
Progress: resolved 3, reused 3, downloaded 0, added 0
Progress: resolved 4, reused 3, downloaded 0, added 0
Progress: resolved 41, reused 41, downloaded 0, added 0
Progress: resolved 62, reused 61, downloaded 0, added 0
Progress: resolved 118, reused 112, downloaded 0, added 0
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 149, reused 148, downloaded 0, added 0
Progress: resolved 171, reused 170, downloaded 0, added 0
Progress: resolved 176, reused 175, downloaded 0, added 0
Progress: resolved 183, reused 182, downloaded 0, added 0
Progress: resolved 184, reused 182, downloaded 0, added 0
Progress: resolved 184, reused 183, downloaded 0, added 0
Progress: resolved 185, reused 183, downloaded 0, added 0
Progress: resolved 188, reused 187, downloaded 0, added 0
Progress: resolved 194, reused 193, downloaded 0, added 0
Already up-to-date
Progress: resolved 194, reused 193, downloaded 0, added 0, done

 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.a72f2539.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.21
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="/umi.e12d55a8.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   42 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
  256 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2022-04-15T14:50:36: info:    ✌️ Init file down
2022-04-15T14:50:36: info:    ✌️ Sentry loaded
2022-04-15T14:50:38: info:    ✌️ DB loaded
2022-04-15T14:50:39: info:    ✌️ Dependency Injector loaded
2022-04-15T14:50:39: info:    ✌️ Express loaded
2022-04-15T14:50:39: info:    ✌️ init data loaded
2022-04-15T14:50:39: info:    ✌️ link deps
2022-04-15T14:50:39: info:    ✌️ Sock loaded
2022-04-15T14:50:39: info:    
2022-04-15T14:50:39:       ################################################
2022-04-15T14:50:39:       🛡️  Server listening on port: 5600 🛡️
2022-04-15T14:50:39:       ################################################
2022-04-15T14:50:39:     
2022-04-15T14:52:31: info:    ✌️ Server need close
2022-04-15T14:52:31: info:    ✌️ Server closed
2022-04-15T14:52:32: info:    ✌️ Init file down
2022-04-15T14:52:33: info:    ✌️ Sentry loaded
2022-04-15T14:52:34: info:    ✌️ DB loaded
2022-04-15T14:52:34: info:    ✌️ Dependency Injector loaded
2022-04-15T14:52:35: info:    ✌️ Express loaded
2022-04-15T14:52:35: info:    ✌️ init data loaded
2022-04-15T14:52:35: info:    ✌️ link deps
2022-04-15T14:52:35: info:    ✌️ Sock loaded
2022-04-15T14:52:35: info:    
2022-04-15T14:52:35:       ################################################
2022-04-15T14:52:35:       🛡️  Server listening on port: 5600 🛡️
2022-04-15T14:52:35:       ################################################
2022-04-15T14:52:35:     
2022-04-15T14:57:29: info:    ✌️ Server need close
2022-04-15T14:57:29: info:    ✌️ Server closed
2022-04-15T14:57:37:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:37: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:37:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:37:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:37:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:37:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:37:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:37:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:37:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:37:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:37:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:38: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:38:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:38:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:38:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:38:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:38:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:38:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:38:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:38:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:38:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:39: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:39:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:39:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:39:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:39:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:39:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:39:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:39:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:39:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:39:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:39:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:40: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:40:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:40:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:40:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:40:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:40:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:40:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:40:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:40:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:40:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:40:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:41: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:41:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:41:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:41:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:41:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:41:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:41:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:41:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:41:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:41:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:41:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:42: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:42:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:42:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:42:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:42:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:42:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:42:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:42:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:42:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:42:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:42:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:43: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:43:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:43:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:43:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:43:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:43:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:43:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:43:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:43:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:43:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:43:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:44: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:44:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:44:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:44:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:44:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:44:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:44:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:44:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:44:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:44:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:44:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:45: Error: ⚠️  Couldn't find .env file  ⚠️
2022-04-15T14:57:45:     at Object.<anonymous> (/ql/back/config/index.ts:34:9)
2022-04-15T14:57:45:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
2022-04-15T14:57:45:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2022-04-15T14:57:45:     at Module.load (node:internal/modules/cjs/loader:975:32)
2022-04-15T14:57:45:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-04-15T14:57:45:     at Module.require (node:internal/modules/cjs/loader:999:19)
2022-04-15T14:57:45:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39)
2022-04-15T14:57:45:     at require (node:internal/modules/cjs/helpers:102:18)
2022-04-15T14:57:45:     at Object.<anonymous> (/ql/back/app.ts:3:1)
2022-04-15T14:57:45:     at Module._compile (node:internal/modules/cjs/loader:1099:14)

=====> 检测后台

=====> 后台服务异常，重置基础环境并重启后台

---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

检测到 /ql 的依赖包有变化，运行 npm install...

Lockfile is up-to-date, resolution step is skipped
Already up-to-date

devDependencies: skipped

 WARN  "prepare" script of "@" inside "/ql" is skipped as the working directory seems suspicious. To run this lifecycle script anyway, use "--unsafe-perm".
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

检测到 /ql/data/scripts 的依赖包有变化，运行 npm install...

Lockfile is up-to-date, resolution step is skipped
Already up-to-date

devDependencies: skipped

---> 脚本依赖安装完成

=====> 检测结束

**Comment by gyq180** [comment]
我和你一样的问题，解决了？

**Comment by q83037265** [comment]
我也是这样。
每天凌晨1点多出这个问题，每次都要重启才能恢复。
现在 重新部署了。目前没有这个问题了。
