### ISSUE TITLE
运行报错，依赖都用一键脚本安装了

### ISSUE THREAD

**Issue by hotket** [whyour/qinglong#1357]
京喜财富岛热气球, 错误!
TypeError: Cannot read properties of undefined (reading 'NormShell')
    at /ql/scripts/he1pu_JDHelp_jd_cfd_loop.js:168:49
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/he1pu_JDHelp_jd_cfd_loop.js:435:4869)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by hotket** [comment]
> 京喜财富岛热气球, 错误! TypeError: Cannot read properties of undefined (reading 'NormShell') at /ql/scripts/he1pu_JDHelp_jd_cfd_loop.js:168:49 at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/he1pu_JDHelp_jd_cfd_loop.js:435:4869) at processTicksAndRejections (node:internal/process/task_queues:96:5)
