### ISSUE TITLE
青龙由2.10.10升级到最新版首页404

### ISSUE THREAD

**Issue by umbrellax** [whyour/qinglong#1405]
晚上升级了青龙，检测升级显示已是最新版本，但是自己青龙已经至少3，4个月没更新过了，就点了强制升级，然后升级完重启就废了。

日志如下：
=====> 开始检测
 ERR_PNPM_REGISTRIES_MISMATCH  This modules directory was created using the following registries configuration: {"default":"https://registry.npmjs.org/"}. The current configuration is {"default":"https://registry.npmmirror.com/"}. To recreate the modules directory using the new settings, run "pnpm install".
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

=====> 面板服务异常，重置基础环境

---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

检测到 /ql 的依赖包有变化，运行 npm install...

Lockfile is up-to-date, resolution step is skipped
Already up-to-date

 WARN  "prepare" script of "@" inside "/ql" is skipped as the working directory seems suspicious. To run this lifecycle script anyway, use "--unsafe-perm".
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

检测到 /ql/data/scripts 的依赖包有变化，运行 npm install...

Recreating /ql/data/scripts/node_modules
Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +212
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 212, reused 212, downloaded 0, added 212, done

---> 脚本依赖安装完成

=====> 检测nginx服务
   43 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
   44 root      0:00 nginx: worker process
   45 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2022-05-10T18:37:35:     '    at /ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/index.js:281:22',
2022-05-10T18:37:35:   [message]: 'EISDIR: illegal operation on a directory, read',
2022-05-10T18:37:35:   errno: -21,
2022-05-10T18:37:35:   syscall: 'read',
2022-05-10T18:37:35:   code: 'EISDIR'
2022-05-10T18:37:35: }
2022-05-10T18:37:37: error:   🔥 error: Error: EISDIR: illegal operation on a directory, read
2022-05-10T18:37:37:     at Object.readSync (fs.js:614:3)
2022-05-10T18:37:37:     at tryReadSync (fs.js:383:20)
2022-05-10T18:37:37:     at Object.readFileSync (fs.js:420:19)
2022-05-10T18:37:37:     at Object.getFileContentByName (/ql/back/config/util.ts:8:15)
2022-05-10T18:37:37:     at /ql/back/api/config.ts:48:21
2022-05-10T18:37:37:     at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)
2022-05-10T18:37:37:     at next (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:137:13)
2022-05-10T18:37:37:     at Route.dispatch (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:112:3)
2022-05-10T18:37:37:     at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)
2022-05-10T18:37:37:     at /ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/index.js:281:22 {
2022-05-10T18:37:37:   [stack]: 'Error: EISDIR: illegal operation on a directory, read\n' +
2022-05-10T18:37:37:     '    at Object.readSync (fs.js:614:3)\n' +
2022-05-10T18:37:37:     '    at tryReadSync (fs.js:383:20)\n' +
2022-05-10T18:37:37:     '    at Object.readFileSync (fs.js:420:19)\n' +
2022-05-10T18:37:37:     '    at Object.getFileContentByName (/ql/back/config/util.ts:8:15)\n' +
2022-05-10T18:37:37:     '    at /ql/back/api/config.ts:48:21\n' +
2022-05-10T18:37:37:     '    at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)\n' +
2022-05-10T18:37:37:     '    at next (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:137:13)\n' +
2022-05-10T18:37:37:     '    at Route.dispatch (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:112:3)\n' +
2022-05-10T18:37:37:     '    at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)\n' +
2022-05-10T18:37:37:     '    at /ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/index.js:281:22',
2022-05-10T18:37:37:   [message]: 'EISDIR: illegal operation on a directory, read',
2022-05-10T18:37:37:   errno: -21,
2022-05-10T18:37:37:   syscall: 'read',
2022-05-10T18:37:37:   code: 'EISDIR'
2022-05-10T18:37:37: }
2022-05-10T18:58:43: info:    task ksjsb0510.js pid: 9701 exit null signal SIGKILL
2022-05-10T18:58:43: info:    task ksjsb0510.js pid: 9701 closed null
2022-05-10T18:59:31: info:    task ksjsb0510.js pid: 9750 exit 0 signal null
2022-05-10T18:59:31: info:    task ksjsb0510.js pid: 9750 closed 0
2022-05-10T19:01:21: info:    task ksjsb0510.js pid: 10898 exit null signal SIGKILL
2022-05-10T19:01:21: info:    task ksjsb0510.js pid: 10898 closed null
2022-05-10T22:06:15: info:    task ksjsb0510.js pid: 16204 exit 0 signal null
2022-05-10T22:06:15: info:    task ksjsb0510.js pid: 16204 closed 0
2022-05-11T06:52:39: info:    task Oreomeow_checkinpanel_master/ck_pojie.py pid: 486 exit 0 signal null
2022-05-11T06:52:39: info:    task Oreomeow_checkinpanel_master/ck_pojie.py pid: 486 closed 0
2022-05-11T07:25:46: info:    task ksjsb0510.js pid: 2052 exit 0 signal null
2022-05-11T07:25:46: info:    task ksjsb0510.js pid: 2052 closed 0
2022-05-11T07:43:18: info:    task dailycheckin pid: 2196 exit 0 signal null
2022-05-11T07:43:18: info:    task dailycheckin pid: 2196 closed 0
2022-05-11T07:45:13: info:    task pip3 install dailycheckin --upgrade pid: 2245 exit 0 signal null
2022-05-11T07:45:13: info:    task pip3 install dailycheckin --upgrade pid: 2245 closed 0
2022-05-11T07:53:04: info:    task dailycheckin pid: 2331 exit 0 signal null
2022-05-11T07:53:04: info:    task dailycheckin pid: 2331 closed 0
2022-05-11T10:47:18: info:    task ksjsb0510.js pid: 8565 exit 0 signal null
2022-05-11T10:47:18: info:    task ksjsb0510.js pid: 8565 closed 0
2022-05-11T10:56:11: info:    task ksjsb0510.js pid: 8658 exit 0 signal null
2022-05-11T10:56:11: info:    task ksjsb0510.js pid: 8658 closed 0
2022-05-12T15:37:43: info:    task ksjsb0510.js pid: 7911 exit null signal SIGKILL
2022-05-12T15:37:43: info:    task ksjsb0510.js pid: 7911 closed null
2022-05-13T06:35:20: info:    task ksjsb0510.js pid: 4211 exit 0 signal null
2022-05-13T06:35:20: info:    task ksjsb0510.js pid: 4211 closed 0
2022-05-13T07:33:41: info:    task ksjsb_zz.js pid: 5961 exit 0 signal null
2022-05-13T07:33:41: info:    task ksjsb_zz.js pid: 5961 closed 0
2022-05-13T07:38:37: info:    task xiecoll_radish-script/lb_elm.js pid: 6039 exit 0 signal null
2022-05-13T07:38:37: info:    task xiecoll_radish-script/lb_elm.js pid: 6039 closed 0
2022-05-14T06:46:23: info:    task dailycheckin pid: 16670 exit 0 signal null
2022-05-14T06:46:23: info:    task dailycheckin pid: 16670 closed 0
2022-05-14T07:18:05: info:    task dailycheckin --include BILIBILI pid: 18359 exit 0 signal null
2022-05-14T07:18:05: info:    task dailycheckin --include BILIBILI pid: 18359 closed 0
2022-05-14T17:40:20: info:    task xiecoll_radish-script/lb_elm.js pid: 4027 exit 0 signal null
2022-05-14T17:40:20: info:    task xiecoll_radish-script/lb_elm.js pid: 4027 closed 0
2022-05-18T13:16:58: info:    task xiecoll_radish-script/lb_elm.js pid: 4780 exit 0 signal null
2022-05-18T13:16:58: info:    task xiecoll_radish-script/lb_elm.js pid: 4780 closed 0
2022-05-18T13:20:38: info:    task xiecoll_radish-script/lb_elm.js pid: 4881 exit null signal SIGKILL
2022-05-18T13:20:38: info:    task xiecoll_radish-script/lb_elm.js pid: 4881 closed null
2022-05-21T07:47:20: info:    task dailycheckin --include VQQ pid: 3469 exit 0 signal null
2022-05-21T07:47:20: info:    task dailycheckin --include VQQ pid: 3469 closed 0
2022-05-21T07:54:32: info:    task xiecoll_radish-script/lb_elm.js pid: 3552 exit 0 signal null
2022-05-21T07:54:32: info:    task xiecoll_radish-script/lb_elm.js pid: 3552 closed 0
2022-05-21T19:10:22: info:    task xiecoll_radish-script/lb_elm.js pid: 26283 exit 0 signal null
2022-05-21T19:10:22: info:    task xiecoll_radish-script/lb_elm.js pid: 26283 closed 0
2022-05-22T08:41:43: info:    task biliexp/BiliExp.py pid: 20561 exit 0 signal null
2022-05-22T08:41:43: info:    task biliexp/BiliExp.py pid: 20561 closed 0
2022-05-22T08:48:20: info:    task pip3 install dailycheckin --upgrade pid: 20686 exit 0 signal null
2022-05-22T08:48:20: info:    task pip3 install dailycheckin --upgrade pid: 20686 closed 0
2022-05-22T08:53:28: info:    task pip3 install dailycheckin --upgrade pid: 20813 exit 0 signal null
2022-05-22T08:53:28: info:    task pip3 install dailycheckin --upgrade pid: 20813 closed 0
2022-05-22T08:57:31: info:    task pip3 install dailycheckin --upgrade pid: 20896 exit 0 signal null
2022-05-22T08:57:31: info:    task pip3 install dailycheckin --upgrade pid: 20896 closed 0
2022-05-22T09:00:55: info:    task pip3 install dailycheckin --upgrade pid: 21035 exit 0 signal null
2022-05-22T09:00:55: info:    task pip3 install dailycheckin --upgrade pid: 21035 closed 0
2022-05-22T09:03:17: info:    task pip3 install dailycheckin --upgrade pid: 22276 exit 0 signal null
2022-05-22T09:03:17: info:    task pip3 install dailycheckin --upgrade pid: 22276 closed 0
2022-05-22T20:52:25: info:    ✌️ Server need close
2022-05-22T20:52:31: info:    ✌️ Init file down
2022-05-22T20:52:31: info:    ✌️ Sentry loaded
2022-05-22T20:52:33: info:    ✌️ DB loaded
2022-05-22T20:52:34: info:    ✌️ Dependency Injector loaded
2022-05-22T20:52:34: info:    ✌️ Express loaded
2022-05-22T20:52:40: info:    [创建interval任务]，任务ID: 59，任务名: 删除日志，执行命令: ql rmlog 3
2022-05-22T20:52:40: info:    ✌️ init data loaded
2022-05-22T20:52:40: info:    ✌️ link deps
2022-01-24T17:49:09:   errno: -2,
2022-01-24T17:49:09:   code: 'ENOENT',
2022-01-24T17:49:09:   syscall: 'rename',
2022-01-24T17:49:09:   path: '/ql/db/env.db~',
2022-01-24T17:49:09:   dest: '/ql/db/env.db'
2022-01-24T17:49:09: }
2022-01-24T17:49:09: Error: ENOENT: no such file or directory, rename '/ql/db/env.db~' -> '/ql/db/env.db'
2022-01-26T21:26:57: [Error: ENOENT: no such file or directory, open '/ql/db/dependence.db~'] {
2022-01-26T21:26:57:   errno: -2,
2022-01-26T21:26:57:   code: 'ENOENT',
2022-01-26T21:26:57:   syscall: 'open',
2022-01-26T21:26:57:   path: '/ql/db/dependence.db~'
2022-01-26T21:26:57: }
2022-01-26T21:26:57: Error: ENOENT: no such file or directory, open '/ql/db/dependence.db~'
2022-02-01T19:08:35: [Error: ENOENT: no such file or directory, rename '/ql/db/app.db~' -> '/ql/db/app.db'] {
2022-02-01T19:08:35:   errno: -2,
2022-02-01T19:08:35:   code: 'ENOENT',
2022-02-01T19:08:35:   syscall: 'rename',
2022-02-01T19:08:35:   path: '/ql/db/app.db~',
2022-02-01T19:08:35:   dest: '/ql/db/app.db'
2022-02-01T19:08:35: }
2022-02-01T19:08:35: Error: ENOENT: no such file or directory, rename '/ql/db/app.db~' -> '/ql/db/app.db'
2022-02-01T19:08:36: [Error: ENOENT: no such file or directory, rename '/ql/db/dependence.db~' -> '/ql/db/dependence.db'] {
2022-02-01T19:08:36:   errno: -2,
2022-02-01T19:08:36:   code: 'ENOENT',
2022-02-01T19:08:36:   syscall: 'rename',
2022-02-01T19:08:36:   path: '/ql/db/dependence.db~',
2022-02-01T19:08:36:   dest: '/ql/db/dependence.db'
2022-02-01T19:08:36: }
2022-02-01T19:08:36: Error: ENOENT: no such file or directory, rename '/ql/db/dependence.db~' -> '/ql/db/dependence.db'
2022-02-14T19:55:17: [Error: ENOENT: no such file or directory, rename '/ql/db/app.db~' -> '/ql/db/app.db'] {
2022-02-14T19:55:17:   errno: -2,
2022-02-14T19:55:17:   code: 'ENOENT',
2022-02-14T19:55:17:   syscall: 'rename',
2022-02-14T19:55:17:   path: '/ql/db/app.db~',
2022-02-14T19:55:17:   dest: '/ql/db/app.db'
2022-02-14T19:55:17: }
2022-02-14T19:55:17: Error: ENOENT: no such file or directory, rename '/ql/db/app.db~' -> '/ql/db/app.db'
2022-03-09T01:53:05: [Error: ENOENT: no such file or directory, rename '/ql/db/env.db~' -> '/ql/db/env.db'] {
2022-03-09T01:53:05:   errno: -2,
2022-03-09T01:53:05:   code: 'ENOENT',
2022-03-09T01:53:05:   syscall: 'rename',
2022-03-09T01:53:05:   path: '/ql/db/env.db~',
2022-03-09T01:53:05:   dest: '/ql/db/env.db'
2022-03-09T01:53:05: }
2022-03-09T01:53:06: Error: ENOENT: no such file or directory, rename '/ql/db/env.db~' -> '/ql/db/env.db'
2022-03-09T01:53:06: [Error: ENOENT: no such file or directory, rename '/ql/db/auth.db~' -> '/ql/db/auth.db'] {
2022-03-09T01:53:06:   errno: -2,
2022-03-09T01:53:06:   code: 'ENOENT',
2022-03-09T01:53:06:   syscall: 'rename',
2022-03-09T01:53:06:   path: '/ql/db/auth.db~',
2022-03-09T01:53:06:   dest: '/ql/db/auth.db'
2022-03-09T01:53:06: }
2022-03-09T01:53:06: Error: ENOENT: no such file or directory, rename '/ql/db/auth.db~' -> '/ql/db/auth.db'
2022-03-09T01:53:06: [Error: ENOENT: no such file or directory, rename '/ql/db/app.db~' -> '/ql/db/app.db'] {
2022-03-09T01:53:06:   errno: -2,
2022-03-09T01:53:06:   code: 'ENOENT',
2022-03-09T01:53:06:   syscall: 'rename',
2022-03-09T01:53:06:   path: '/ql/db/app.db~',
2022-03-09T01:53:06:   dest: '/ql/db/app.db'
2022-03-09T01:53:06: }
2022-03-09T01:53:06: Error: ENOENT: no such file or directory, rename '/ql/db/app.db~' -> '/ql/db/app.db'
2022-04-03T10:03:29: [Error: ENOENT: no such file or directory, rename '/ql/db/auth.db~' -> '/ql/db/auth.db'] {
2022-04-03T10:03:29:   errno: -2,
2022-04-03T10:03:29:   code: 'ENOENT',
2022-04-03T10:03:29:   syscall: 'rename',
2022-04-03T10:03:29:   path: '/ql/db/auth.db~',
2022-04-03T10:03:29:   dest: '/ql/db/auth.db'
2022-04-03T10:03:29: }
2022-04-03T10:03:29: Error: ENOENT: no such file or directory, rename '/ql/db/auth.db~' -> '/ql/db/auth.db'
2022-04-28T12:45:50: [Error: ENOENT: no such file or directory, open '/ql/db/crontab.db~'] {
2022-04-28T12:45:50:   errno: -2,
2022-04-28T12:45:50:   code: 'ENOENT',
2022-04-28T12:45:50:   syscall: 'open',
2022-04-28T12:45:50:   path: '/ql/db/crontab.db~'
2022-04-28T12:45:50: }
2022-04-28T12:45:50: Error: ENOENT: no such file or directory, open '/ql/db/crontab.db~'
2022-05-22T20:52:29: Error: ENOENT: no such file or directory, mkdir '/ql/data/config/'
2022-05-22T20:52:29:     at Object.mkdirSync (fs.js:1009:3)
2022-05-22T20:52:29:     at Object.exports.default (/back/loaders/initFile.ts:26:8)
2022-05-22T20:52:29:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-05-22T20:52:29:     at startServer (/back/app.ts:12:3) {
2022-05-22T20:52:29:   errno: -2,
2022-05-22T20:52:29:   syscall: 'mkdir',
2022-05-22T20:52:29:   code: 'ENOENT',
2022-05-22T20:52:29:   path: '/ql/data/config/'
2022-05-22T20:52:29: }
2022-05-22T20:52:40: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
2022-05-22T20:52:40:     at validatePort (internal/validators.js:217:11)
2022-05-22T20:52:40:     at Server.listen (net.js:1446:5)
2022-05-22T20:52:40:     at Function.listen (/ql/node_modules/.pnpm/registry.npmmirror.com+express@4.18.1/node_modules/express/lib/application.js:635:24)
2022-05-22T20:52:40:     at startServer (/back/app.ts:21:6) {
2022-05-22T20:52:40:   code: 'ERR_SOCKET_BAD_PORT'
2022-05-22T20:52:40: }
2022-05-22T20:52:40: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-05-22T20:52:40: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
2022-05-22T20:52:40:     at validatePort (internal/validators.js:217:11)
2022-05-22T20:52:40:     at Server.listen (net.js:1446:5)
2022-05-22T20:52:40:     at Function.listen (/ql/node_modules/.pnpm/registry.npmmirror.com+express@4.18.1/node_modules/express/lib/application.js:635:24)
2022-05-22T20:52:40:     at startServer (/back/app.ts:21:6)
=====> 检测后台
=====> 后台服务异常，重置基础环境并重启后台
---> 1. 开始检测配置文件
---> 配置文件检测完成
---> 2. 开始安装青龙依赖
检测到 /ql 的依赖包有变化，运行 npm install...
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
 WARN  "prepare" script of "@" inside "/ql" is skipped as the working directory seems suspicious. To run this lifecycle script anyway, use "--unsafe-perm".
---> 青龙依赖安装完成
---> 3. 开始安装脚本依赖
检测到 /ql/data/scripts 的依赖包有变化，运行 npm install...
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
---> 脚本依赖安装完成
=====> 检测结束

**Comment by cc9014** [comment]
这种大版本升级最好重新拉新版镜像。另外工作目录变化为了/ql/data目录，可能还需要自己手动移动下以前的文件到新目录。
建议新开个容器，待能成功运行后迁移以前容器的数据过来比较保险。

**Comment by cc9014** [comment]
2.12之前的版本，目录都散在/ql下面，新的统一迁移到/ql/data下面。所以你可以先新建个容器（重新取名），等能跑起来后，把原来ql目录下的文件夹（主要应该是config和db应该）都copy覆盖过去，理论上就和原来一模一样了。不过有些脚本可能路径会报错，到时候再修修就行了。
`  -v $PWD/ql/config:/ql/config \`
`  -v $PWD/ql/log:/ql/log \`
`  -v $PWD/ql/db:/ql/db \`
`  -v $PWD/ql/repo:/ql/repo \`
`  -v $PWD/ql/raw:/ql/raw \`
`  -v $PWD/ql/scripts:/ql/scripts \`

`  -v $PWD/ql:/ql/data \`
