### ISSUE TITLE
🔥 error: TypeError: Cannot read properties of undefined (reading 'lastIndexOf')

### ISSUE THREAD

**Issue by Checkra2n** [whyour/qinglong#1423]
2022-05-25T20:57:36: error:   🔥 error: TypeError: Cannot read properties of undefined (reading 'lastIndexOf')
2022-05-25T20:57:36:     at CronService.getKey (/ql/back/services/cron.ts:406:15)
2022-05-25T20:57:36:     at CronService.logs (/ql/back/services/cron.ts:378:24)
2022-05-25T20:57:36:     at /ql/back/api/cron.ts:348:22 {
2022-05-25T20:57:36:   [stack]: "TypeError: Cannot read properties of undefined (reading 'lastIndexOf')\n" +
2022-05-25T20:57:36:     '    at CronService.getKey (/ql/back/services/cron.ts:406:15)\n' +
2022-05-25T20:57:36:     '    at CronService.logs (/ql/back/services/cron.ts:378:24)\n' +
2022-05-25T20:57:36:     '    at /ql/back/api/cron.ts:348:22',
2022-05-25T20:57:36:   [message]: "Cannot read properties of undefined (reading 'lastIndexOf')"

本地软路由的系统，大佬这个怎么解决

**Comment by Checkra2n** [comment]
感谢大佬的建议，强制更新已解决
