### ISSUE TITLE
全部脚本无法运行

### ISSUE THREAD

**Issue by 2284787774** [whyour/qinglong#143]
开始执行...
Mon May 17 2021 20:52:45 GMT+0800 (中国标准时间)

🔔京东资产变动通知, 开始!

====================共4个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/5/17下午8:52:45=====================

(node:822) UnhandledPromiseRejectionWarning: Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/scripts/chinnkarahoi_jd_bean_change.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.initGotEnv (/ql/scripts/chinnkarahoi_jd_bean_change.js:372:3796)
    at Object.get (/ql/scripts/chinnkarahoi_jd_bean_change.js:372:4567)
    at /ql/scripts/chinnkarahoi_jd_bean_change.js:172:7
    at new Promise (<anonymous>)
    at TotalBean (/ql/scripts/chinnkarahoi_jd_bean_change.js:158:10)
    at /ql/scripts/chinnkarahoi_jd_bean_change.js:63:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:822) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:822) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

执行结束...

**Comment by whyour** [comment]
你重新安装下吧，按照频道通知来
