### ISSUE TITLE
新手求指路，脚本运行错误 Error: Cannot find module './jdCookie.js'  

### ISSUE THREAD

**Issue by toubiaodaili** [whyour/qinglong#148]
![photo_2021-05-18_23-53-22](https://user-images.githubusercontent.com/48340858/118683951-61969200-b834-11eb-97e8-20568568de8a.jpg)

都报这个错误，我的Cookie已经填了呀
Error: Cannot find module './jdCookie.js'  

开始执行...
Tue May 18 2021 23:55:25 GMT+0800 (中国标准时间)

🔔京享值PK, 开始!
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './jdCookie.js'
Require stack:
- /ql/scripts/monk-coder_adolf_pk.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ql/scripts/monk-coder_adolf_pk.js:20:35)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/monk-coder_adolf_pk.js' ]

**Comment by hcl821** [comment]
我也是这样的问题

**Comment by toubiaodaili** [comment]
> 我也是这样的问题

弄好了吗？  弄好了 教我一下

**Comment by hcl821** [comment]
没有安装几道都是这样的，不知道哪里除了问题

**Comment by toubiaodaili** [comment]
我在scripts文件夹  新建了一个 jdCookie.js文件

就提示我没有获取cookie ，是不是我填的cookie  没有跟这些关联起来？？？
开始执行...
Thu May 20 2021 10:35:27 GMT+0800 (中国标准时间)

🔔京喜工厂plus, 开始!

==============📣系统通知📣==============
京喜工厂plus
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/

🔔京喜工厂plus, 结束! 🕛 0.599 秒


执行结束...

**Comment by hcl821** [comment]
弄好了吗

**Comment by toubiaodaili** [comment]
> 弄好了吗

ql repo https://ghproxy.com/https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"
弄好了  问了大佬  运行这个

**Comment by 666668113** [comment]
运行之后还是这样 可能是我的问题 但是不知道这么解决-bash: ql: 未找到命令

**Comment by rzdbaba** [comment]
> 运行之后还是这样 可能是我的问题 但是不知道这么解决-bash: ql: 未找到命令

容器里面运行才行！
