### ISSUE TITLE
Bark_Push doesn't work with self-built Bark server

### ISSUE THREAD

**Issue by GraysonSmith** [whyour/qinglong#1732]
### Qinglong version

2.15.1

### Steps to reproduce

export BARK_PUSH="https://mybark.domain.name:port/abcdefg" as BARK_PUSH variable, then run a .js file, the running results couldn't be sent to the bark client.

### What is expected?

The bark client could receive the proper msg.

### What is actually happening?

Here is the error report:

RequestError: getaddrinfo ENOTFOUND mybark.domain.name
    at ClientRequest.<anonymous> (/ql/data/scripts/node_modules/.pnpm/got@11.8.5/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/ql/data/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
  code: 'ENOTFOUND',
  timings: {
    start: 1669982492926,
    socket: 1669982492927,
    lookup: 1669982492936,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1669982492937,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 9,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 11
    }
  }
}

### Any additional comments?

When I try to use Python (notify.py) to send msg, it worked fine. Cause I modified the notify.py file manually, writing the variable content into the file, not as a environment variable. So does it have relationship with that? (Mean that I need to write the variable manually into the SendNotify.js )

**Comment by whyour** [comment]
使用最新镜像，检查你的bark服务是否和青龙容器相通
