### ISSUE TITLE
在python脚本里使用selenium调用不了chromedriver

### ISSUE THREAD

**Issue by zzh151223** [whyour/qinglong#1777]
### Qinglong version

 v2.15.2

### Steps to reproduce

123

### What is expected?

解决

### What is actually happening?

调用chromedriver时python报错：

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 199, in _start_process

    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/ql/data/scripts/依赖工具/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 213, in _start_process

^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 546, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager'

python有几率调用不了chromedriver(文件已存在指定位置)，多运行几次可能会成功1次，No such file or directory: '/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager这个错误一直存在,我在物理路径上创建这些目录也不行

**Comment by hong0980** [comment]
`  service = webdriver.ChromeService(
      executable_path='/usr/bin/chromedriver'
  )`
需要指定路径
