### ISSUE TITLE
依赖安装问题，npm指令用不了 nodejs的依赖没法加

### ISSUE THREAD

**Issue by sanxianla** [whyour/qinglong#1803]
### Qinglong version

2.10.13

### Steps to reproduce

开始安装依赖 png-js，开始时间 2023/2/9 下午6:44:32

/bin/bash: npm: command not found

依赖安装失败，结束时间 2023/2/9 下午6:44:32，耗时 0.049 秒

### What is expected?

怎么能解决这个指令未找到问题

### What is actually happening?

添加依赖界面

**Comment by whyour** [comment]
@sanxianla 升级最新版

**Comment by sanxianla** [comment]
> 这个是今天重装docker之后从头拉的latest版的青龙面板，是换别的版本吗 我查了一下好像是我nodejs版本和npm版本不对应的原因 但是找不到合适的解决方案
root@aml-s812:~# node -v
v10.24.0
root@aml-s812:~# npm -v
ERROR: npm is known not to run on Node.js v10.24.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/
root@aml-s812:~# sudo apt install nodejs npm -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
npm is already the newest version (5.8.0+ds6-4+deb10u2).
nodejs is already the newest version (10.24.0~dfsg-1~deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@aml-s812:~# npm -v
ERROR: npm is known not to run on Node.js v10.24.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/

**Comment by sanxianla** [comment]
> @sanxianla 升级最新版

这个是今天重装docker之后从头拉的latest版的青龙面板，是换别的版本吗 我查了一下好像是我nodejs版本和npm版本不对应的原因 但是找不到合适的解决方案
root@aml-s812:# node -v
v10.24.0
root@aml-s812:# npm -v
ERROR: npm is known not to run on Node.js v10.24.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/
root@aml-s812:# sudo apt install nodejs npm -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
npm is already the newest version (5.8.0+ds6-4+deb10u2).
nodejs is already the newest version (10.24.0dfsg-1deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@aml-s812:# npm -v
ERROR: npm is known not to run on Node.js v10.24.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/

**Comment by whyour** [comment]
> > @sanxianla 升级最新版
> 
> 这个是今天重装docker之后从头拉的latest版的青龙面板，是换别的版本吗 我查了一下好像是我nodejs版本和npm版本不对应的原因 但是找不到合适的解决方案 root@aml-s812:# node -v v10.24.0 root@aml-s812:# npm -v ERROR: npm is known not to run on Node.js v10.24.0 You'll need to upgrade to a newer Node.js version in order to use this version of npm. You can find the latest version at https://nodejs.org/ root@aml-s812:# sudo apt install nodejs npm -y Reading package lists... Done Building dependency tree Reading state information... Done npm is already the newest version (5.8.0+ds6-4+deb10u2). nodejs is already the newest version (10.24.0dfsg-1deb10u2). 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded. root@aml-s812:# npm -v ERROR: npm is known not to run on Node.js v10.24.0 You'll need to upgrade to a newer Node.js version in order to use this version of npm. You can find the latest version at https://nodejs.org/

你这docker源有问题吧

**Comment by sanxianla** [comment]
用的应该是豆瓣源



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月9日(周四) 晚上7:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] 依赖安装问题，npm指令用不了 nodejs的依赖没法加 (Issue #1803)




   
@sanxianla 升级最新版
  
这个是今天重装docker之后从头拉的latest版的青龙面板，是换别的版本吗 我查了一下好像是我nodejs版本和npm版本不对应的原因 但是找不到合适的解决方案 ***@***.***:# node -v v10.24.0 ***@***.***:# npm -v ERROR: npm is known not to run on Node.js v10.24.0 You'll need to upgrade to a newer Node.js version in order to use this version of npm. You can find the latest version at https://nodejs.org/ ***@***.***:# sudo apt install nodejs npm -y Reading package lists... Done Building dependency tree Reading state information... Done npm is already the newest version (5.8.0+ds6-4+deb10u2). nodejs is already the newest version (10.24.0dfsg-1deb10u2). 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded. ***@***.***:# npm -v ERROR: npm is known not to run on Node.js v10.24.0 You'll need to upgrade to a newer Node.js version in order to use this version of npm. You can find the latest version at https://nodejs.org/
  
你这docker源有问题吧

**Comment by whyour** [comment]
@sanxianla 要先看镜像的创建时间是不是和 dockerhub 上的一致，不一致说明源有问题

**Comment by sanxianla** [comment]
> 



> @sanxianla 要先看镜像的创建时间是不是和 dockerhub 上的一致，不一致说明源有问题

`root@qinglong:/ql $ ql check
Error: Cannot find module 'reflect-metadata'
Require stack:
- /ql/back/token.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/usr/local/pnpm-global/5/node_modules/.pnpm/@cspotcode+source-map-support@0.7.0/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/back/token.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/usr/local/pnpm-global/5/node_modules/.pnpm/ts-node@10.4.0_typescript@4.5.4/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/pnpm-global/5/node_modules/.pnpm/ts-node@10.4.0_typescript@4.5.4/node_modules/ts-node/src/index.ts:1374:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/back/token.ts' ]
}

`
现在打开是pm2 logs panel
暂无日志
运行ql check报错提示这些之后就卡主不动 这是在自动安装依赖吗？

**Comment by whyour** [comment]
@sanxianla 最新镜像吗

**Comment by sanxianla** [comment]
是的 刚拉的latest镜像



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月9日(周四) 晚上9:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whyour/qinglong] 依赖安装问题，npm指令用不了 nodejs的依赖没法加 (Issue #1803)




 
@sanxianla 最新镜像吗

**Comment by whyour** [comment]
@sanxianla 拉latest也不一定是最新的，看你镜像创建时间是否一致。或者容器内 env 看青龙版本

**Comment by sanxianla** [comment]
看了一下创建时间 docker imagesREPOSITORY&nbsp; &nbsp; &nbsp; &nbsp; TAG&nbsp; &nbsp; &nbsp; &nbsp;IMAGE ID&nbsp; &nbsp; &nbsp; &nbsp;CREATED&nbsp; &nbsp; &nbsp; SIZE
whyour/qinglong&nbsp; &nbsp;latest&nbsp; &nbsp; 4dbbb89df314&nbsp; &nbsp;7 days ago&nbsp; &nbsp;316MB
&nbsp;在github上显示8days ago&nbsp; 这边刚拉的是7days ago应该差不多吧
我在重新装nodejs之后解决了npm不能用问题 但是重装青龙面板访问端口还是
pm2 logs panel
暂无日志

进入容器运行ql check是提示这个
***@***.***:~# docker exec -it qinglong bash
***@***.***:/ql $ ql check




#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbea09e8c
date: time ‘-4701852401471062016’ is out of range
date: time ‘-4693531297472053248’ is out of range
date: invalid date ‘’
date: invalid date ‘’
date: time ‘-4701993242038632448’ is out of range
date: invalid date ‘’
date: invalid date ‘’
/usr/local/bin/ql: line 498: - : syntax error: operand expected (error token is "- ")
***@***.***:/ql $&nbsp;



&nbsp;


散仙哟！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月9日(星期四) 晚上10:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 依赖安装问题，npm指令用不了 nodejs的依赖没法加 (Issue #1803)





 
@sanxianla 拉latest也不一定是最新的，看你镜像创建时间是否一致。或者容器内 env 看青龙版本

**Comment by whyour** [comment]
@sanxianla 新建的容器环境就有问题？

**Comment by sanxianla** [comment]
我觉得是因为我用的玩客云32位的问题 是不是比较新的版本都不支持32位了？
&nbsp;


散仙哟！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月9日(星期四) 晚上10:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 依赖安装问题，npm指令用不了 nodejs的依赖没法加 (Issue #1803)





 
@sanxianla 新建的容器环境就有问题？

**Comment by whyour** [comment]
@sanxianla 支持的，你用develop镜像试一下，过几天就是正式版了

**Comment by whyour** [comment]
@sanxianla https://t.me/jiao_long/362

**Comment by sanxianla** [comment]
我这边查看架构显示的是arm&nbsp;


散仙哟！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月9日(星期四) 晚上10:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whyour/qinglong] 依赖安装问题，npm指令用不了 nodejs的依赖没法加 (Issue #1803)





 
@sanxianla https://t.me/jiao_long/362

**Comment by whyour** [comment]
@sanxianla 捉你起来了吗，刚开始你执行 check 干啥

**Comment by whyour** [comment]
@sanxianla 面板起来了吗

**Comment by sanxianla** [comment]
> 

装好之后打开的样子就是pm2 logs panel
暂无日志这样
这是地址
d.justdns.tk:5700

**Comment by whyour** [comment]
@sanxianla 这是dev部署的？进容器看panel有日志吗

**Comment by sanxianla** [comment]
> 

docker拉的
docker run -dit \
  -v $PWD/ql/data:/ql/data \
  -p 5700:5700 \
  --name qinglong \
  --hostname qinglong \
  --restart unless-stopped \
  whyour/qinglong:develop

进入容器后怎么查看日志呢

**Comment by whyour** [comment]
@sanxianla pm2 logs panel

**Comment by sanxianla** [comment]
> @sanxianla pm2 logs panel

root@qinglong:/ql $ pm2 logs panel


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbe82b23c
Trace/breakpoint trap (core dumped)

**Comment by whyour** [comment]
@sanxianla 置顶的 issue 不就是你的问题？  https://github.com/whyour/qinglong/issues/897

**Comment by sanxianla** [comment]
> 

感谢感谢！！！！

**Comment by sanxianla** [comment]
> 

今天又遇到了一大堆无法理解的问题，刚开始是在拉库的时候无法拉库，之后稀里糊涂拉完就经常面板打不开，进行ql -l check的时候老是提示npm install失败，之后一直报错下面信息，module老是无法安装上
## 开始执行... 2023-02-10 10:56:08


🔔摇京豆, 开始!

====================共3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2/10/2023, 10:56:12=====================

faker 友情提示：您的脚本正常运行中，频道：https://t.me/scriptalking
node:internal/modules/cjs/loader:995
  const err = new Error(message);
              ^

Error: Cannot find module '@sindresorhus/is'
Require stack:
- /ql/data/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.5/node_modules/got/dist/source/create.js
- /ql/data/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.5/node_modules/got/dist/source/index.js
- /ql/data/scripts/shufflewzc_faker3_main/jd_club_lottery.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/ql/data/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.5/node_modules/got/dist/source/create.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/data/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.5/node_modules/got/dist/source/create.js',
    '/ql/data/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.5/node_modules/got/dist/source/index.js',
    '/ql/data/scripts/shufflewzc_faker3_main/jd_club_lottery.js'
  ]
}

Node.js v18.12.1


## 执行结束... 2023-02-10 10:56:12  耗时 4 秒

**Comment by whyour** [comment]
@sanxianla 脚本问题找脚本开发者

**Comment by sanxianla** [comment]
> 

是因为这一类的依赖安装问题 进入青龙内部运行npm install老是卡死

**Comment by whyour** [comment]
@sanxianla 依赖在依赖管理啊，谁让你进内部运行的

**Comment by sanxianla** [comment]
> 

依赖管理里面全是安装失败
开始安装依赖 @sindresorhus/is，开始时间 2023-02-10 11:01:45


依赖安装失败，结束时间 2023-02-10 11:01:45，耗时 0 秒

**Comment by whyour** [comment]
@sanxianla 排查网络问题，加上代理，不行强制更新

**Comment by sanxianla** [comment]
> @sanxianla 排查网络问题，加上代理，不行强制更新

强制更新是指的什么，依赖安装过程也可以加上代理吗，我之前修改了node源是淘宝源。（）

**Comment by whyour** [comment]
@sanxianla 配置里面不是有源的修改吗，系统设置-检查更新-强制更新
