### ISSUE TITLE
添加任务失败，修复报错。ql -l check

### ISSUE THREAD

**Issue by ZhiXuanWang** [whyour/qinglong#1834]
### Qinglong version

最新版

### Steps to reproduce

2023-03-04T11:42:15:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:15:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:15: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-03-04T11:42:15: TypeError: Cannot read properties of null (reading 'log_path')
2023-03-04T11:42:15:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:15:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:17: TypeError: Cannot read properties of null (reading 'log_path')
2023-03-04T11:42:17:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:17:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:17: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

### What is expected?

2023-03-04T11:42:15:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:15:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:15: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-03-04T11:42:15: TypeError: Cannot read properties of null (reading 'log_path')
2023-03-04T11:42:15:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:15:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:17: TypeError: Cannot read properties of null (reading 'log_path')
2023-03-04T11:42:17:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:17:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:17: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

### What is actually happening?

2023-03-04T11:42:15:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:15:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:15: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-03-04T11:42:15: TypeError: Cannot read properties of null (reading 'log_path')
2023-03-04T11:42:15:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:15:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:17: TypeError: Cannot read properties of null (reading 'log_path')
2023-03-04T11:42:17:     at Object.onLog (/ql/back/services/subscription.ts:266:59)
2023-03-04T11:42:17:     at Socket.<anonymous> (/ql/back/services/schedule.ts:62:11)
2023-03-04T11:42:17: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

**Comment by whyour** [comment]
日志太少了
