### ISSUE TITLE
notify.py脚本使用旧的SCU开头的key 推送ServerJ异常

### ISSUE THREAD

**Issue by HikerX** [whyour/qinglong#1857]
### Qinglong version

v2.15.10

### Steps to reproduce

1, 在config.sh 添加 PUSH_KEY=SCU开头的key，非 新版本 SCT开头的 key
2, 调用 send方法推送任意通知

### What is expected?

异常1
Exception in thread serverJ:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/HikerX_china_unicom_reward/notify.py", line 262, in serverJ
    if push_config.get("PUSH_KEY").index("SCT") != -1:
ValueError: substring not found

异常2
Exception in thread serverJ:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/HikerX_china_unicom_reward/notify.py", line 272, in serverJ
    print(f'serverJ 推送失败！错误码：{response["message"]}')
KeyError: 'message'

### What is actually happening?

https://github.com/whyour/qinglong/blob/develop/sample/notify.py
异常1
272行 
    if push_config.get("PUSH_KEY").index("SCT") != -1:
index 方法，如果没找到 SCT，会直接抛异常，而不是 返回-1，建议 用 find 方法代替

异常2
275 行
        url = f'https://sc.ftqq.com/${push_config.get("PUSH_KEY")}.send'
 python 中格式化字符中读取变量 {} 外不需要 $, 不然会直接当作多余字符添加进去，导致 token 错误
 {"errno":1024,"errmsg":"bad pushtoken"}

### Any additional comments?

ServerJ (ServerChan) 之前使用 SCU 开头的 token
后来 使用了 SCT 开头的 token
目前， SCU 开头的 token  仍能使用
这两个异常都是 js 中的”合理“写法， python 中则异常

**Comment by whyour** [comment]
👍   下个版本修复
