### ISSUE TITLE
 Can't start normally after update

### ISSUE THREAD

**Issue by mayjack0312** [whyour/qinglong#1988]
### Qinglong version

v2.15.16

### Steps to reproduce

更新方法:
-> 面板更新 系统设置 -> 其他设置 -> 检查更新
-> 容器内更新 执行 ql -l update
-> 宿主机更新 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>

### What is expected?

![image](https://github.com/whyour/qinglong/assets/102800660/ba4080b7-6603-4e8f-8ba8-1c6018e515d1)

### What is actually happening?

```log
root@QL:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-06-24T13:08:37: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-06-24T13:08:37: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-06-24T13:08:37: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-06-24T13:08:37: PM2 log: Script /ql/static/build/schedule/index.js had too many unstable restarts (10). Stopped. "errored"
PM2        | 2023-06-24T13:08:44: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:44: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:44: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:45: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:45: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:45: PM2 log: App [panel:2] online
PM2        | 2023-06-24T13:08:45: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:46: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:46: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:47: PM2 log: App [schedule:0] online
PM2        | 2023-06-24T13:08:47: PM2 log: App [schedule:0] online

/root/.pm2/logs/schedule-out.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-06-24T13:08:35: info:    ✌️ Sentry loaded
1|public   | 2023-06-24T13:08:35: info:    ✌️ DB loaded
1|public   | 2023-06-24T13:08:35: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-06-24T13:08:36: info:    ✌️ DB loaded
2|panel    | 2023-06-24T13:08:36: info:    ✌️ Init file down
2|panel    | 2023-06-24T13:08:36: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-06-24T13:08:37: - /ql/static/build/api/user.js
2|panel    | 2023-06-24T13:08:37: - /ql/static/build/api/index.js
2|panel    | 2023-06-24T13:08:37: - /ql/static/build/loaders/express.js
2|panel    | 2023-06-24T13:08:37: - /ql/static/build/loaders/app.js
2|panel    | 2023-06-24T13:08:37: - /ql/static/build/app.js
2|panel    | 2023-06-24T13:08:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2|panel    | 2023-06-24T13:08:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-06-24T13:08:37:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-06-24T13:08:37:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2|panel    | 2023-06-24T13:08:37:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2|panel    | 2023-06-24T13:08:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2|panel    | 2023-06-24T13:08:37:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2|panel    | 2023-06-24T13:08:37:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2|panel    | 2023-06-24T13:08:37:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2|panel    | 2023-06-24T13:08:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-06-24T13:08:37:     at require (node:internal/modules/cjs/helpers:110:18)
0|schedule | 2023-06-24T13:08:37:     at Object.<anonymous> (/ql/back/shared/runCron.ts:1:1)
0|schedule | 2023-06-24T13:08:37:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|schedule | 2023-06-24T13:08:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|schedule | 2023-06-24T13:08:37:     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|schedule | 2023-06-24T13:08:37:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
0|schedule | 2023-06-24T13:08:37:     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|schedule | 2023-06-24T13:08:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
0|schedule | 2023-06-24T13:08:37:   code: 'MODULE_NOT_FOUND',
0|schedule | 2023-06-24T13:08:37:   requireStack: [
0|schedule | 2023-06-24T13:08:37:     '/ql/static/build/shared/runCron.js',
0|schedule | 2023-06-24T13:08:37:     '/ql/static/build/schedule/addCron.js',
0|schedule | 2023-06-24T13:08:37:     '/ql/static/build/schedule/index.js'
0|schedule | 2023-06-24T13:08:37:   ]
0|schedule | 2023-06-24T13:08:37: }
```

**Comment by whyour** [comment]
pm2 delete all && pm2 start ecosystem.config.js

**Comment by whyour** [comment]
Restart the container with the latest image. Before that, you need to ensure that there is mapping /ql/data directory data

**Comment by mayjack0312** [comment]
> Restart the container with the latest image. Before that, you need to ensure that there is mapping /ql/data directory data

Ok, but I don't know why. After a period of time, try again and find that this inexplicable is normal. thanks again.

**Comment by whyour** [comment]
> > Restart the container with the latest image. Before that, you need to ensure that there is mapping /ql/data directory data
> 
> Ok, but I don't know why. After a period of time, try again and find that this inexplicable is normal. thanks again.

This problem is due to the schedule service not starting properly, the error above looks like a missing dependency, if you are using docker, we recommend using `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <container name>` update,  if you use in-panel updates, you may have this problem
