### ISSUE TITLE
ql

### ISSUE THREAD

**Issue by YZGI** [whyour/qinglong#1992]
### Qinglong version

2.15.15

### Steps to reproduce

执行 ql update 后打不开面板

### What is expected?

怎么在不丢失数据的情况下恢复面板

### What is actually happening?

进不去面板

### System Info

```shell
root@qinglong:/ql $ ql -l update
/ql/data/config/config.sh: line 165: unexpected EOF while looking for matching `"'
## 开始执行... 2023-06-25 09:28:53

使用 gitee 源更新...

开始更新仓库：/ql
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 64 (delta 53), reused 24 (delta 22), pack-reused 0
Unpacking objects: 100% (64/64), 40.89 KiB | 1.63 MiB/s, done.
From https://gitee.com/whyour/qinglong
 * branch            master     -> FETCH_HEAD

更新青龙源文件成功...

开始更新仓库：/ql/data/repo/static
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://gitee.com/whyour/qinglong-static
 * branch            master     -> FETCH_HEAD

更新青龙静态资源成功...

重启面板中...
[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [public](1) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [schedule](0) ✓
[PM2] [panel](2) ✓
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 2  │ panel              │ fork     │ 1    │ online    │ 0%       │ 81.1mb   │
│ 1  │ public             │ fork     │ 1    │ online    │ 2.2%     │ 79.2mb   │
│ 0  │ schedule           │ fork     │ 19   │ errored   │ 0%       │ 0b       │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘

## 执行结束... 2023-06-25 09:29:17 耗时 24 秒　　　　　
root@qinglong:/ql $ ql check
/ql/data/config/config.sh: line 165: unexpected EOF while looking for matching `"'
## 开始执行... 2023-06-25 09:29:28

=====> 开始检测

changed 1 package in 2s
检测到旧的db目录，拷贝到data目录...


检测到旧的scripts目录，拷贝到data目录...


检测到旧的log目录，拷贝到data目录...


检测到旧的config目录，拷贝到data目录...


OK: 556 MiB in 198 packages
 ERR_PNPM_REGISTRIES_MISMATCH  This modules directory was created using the following registries configuration: {"default":"https://registry.npmmirror.com/"}. The current configuration is {"default":"https://registry.npm.taobao.org/"}. To recreate the modules directory using the new settings, run "pnpm install -g".
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...


devDependencies: skipped


> @ postinstall /ql
> max setup 2>/dev/null || true

Done in 1.6s
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

安装 /ql/data/scripts 依赖包...


devDependencies: skipped

Done in 784ms
---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="https://qn.whyour.cn/favicon.svg">
<link rel="stylesheet" href="./umi.8a0eaca6.css">
<script src="./api/env.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>
<script src="./umi.51065785.js"></script>

</body></html>

=====> 面板服务启动正常

=====> 检测nginx服务
   82 nginx: master process nginx -c /etc/nginx/nginx.conf
  402 nginx: worker process
  403 nginx: worker process
  404 nginx: worker process
  405 nginx: worker process

=====> nginx服务正常

---> pm2日志
2023-06-25T09:29:07: info:    ✌️ DB loaded
2023-06-25T09:29:07: info:    ✌️ Init file down
2023-06-25T09:29:07: info:    ✌️ Sentry loaded
2023-06-25T09:29:08: Error: Cannot find module 'p-limit'
2023-06-25T09:29:08: Require stack:
2023-06-25T09:29:08: - /ql/static/build/shared/pLimit.js
2023-06-25T09:29:08: - /ql/static/build/services/schedule.js
2023-06-25T09:29:08: - /ql/static/build/services/user.js
2023-06-25T09:29:08: - /ql/static/build/api/user.js
2023-06-25T09:29:08: - /ql/static/build/api/index.js
2023-06-25T09:29:08: - /ql/static/build/loaders/express.js
2023-06-25T09:29:08: - /ql/static/build/loaders/app.js
2023-06-25T09:29:08: - /ql/static/build/app.js
2023-06-25T09:29:08:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-06-25T09:29:08:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-06-25T09:29:08:     at require (node:internal/modules/cjs/helpers:110:18)
2023-06-25T09:29:08:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2023-06-25T09:29:08:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-06-25T09:29:08:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-06-25T09:29:08:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-06-25T09:29:08:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-06-25T09:29:08:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-06-25T09:29:08:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-06-25T09:29:08:   code: 'MODULE_NOT_FOUND',
2023-06-25T09:29:08:   requireStack: [
2023-06-25T09:29:08:     '/ql/static/build/shared/pLimit.js',
2023-06-25T09:29:08:     '/ql/static/build/services/schedule.js',
2023-06-25T09:29:08:     '/ql/static/build/services/user.js',
2023-06-25T09:29:08:     '/ql/static/build/api/user.js',
2023-06-25T09:29:08:     '/ql/static/build/api/index.js',
2023-06-25T09:29:08:     '/ql/static/build/loaders/express.js',
2023-06-25T09:29:08:     '/ql/static/build/loaders/app.js',
2023-06-25T09:29:08:     '/ql/static/build/app.js'
2023-06-25T09:29:08:   ]
2023-06-25T09:29:08: }
2023-06-25T09:29:08: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-06-25T09:29:08: Error: Cannot find module 'p-limit'
2023-06-25T09:29:08: Require stack:
2023-06-25T09:29:08: - /ql/static/build/shared/pLimit.js
2023-06-25T09:29:08: - /ql/static/build/services/schedule.js
2023-06-25T09:29:08: - /ql/static/build/services/user.js
2023-06-25T09:29:08: - /ql/static/build/api/user.js
2023-06-25T09:29:08: - /ql/static/build/api/index.js
2023-06-25T09:29:08: - /ql/static/build/loaders/express.js
2023-06-25T09:29:08: - /ql/static/build/loaders/app.js
2023-06-25T09:29:08: - /ql/static/build/app.js
2023-06-25T09:29:08:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-06-25T09:29:08:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-06-25T09:29:08:     at require (node:internal/modules/cjs/helpers:110:18)
2023-06-25T09:29:08:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2023-06-25T09:29:08:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-06-25T09:29:08:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-06-25T09:29:08:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-06-25T09:29:08:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-06-25T09:29:08:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-06-25T09:29:08:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

=====> 检测后台



[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [public](1) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [schedule](0) ✓
[PM2] [panel](2) ✓
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 815      │ 10s    │ 2    │ online    │ 0%       │ 105.3mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 756      │ 11s    │ 2    │ online    │ 2%       │ 78.9mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 0        │ 0      │ 28   │ errored   │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

=====> 检测结束


## 执行结束... 2023-06-25 09:29:47 耗时 19 秒　　　　　
root@qinglong:/ql $ docker pull whyour/qinglong:2
/bin/sh: docker: Permission denied
root@qinglong:/ql $ docker exec -it qinglong ql update
/bin/sh: docker: Permission denied
root@qinglong:/ql $ ql check
/ql/data/config/config.sh: line 165: unexpected EOF while looking for matching `"'
## 开始执行... 2023-06-25 09:42:57

=====> 开始检测

changed 1 package in 2s
检测到旧的db目录，拷贝到data目录...


检测到旧的scripts目录，拷贝到data目录...


检测到旧的log目录，拷贝到data目录...


检测到旧的config目录，拷贝到data目录...


OK: 556 MiB in 198 packages
 ERR_PNPM_REGISTRIES_MISMATCH  This modules directory was created using the following registries configuration: {"default":"https://registry.npmmirror.com/"}. The current configuration is {"default":"https://registry.npm.taobao.org/"}. To recreate the modules directory using the new settings, run "pnpm install -g".
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...


devDependencies: skipped


> @ postinstall /ql
> max setup 2>/dev/null || true

Done in 1.3s
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

安装 /ql/data/scripts 依赖包...


devDependencies: skipped

Done in 830ms
---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="https://qn.whyour.cn/favicon.svg">
<link rel="stylesheet" href="./umi.8a0eaca6.css">
<script src="./api/env.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>
<script src="./umi.51065785.js"></script>

</body></html>

=====> 面板服务启动正常

=====> 检测nginx服务
   82 nginx: master process nginx -c /etc/nginx/nginx.conf
 2035 nginx: worker process
 2036 nginx: worker process
 2037 nginx: worker process
 2039 nginx: worker process

=====> nginx服务正常

---> pm2日志
2023-06-25T09:36:27: info:    ✌️ DB loaded
2023-06-25T09:36:27: info:    ✌️ Init file down
2023-06-25T09:36:27: info:    ✌️ Sentry loaded
2023-06-25T09:36:28: Error: Cannot find module 'p-limit'
2023-06-25T09:36:28: Require stack:
2023-06-25T09:36:28: - /ql/static/build/shared/pLimit.js
2023-06-25T09:36:28: - /ql/static/build/services/schedule.js
2023-06-25T09:36:28: - /ql/static/build/services/user.js
2023-06-25T09:36:28: - /ql/static/build/api/user.js
2023-06-25T09:36:28: - /ql/static/build/api/index.js
2023-06-25T09:36:28: - /ql/static/build/loaders/express.js
2023-06-25T09:36:28: - /ql/static/build/loaders/app.js
2023-06-25T09:36:28: - /ql/static/build/app.js
2023-06-25T09:36:28:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-06-25T09:36:28:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-06-25T09:36:28:     at require (node:internal/modules/cjs/helpers:110:18)
2023-06-25T09:36:28:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2023-06-25T09:36:28:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-06-25T09:36:28:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-06-25T09:36:28:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-06-25T09:36:28:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-06-25T09:36:28:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-06-25T09:36:28:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-06-25T09:36:28:   code: 'MODULE_NOT_FOUND',
2023-06-25T09:36:28:   requireStack: [
2023-06-25T09:36:28:     '/ql/static/build/shared/pLimit.js',
2023-06-25T09:36:28:     '/ql/static/build/services/schedule.js',
2023-06-25T09:36:28:     '/ql/static/build/services/user.js',
2023-06-25T09:36:28:     '/ql/static/build/api/user.js',
2023-06-25T09:36:28:     '/ql/static/build/api/index.js',
2023-06-25T09:36:28:     '/ql/static/build/loaders/express.js',
2023-06-25T09:36:28:     '/ql/static/build/loaders/app.js',
2023-06-25T09:36:28:     '/ql/static/build/app.js'
2023-06-25T09:36:28:   ]
2023-06-25T09:36:28: }
2023-06-25T09:36:28: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-06-25T09:36:28: Error: Cannot find module 'p-limit'
2023-06-25T09:36:28: Require stack:
2023-06-25T09:36:28: - /ql/static/build/shared/pLimit.js
2023-06-25T09:36:28: - /ql/static/build/services/schedule.js
2023-06-25T09:36:28: - /ql/static/build/services/user.js
2023-06-25T09:36:28: - /ql/static/build/api/user.js
2023-06-25T09:36:28: - /ql/static/build/api/index.js
2023-06-25T09:36:28: - /ql/static/build/loaders/express.js
2023-06-25T09:36:28: - /ql/static/build/loaders/app.js
2023-06-25T09:36:28: - /ql/static/build/app.js
2023-06-25T09:36:28:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-06-25T09:36:28:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-06-25T09:36:28:     at require (node:internal/modules/cjs/helpers:110:18)
2023-06-25T09:36:28:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2023-06-25T09:36:28:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-06-25T09:36:28:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-06-25T09:36:28:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-06-25T09:36:28:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-06-25T09:36:28:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-06-25T09:36:28:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

=====> 检测后台



[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [public](1) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [schedule](0) ✓
[PM2] [panel](2) ✓
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 2952     │ 10s    │ 5    │ online    │ 0%       │ 105.6mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 2889     │ 11s    │ 5    │ online    │ 0.9%     │ 99.5mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 0        │ 0      │ 55   │ errored   │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

=====> 检测结束


## 执行结束... 2023-06-25 09:43:15 耗时 18 秒　　　　　
root@qinglong:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-06-25T09:43:06: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-06-25T09:43:06: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-06-25T09:43:06: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-06-25T09:43:06: PM2 log: Script /ql/static/build/schedule/index.js had too many unstable restarts (10). Stopped. "errored"
PM2        | 2023-06-25T09:43:13: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:14: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:14: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:14: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:15: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:15: PM2 log: App [panel:2] online
PM2        | 2023-06-25T09:43:15: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:15: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:15: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:16: PM2 log: App [schedule:0] online
PM2        | 2023-06-25T09:43:16: PM2 log: App [schedule:0] online

/root/.pm2/logs/schedule-out.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-06-25T09:43:04: info:    ✌️ Sentry loaded
1|public   | 2023-06-25T09:43:05: info:    ✌️ DB loaded
1|public   | 2023-06-25T09:43:05: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-06-25T09:43:06: info:    ✌️ DB loaded
2|panel    | 2023-06-25T09:43:06: info:    ✌️ Init file down
2|panel    | 2023-06-25T09:43:06: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-06-25T09:43:06: - /ql/static/build/api/user.js
2|panel    | 2023-06-25T09:43:06: - /ql/static/build/api/index.js
2|panel    | 2023-06-25T09:43:06: - /ql/static/build/loaders/express.js
2|panel    | 2023-06-25T09:43:06: - /ql/static/build/loaders/app.js
2|panel    | 2023-06-25T09:43:06: - /ql/static/build/app.js
2|panel    | 2023-06-25T09:43:06:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2|panel    | 2023-06-25T09:43:06:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-06-25T09:43:06:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-06-25T09:43:06:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2|panel    | 2023-06-25T09:43:06:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2|panel    | 2023-06-25T09:43:06:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2|panel    | 2023-06-25T09:43:06:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2|panel    | 2023-06-25T09:43:06:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2|panel    | 2023-06-25T09:43:06:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2|panel    | 2023-06-25T09:43:06:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-06-25T09:43:06:     at require (node:internal/modules/cjs/helpers:110:18)
0|schedule | 2023-06-25T09:43:06:     at Object.<anonymous> (/ql/back/shared/runCron.ts:1:1)
0|schedule | 2023-06-25T09:43:06:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|schedule | 2023-06-25T09:43:06:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|schedule | 2023-06-25T09:43:06:     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|schedule | 2023-06-25T09:43:06:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
0|schedule | 2023-06-25T09:43:06:     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|schedule | 2023-06-25T09:43:06:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
0|schedule | 2023-06-25T09:43:06:   code: 'MODULE_NOT_FOUND',
0|schedule | 2023-06-25T09:43:06:   requireStack: [
0|schedule | 2023-06-25T09:43:06:     '/ql/static/build/shared/runCron.js',
0|schedule | 2023-06-25T09:43:06:     '/ql/static/build/schedule/addCron.js',
0|schedule | 2023-06-25T09:43:06:     '/ql/static/build/schedule/index.js'
0|schedule | 2023-06-25T09:43:06:   ]
0|schedule | 2023-06-25T09:43:06: }
```

**Comment by MaydayV** [comment]
我也想问怎么在不丢失数据的前提下重装，找到办法踢我一下

**Comment by MaydayV** [comment]
开始更新仓库：/ql
remote: Enumerating objects: 290, done.
remote: Counting objects: 100% (182/182), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 76 (delta 62), reused 23 (delta 19), pack-reused 0
Unpacking objects: 100% (76/76), 43.19 KiB | 455.00 KiB/s, done.
From https://gitee.com/whyour/qinglong
 * branch            master     -> FETCH_HEAD

更新青龙源文件成功...

开始更新仓库：/ql/data/repo/static
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://gitee.com/whyour/qinglong-static
 * branch            master     -> FETCH_HEAD

更新青龙静态资源成功...

重启面板中...
[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [public](1) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [schedule](0) ✓
[PM2] [panel](2) ✓
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 458      │ 3s     │ 1    │ online    │ 0%       │ 116.8mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 400      │ 5s     │ 1    │ online    │ 0%       │ 100.7mb  │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 519      │ 0      │ 20   │ launching │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

**Comment by whyour** [comment]
docker 拷贝容器内 /ql/data 目录，然后删除容器，更新镜像，重新运行容器。或者再运行容器时增加映射目录，参考项目 readme
