### ISSUE TITLE
lxk的京喜sign有问题

### ISSUE THREAD

**Issue by lyiangsh** [whyour/qinglong#203]
TypeError: data.data.tasks is not iterable
at /jd/scripts/jx_sign.js:121:38
at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jx_sign.js:315:4869)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
任务完成失败，错误信息not sign
目前就只有这个脚本这样 好多人也是这种情况

**Comment by kuilei0926** [comment]
那就跟lxk反馈去
