### ISSUE TITLE
更新最新版后无法启动面板

### ISSUE THREAD

**Issue by Eternityioi** [whyour/qinglong#2030]
### Qinglong version

unknow

### Steps to reproduce

更新最新版后无法启动面板

### What is expected?

面板正常启动

### What is actually happening?

面板无法启动

### System Info

```shell
root@qinglong:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-07-22T18:24:42: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-07-22T18:24:42: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-07-22T18:24:43: PM2 log: App [schedule:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-07-22T18:24:43: PM2 log: Script /ql/static/build/schedule/index.js had too many unstable restarts (10). Stopped. "errored"
PM2        | 2023-07-22T18:24:49: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:50: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:50: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:50: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:51: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:51: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:51: PM2 log: App [panel:2] online
PM2        | 2023-07-22T18:24:51: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:52: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:52: PM2 log: App [schedule:0] online
PM2        | 2023-07-22T18:24:52: PM2 log: App [schedule:0] online

/root/.pm2/logs/schedule-out.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-07-22T18:24:40: info:    ✌️ Sentry loaded
1|public   | 2023-07-22T18:24:41: info:    ✌️ DB loaded
1|public   | 2023-07-22T18:24:41: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-07-22T18:24:42: info:    ✌️ DB loaded
2|panel    | 2023-07-22T18:24:42: info:    ✌️ Init file down
2|panel    | 2023-07-22T18:24:42: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-07-22T18:24:42: - /ql/static/build/api/user.js
2|panel    | 2023-07-22T18:24:42: - /ql/static/build/api/index.js
2|panel    | 2023-07-22T18:24:42: - /ql/static/build/loaders/express.js
2|panel    | 2023-07-22T18:24:42: - /ql/static/build/loaders/app.js
2|panel    | 2023-07-22T18:24:42: - /ql/static/build/app.js
2|panel    | 2023-07-22T18:24:42:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2|panel    | 2023-07-22T18:24:42:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-07-22T18:24:42:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-07-22T18:24:42:     at Object.<anonymous> (/ql/back/shared/pLimit.ts:1:1)
2|panel    | 2023-07-22T18:24:42:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2|panel    | 2023-07-22T18:24:42:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2|panel    | 2023-07-22T18:24:42:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2|panel    | 2023-07-22T18:24:42:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2|panel    | 2023-07-22T18:24:42:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2|panel    | 2023-07-22T18:24:42:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

/root/.pm2/logs/schedule-error.log last 15 lines:
0|schedule | 2023-07-22T18:24:43:     at require (node:internal/modules/cjs/helpers:110:18)
0|schedule | 2023-07-22T18:24:43:     at Object.<anonymous> (/ql/back/shared/runCron.ts:1:1)
0|schedule | 2023-07-22T18:24:43:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
0|schedule | 2023-07-22T18:24:43:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
0|schedule | 2023-07-22T18:24:43:     at Module.load (node:internal/modules/cjs/loader:1117:32)
0|schedule | 2023-07-22T18:24:43:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
0|schedule | 2023-07-22T18:24:43:     at Module.require (node:internal/modules/cjs/loader:1141:19)
0|schedule | 2023-07-22T18:24:43:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
0|schedule | 2023-07-22T18:24:43:   code: 'MODULE_NOT_FOUND',
0|schedule | 2023-07-22T18:24:43:   requireStack: [
0|schedule | 2023-07-22T18:24:43:     '/ql/static/build/shared/runCron.js',
0|schedule | 2023-07-22T18:24:43:     '/ql/static/build/schedule/addCron.js',
0|schedule | 2023-07-22T18:24:43:     '/ql/static/build/schedule/index.js'
0|schedule | 2023-07-22T18:24:43:   ]
0|schedule | 2023-07-22T18:24:43: }
```

**Comment by HelloKitty2012** [comment]
我刚更新完，面板也打不开了

**Comment by angle111** [comment]
同样打不开502错误

**Comment by whyour** [comment]
1. 首先更新镜像，确保更新到了最新版镜像
2. 确保原来映射了 data 目录
3. 使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
