### ISSUE TITLE
升级后无法进入面板提示服务启动超时

### ISSUE THREAD

**Issue by dalant2019** [whyour/qinglong#2036]
### Qinglong version

2.15.9

### Steps to reproduce

在青龙的面板设置页面点升级版本并重启服务以后，无法进入面板并提示：服务启动超时

按照提示页面的修复方法但仍然无法解决
1. 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
2. 容器内执行 ql -l check、ql -l update

### What is expected?

希望修复这个问题

### What is actually happening?

![ql check](https://github.com/whyour/qinglong/assets/59816559/61f08753-8dc5-4bad-9295-ec8803ad47ec)
![ql update](https://github.com/whyour/qinglong/assets/59816559/5102c593-fa2b-4c9c-b21b-20746e12477f)

### System Info

```shell
服务启动超时
请先按如下方式修复：
1. 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
2. 容器内执行 ql -l check、ql -l update
3. 如果无法解决，容器内执行 pm2 logs，拷贝执行结果[提交 issue](https://github.com/whyour/qinglong/issues/new?assignees=&labels=&template=bug_report.yml)
No connection established

null
2023-07-25T21:01:24: Error: Cannot find module 'tar'
2023-07-25T21:01:24: Require stack:
2023-07-25T21:01:24: - /ql/static/build/services/system.js
2023-07-25T21:01:24: - /ql/static/build/api/system.js
2023-07-25T21:01:24: - /ql/static/build/api/index.js
2023-07-25T21:01:24: - /ql/static/build/loaders/express.js
2023-07-25T21:01:24: - /ql/static/build/loaders/app.js
2023-07-25T21:01:24: - /ql/static/build/app.js
2023-07-25T21:01:24: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-07-25T21:01:24: at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-07-25T21:01:24: at require (node:internal/modules/cjs/helpers:110:18)
2023-07-25T21:01:24: at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2023-07-25T21:01:24: at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-07-25T21:01:24: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-07-25T21:01:24: at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-07-25T21:01:24: at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-07-25T21:01:24: at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-07-25T21:01:24: at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-07-25T21:01:24: code: 'MODULE_NOT_FOUND',
2023-07-25T21:01:24: requireStack: [
2023-07-25T21:01:24: '/ql/static/build/services/system.js',
2023-07-25T21:01:24: '/ql/static/build/api/system.js',
2023-07-25T21:01:24: '/ql/static/build/api/index.js',
2023-07-25T21:01:24: '/ql/static/build/loaders/express.js',
2023-07-25T21:01:24: '/ql/static/build/loaders/app.js',
2023-07-25T21:01:24: '/ql/static/build/app.js'
2023-07-25T21:01:24: ]
2023-07-25T21:01:24: }
2023-07-25T21:01:24: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-07-25T21:01:24: Error: Cannot find module 'tar'
2023-07-25T21:01:24: Require stack:
2023-07-25T21:01:24: - /ql/static/build/services/system.js
2023-07-25T21:01:24: - /ql/static/build/api/system.js
2023-07-25T21:01:24: - /ql/static/build/api/index.js
2023-07-25T21:01:24: - /ql/static/build/loaders/express.js
2023-07-25T21:01:24: - /ql/static/build/loaders/app.js
2023-07-25T21:01:24: - /ql/static/build/app.js
2023-07-25T21:01:24: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-07-25T21:01:24: at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-07-25T21:01:24: at require (node:internal/modules/cjs/helpers:110:18)
2023-07-25T21:01:24: at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2023-07-25T21:01:24: at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-07-25T21:01:24: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-07-25T21:01:24: at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-07-25T21:01:24: at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-07-25T21:01:24: at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-07-25T21:01:24: at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

{"code":7,"killed":false,"signal":null,"cmd":"curl -s http://localhost:5600/api/system"}
```

**Comment by whyour** [comment]
使用宿主机方式更新下

1. 首先更新镜像，确保更新到了最新版镜像
2. 确保原来映射了 data 目录
3. 使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
