### ISSUE TITLE
升级失败 ql check/update未能解决

### ISSUE THREAD

**Issue by niyueyeee** [whyour/qinglong#2040]
### Qinglong version

root@qinglong:/ql $ cat version.yaml  version: 2.15.16 changeLogLink: https://t.me/jiao_long/378 changeLog: |   1. 企业微信通知增加代理地址配置 QYWX_ORIGIN   2. 重构任务并发执行逻辑，依赖并发安装逻辑   3. 修复关闭全部任务视图，默认视图筛选错误   4. 增加初始化文件写入，修复参数含有空格影响 task/ql 命令   5. 修复初始化界面、侧边栏、错误页样式   6. 修复拉取订阅文件包含空格出错   7. 修改 api 限流策略，修复检查检查日志   8. 修复环境变量列表搜索字符转码

### Steps to reproduce

升级 ql check /update  不能解决问题

### What is expected?

成功

### What is actually happening?

升级失败 

### System Info

```shell
root@qinglong:/ql $  pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-07-29T21:14:31: PM2 log: Stopping app:public id:1
PM2        | 2023-07-29T21:14:31: PM2 log: App [schedule:0] exited with code [0] via signal [SIGINT]
PM2        | 2023-07-29T21:14:31: PM2 log: App [public:1] exited with code [0] via signal [SIGINT]
PM2        | 2023-07-29T21:14:31: PM2 log: pid=20230 msg=process killed
PM2        | 2023-07-29T21:14:31: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-07-29T21:14:31: PM2 log: pid=20231 msg=process killed
PM2        | 2023-07-29T21:14:31: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-07-29T21:14:35: PM2 log: App [schedule:0] online
PM2        | 2023-07-29T21:14:35: PM2 log: Process 2 in a stopped status, starting it
PM2        | 2023-07-29T21:14:35: PM2 log: Stopping app:panel id:2
PM2        | 2023-07-29T21:14:35: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-07-29T21:14:36: PM2 log: pid=20264 msg=process killed
PM2        | 2023-07-29T21:14:36: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-07-29T21:14:37: PM2 log: App [public:1] online
PM2        | 2023-07-29T21:14:46: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-07-29T21:14:35: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-07-29T21:14:35: info:    ✌️ Sentry loaded
1|public   | 2023-07-29T21:14:37: info:    ✌️ DB loaded
1|public   | 2023-07-29T21:14:37: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-07-29T21:14:39: info:    ✌️ DB loaded
2|panel    | 2023-07-29T21:14:39: info:    ✌️ Init file down
2|panel    | 2023-07-29T21:14:39: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-07-29T21:14:41: - /ql/static/build/api/system.js
2|panel    | 2023-07-29T21:14:41: - /ql/static/build/api/index.js
2|panel    | 2023-07-29T21:14:41: - /ql/static/build/loaders/express.js
2|panel    | 2023-07-29T21:14:41: - /ql/static/build/loaders/app.js
2|panel    | 2023-07-29T21:14:41: - /ql/static/build/app.js
2|panel    | 2023-07-29T21:14:41:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2|panel    | 2023-07-29T21:14:41:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-07-29T21:14:41:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-07-29T21:14:41:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2|panel    | 2023-07-29T21:14:41:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2|panel    | 2023-07-29T21:14:41:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2|panel    | 2023-07-29T21:14:41:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2|panel    | 2023-07-29T21:14:41:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2|panel    | 2023-07-29T21:14:41:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2|panel    | 2023-07-29T21:14:41:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)
```

**Comment by China-BlueFat** [comment]
schedule 这个报错

**Comment by niyueyeee** [comment]
> 时间表报这个错误

那问下 如何操作能解决

**Comment by whyour** [comment]
使用宿主机方式更新下

1. 首先更新镜像，确保更新到了最新版镜像
2. 确保原来映射了 data 目录
3. 使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
