### ISSUE TITLE
更新后无法启动

### ISSUE THREAD

**Issue by 1127957008** [whyour/qinglong#2043]
### Qinglong version

ubuntu系统安装的

### Steps to reproduce

系统内直接点击更新后无法打开，容器里执行更新和修复也不行

### What is expected?

怎么去修复

### What is actually happening?

更新后无法打开

### System Info

```shell
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-07-30T16:27:05: PM2 log: Stopping app:public id:1
PM2        | 2023-07-30T16:27:05: PM2 log: App [schedule:0] exited with code [0] via signal [SIGINT]
PM2        | 2023-07-30T16:27:05: PM2 log: App [public:1] exited with code [0] via signal [SIGINT]
PM2        | 2023-07-30T16:27:06: PM2 log: pid=338 msg=process killed
PM2        | 2023-07-30T16:27:06: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-07-30T16:27:06: PM2 log: pid=339 msg=process killed
PM2        | 2023-07-30T16:27:06: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-07-30T16:27:06: PM2 log: App [schedule:0] online
PM2        | 2023-07-30T16:27:06: PM2 log: Process 2 in a stopped status, starting it
PM2        | 2023-07-30T16:27:06: PM2 log: Stopping app:panel id:2
PM2        | 2023-07-30T16:27:07: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-07-30T16:27:07: PM2 log: pid=484 msg=process killed
PM2        | 2023-07-30T16:27:07: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-07-30T16:27:07: PM2 log: App [public:1] online
PM2        | 2023-07-30T16:27:17: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-07-30T16:27:06: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-07-30T16:27:06: info:    ✌️ Sentry loaded
1|public   | 2023-07-30T16:27:07: info:    ✌️ DB loaded
1|public   | 2023-07-30T16:27:07: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-07-30T16:27:08: info:    ✌️ DB loaded
2|panel    | 2023-07-30T16:27:08: info:    ✌️ Init file down
2|panel    | 2023-07-30T16:27:08: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-07-30T16:27:08: - /ql/static/build/api/system.js
2|panel    | 2023-07-30T16:27:08: - /ql/static/build/api/index.js
2|panel    | 2023-07-30T16:27:08: - /ql/static/build/loaders/express.js
2|panel    | 2023-07-30T16:27:08: - /ql/static/build/loaders/app.js
2|panel    | 2023-07-30T16:27:08: - /ql/static/build/app.js
2|panel    | 2023-07-30T16:27:08:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
2|panel    | 2023-07-30T16:27:08:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-07-30T16:27:08:     at require (node:internal/modules/cjs/helpers:103:18)
2|panel    | 2023-07-30T16:27:08:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2|panel    | 2023-07-30T16:27:08:     at Module._compile (node:internal/modules/cjs/loader:1159:14)
2|panel    | 2023-07-30T16:27:08:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
2|panel    | 2023-07-30T16:27:08:     at Module.load (node:internal/modules/cjs/loader:1037:32)
2|panel    | 2023-07-30T16:27:08:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
2|panel    | 2023-07-30T16:27:08:     at Module.require (node:internal/modules/cjs/loader:1061:19)
2|panel    | 2023-07-30T16:27:08:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)
```

**Comment by China-BlueFat** [comment]
我也是

**Comment by whyour** [comment]
使用宿主机方式更新下

1. 首先更新镜像，确保更新到了最新版镜像
2. 确保原来映射了 data 目录
3. 使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
