### ISSUE TITLE
升级异常

### ISSUE THREAD

**Issue by aiyamayaaa** [whyour/qinglong#2049]
### Qinglong version

v2.15.17

### Steps to reproduce

升级刷新进入/error页面

### What is expected?

升级刷新进入/error页面

### What is actually happening?

升级刷新进入/error页面

### System Info

```shell
PM2        | 2023-08-03T14:09:24: PM2 log: Stopping app:public id:1
PM2        | 2023-08-03T14:09:24: PM2 log: App [schedule:0] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-03T14:09:24: PM2 log: App [public:1] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-03T14:09:24: PM2 log: pid=2915 msg=process killed
PM2        | 2023-08-03T14:09:24: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-03T14:09:24: PM2 log: pid=2916 msg=process killed
PM2        | 2023-08-03T14:09:24: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-08-03T14:09:26: PM2 log: App [schedule:0] online
PM2        | 2023-08-03T14:09:26: PM2 log: Process 2 in a stopped status, starting it
PM2        | 2023-08-03T14:09:26: PM2 log: Stopping app:panel id:2
PM2        | 2023-08-03T14:09:26: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-03T14:09:26: PM2 log: pid=2942 msg=process killed
PM2        | 2023-08-03T14:09:26: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-08-03T14:09:26: PM2 log: App [public:1] online
PM2        | 2023-08-03T14:09:36: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-08-03T14:09:26: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-03T14:09:26: info:    ✌️ Sentry loaded
1|public   | 2023-08-03T14:09:26: info:    ✌️ DB loaded
1|public   | 2023-08-03T14:09:26: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-03T14:09:27: info:    ✌️ DB loaded
2|panel    | 2023-08-03T14:09:27: info:    ✌️ Init file down
2|panel    | 2023-08-03T14:09:27: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-03T14:09:28: - /ql/static/build/api/system.js
2|panel    | 2023-08-03T14:09:28: - /ql/static/build/api/index.js
2|panel    | 2023-08-03T14:09:28: - /ql/static/build/loaders/express.js
2|panel    | 2023-08-03T14:09:28: - /ql/static/build/loaders/app.js
2|panel    | 2023-08-03T14:09:28: - /ql/static/build/app.js
2|panel    | 2023-08-03T14:09:28:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
2|panel    | 2023-08-03T14:09:28:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-08-03T14:09:28:     at require (node:internal/modules/cjs/helpers:110:18)
2|panel    | 2023-08-03T14:09:28:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2|panel    | 2023-08-03T14:09:28:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2|panel    | 2023-08-03T14:09:28:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2|panel    | 2023-08-03T14:09:28:     at Module.load (node:internal/modules/cjs/loader:1119:32)
2|panel    | 2023-08-03T14:09:28:     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
2|panel    | 2023-08-03T14:09:28:     at Module.require (node:internal/modules/cjs/loader:1143:19)
2|panel    | 2023-08-03T14:09:28:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)
```

**Comment by whyour** [comment]
使用宿主机方式更新下

1. 首先更新镜像，确保更新到了最新版镜像
2. 确保原来映射了 data 目录
3. 使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
