### ISSUE TITLE
服务启动超时

### ISSUE THREAD

**Issue by Hanbing1739** [whyour/qinglong#2053]
### Qinglong version

正式版whyour/qinglong:latest

### Steps to reproduce

2023-08-04T21:15:56: Error:
2023-08-04T21:15:56: at Database.<anonymous> (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:236:27)
2023-08-04T21:15:56: at /ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:234:50
2023-08-04T21:15:56: at new Promise (<anonymous>)
2023-08-04T21:15:56: at Query.run (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:234:12)
2023-08-04T21:15:56: at /ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/sequelize.js:650:28
2023-08-04T21:15:56: at SQLiteQueryInterface.select (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/abstract/query-interface.js:1001:12)
2023-08-04T21:15:56: at Function.findAll (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/model.js:1824:21)
2023-08-04T21:15:56: at Function.findOne (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/model.js:1998:12)
2023-08-04T21:15:56: at TaskLimit.setCustomLimit (/ql/back/shared/pLimit.ts:19:17) {
2023-08-04T21:15:56: name: 'SequelizeDatabaseError',
2023-08-04T21:15:56: parent: [Error: SQLITE_ERROR: no such table: Auths] {
2023-08-04T21:15:56: errno: 1,
2023-08-04T21:15:56: code: 'SQLITE_ERROR',
2023-08-04T21:15:56: sql: "SELECT `id`, `ip`, `type`, `info`, `createdAt`, `updatedAt` FROM `Auths` AS `Auth` WHERE `Auth`.`type` = 'systemConfig' LIMIT 1;"
2023-08-04T21:15:56: },
2023-08-04T21:15:56: original: [Error: SQLITE_ERROR: no such table: Auths] {
2023-08-04T21:15:56: errno: 1,
2023-08-04T21:15:56: code: 'SQLITE_ERROR',
2023-08-04T21:15:56: sql: "SELECT `id`, `ip`, `type`, `info`, `createdAt`, `updatedAt` FROM `Auths` AS `Auth` WHERE `Auth`.`type` = 'systemConfig' LIMIT 1;"
2023-08-04T21:15:56: },
2023-08-04T21:15:56: sql: "SELECT `id`, `ip`, `type`, `info`, `createdAt`, `updatedAt` FROM `Auths` AS `Auth` WHERE `Auth`.`type` = 'systemConfig' LIMIT 1;",
2023-08-04T21:15:56: parameters: {}
2023-08-04T21:15:56: }
2023-08-04T21:16:03: Error: spawn ENOMEM
2023-08-04T21:16:03: at ChildProcess.spawn (node:internal/child_process:413:11)
2023-08-04T21:16:03: at spawn (node:child_process:757:9)
2023-08-04T21:16:03: at Object.execFile (node:child_process:348:17)
2023-08-04T21:16:03: at exec (node:child_process:232:25)
2023-08-04T21:16:03: at /ql/back/config/util.ts:392:9
2023-08-04T21:16:03: at new Promise (<anonymous>)
2023-08-04T21:16:03: at promiseExec (/ql/back/config/util.ts:391:10)
2023-08-04T21:16:03: at Object.check (/ql/back/schedule/health.ts:12:36)
2023-08-04T21:16:03: at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:1077:13
2023-08-04T21:16:03: at Http2ServerCallStream.safeDeserializeMessage (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server-call.ts:636:7) {
2023-08-04T21:16:03: errno: -12,
2023-08-04T21:16:03: code: 'ENOMEM',
2023-08-04T21:16:03: syscall: 'spawn'
2023-08-04T21:16:03: }
2023-08-04T21:16:04: Error: spawn ENOMEM
2023-08-04T21:16:04: at ChildProcess.spawn (node:internal/child_process:413:11)
2023-08-04T21:16:04: at spawn (node:child_process:757:9)
2023-08-04T21:16:04: at Object.execFile (node:child_process:348:17)
2023-08-04T21:16:04: at exec (node:child_process:232:25)
2023-08-04T21:16:04: at /ql/back/config/util.ts:392:9
2023-08-04T21:16:04: at new Promise (<anonymous>)
2023-08-04T21:16:04: at promiseExec (/ql/back/config/util.ts:391:10)
2023-08-04T21:16:04: at Object.check (/ql/back/schedule/health.ts:12:36)
2023-08-04T21:16:04: at /ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server.ts:1077:13
2023-08-04T21:16:04: at Http2ServerCallStream.safeDeserializeMessage (/ql/node_modules/.pnpm/@grpc+grpc-js@1.8.15/node_modules/@grpc/grpc-js/src/server-call.ts:636:7) {
2023-08-04T21:16:04: errno: -12,
2023-08-04T21:16:04: code: 'ENOMEM',
2023-08-04T21:16:04: syscall: 'spawn'
2023-08-04T21:16:04: }

2023-08-04T21:16:05: <ref *1> Error: spawnSync /bin/sh ENOMEM
2023-08-04T21:16:05: at Object.spawnSync (node:internal/child_process:1110:20)
2023-08-04T21:16:05: at spawnSync (node:child_process:871:24)
2023-08-04T21:16:05: at execSync (node:child_process:952:15)
2023-08-04T21:16:05: at CronService.set_crontab (/ql/back/services/cron.ts:542:13)
2023-08-04T21:16:05: at CronService.autosave_crontab (/ql/back/services/cron.ts:582:10)
2023-08-04T21:16:05: at exports.default (/ql/back/loaders/initData.ts:128:3)
2023-08-04T21:16:05: at Object.exports.default (/ql/back/loaders/app.ts:16:3)
2023-08-04T21:16:05: at startServer (/ql/back/app.ts:16:3) {
2023-08-04T21:16:05: errno: -12,
2023-08-04T21:16:05: code: 'ENOMEM',
2023-08-04T21:16:05: syscall: 'spawnSync /bin/sh',
2023-08-04T21:16:05: path: '/bin/sh',
2023-08-04T21:16:05: spawnargs: [ '-c', 'crontab /ql/data/config/crontab.list' ],
2023-08-04T21:16:05: error: [Circular *1],
2023-08-04T21:16:05: status: null,
2023-08-04T21:16:05: signal: null,
2023-08-04T21:16:05: output: null,
2023-08-04T21:16:05: pid: 0,
2023-08-04T21:16:05: stdout: null,
2023-08-04T21:16:05: stderr: null
2023-08-04T21:16:05: }
2023-08-04T21:16:05: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-08-04T21:16:05: Error: spawnSync /bin/sh ENOMEM
2023-08-04T21:16:05: at Object.spawnSync (node:internal/child_process:1110:20)
2023-08-04T21:16:05: at spawnSync (node:child_process:871:24)
2023-08-04T21:16:05: at execSync (node:child_process:952:15)
2023-08-04T21:16:05: at CronService.set_crontab (/ql/back/services/cron.ts:542:13)
2023-08-04T21:16:05: at CronService.autosave_crontab (/ql/back/services/cron.ts:582:10)
2023-08-04T21:16:05: at exports.default (/ql/back/loaders/initData.ts:128:3)
2023-08-04T21:16:05: at Object.exports.default (/ql/back/loaders/app.ts:16:3)
2023-08-04T21:16:05: at startServer (/ql/back/app.ts:16:3)
2023-08-04T21:16:06: Error: spawn ENOMEM
2023-08-04T21:16:06: at ChildProcess.spawn (node:internal/child_process:413:11)
2023-08-04T21:16:06: at spawn (node:child_process:757:9)
2023-08-04T21:16:06: at Object.execFile (node:child_process:348:17)
2023-08-04T21:16:06: at exec (node:child_process:232:25)
2023-08-04T21:16:06: at /ql/back/config/util.ts:392:9
2023-08-04T21:16:06: at new Promise (<anonymous>)
2023-08-04T21:16:06: at promiseExec (/ql/back/config/util.ts:391:10)
2023-08-04T21:16:06: at linkCommand (/ql/back/loaders/deps.ts:21:40)
2023-08-04T21:16:06: at exports.default (/ql/back/loaders/deps.ts:45:9)
2023-08-04T21:16:06: at Object.exports.default (/ql/back/loaders/app.ts:19:17) {
2023-08-04T21:16:06: errno: -12,
2023-08-04T21:16:06: code: 'ENOMEM',
2023-08-04T21:16:06: syscall: 'spawn'
2023-08-04T21:16:06: }
2023-08-04T21:16:06: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-08-04T21:16:06: Error: spawn ENOMEM
2023-08-04T21:16:06: at ChildProcess.spawn (node:internal/child_process:413:11)
2023-08-04T21:16:06: at spawn (node:child_process:757:9)
2023-08-04T21:16:06: at Object.execFile (node:child_process:348:17)
2023-08-04T21:16:06: at exec (node:child_process:232:25)
2023-08-04T21:16:06: at /ql/back/config/util.ts:392:9
2023-08-04T21:16:06: at new Promise (<anonymous>)
2023-08-04T21:16:06: at promiseExec (/ql/back/config/util.ts:391:10)
2023-08-04T21:16:06: at linkCommand (/ql/back/loaders/deps.ts:21:40)
2023-08-04T21:16:06: at exports.default (/ql/back/loaders/deps.ts:45:9)
2023-08-04T21:16:06: at Object.exports.default (/ql/back/loaders/app.ts:19:17)

{"code":7,"killed":false,"signal":null,"cmd":"curl -s http://localhost:5600/api/system"}

### What is expected?

下版本修复

### What is actually happening?

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-08-04T21:26:17: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2023-08-04T21:26:17: PM2 log: Time                 : Fri Aug 04 2023 21:26:17 GMT+0800 (China Standard Time)
PM2        | 2023-08-04T21:26:17: PM2 log: PM2 version          : 5.3.0
PM2        | 2023-08-04T21:26:17: PM2 log: Node.js version      : 18.17.0
PM2        | 2023-08-04T21:26:17: PM2 log: Current arch         : arm64
PM2        | 2023-08-04T21:26:17: PM2 log: PM2 home             : /root/.pm2
PM2        | 2023-08-04T21:26:17: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid
PM2        | 2023-08-04T21:26:17: PM2 log: RPC socket file      : /root/.pm2/rpc.sock
PM2        | 2023-08-04T21:26:17: PM2 log: BUS socket file      : /root/.pm2/pub.sock
PM2        | 2023-08-04T21:26:17: PM2 log: Application log path : /root/.pm2/logs
PM2        | 2023-08-04T21:26:17: PM2 log: Worker Interval      : 30000
PM2        | 2023-08-04T21:26:17: PM2 log: Process dump file    : /root/.pm2/dump.pm2
PM2        | 2023-08-04T21:26:17: PM2 log: Concurrent actions   : 2
PM2        | 2023-08-04T21:26:17: PM2 log: SIGTERM timeout      : 1600
PM2        | 2023-08-04T21:26:17: PM2 log: ===============================================================================

**Comment by whyour** [comment]
使用宿主机方式更新下

1. 首先更新镜像，确保更新到了最新版镜像
2. 确保原来映射了 data 目录
3. 使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
