### ISSUE TITLE
v2.16.0，无法ip+5700进入

### ISSUE THREAD

**Issue by tommyhe1217** [whyour/qinglong#2058]
### Qinglong version

v2.16.0

### Steps to reproduce

无法金融后台管理页面，显示“”服务启动超时“，下面2种修复方式都试过了，还是无法进入，
1. 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
2. 容器内执行 ql -l check、ql -l update
容器的状态为“健康”
下面有容器内执行 pm2 logs的日志，请帮忙查看

### What is expected?

能够ip+5700进入，并正常跑起来

### What is actually happening?

ip+5700无法进入，不能启动。

### System Info

```shell
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-08-07T16:57:15: PM2 log: Stopping app:public id:1
PM2        | 2023-08-07T16:57:15: PM2 log: App [schedule:0] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-07T16:57:15: PM2 log: App [public:1] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-07T16:57:15: PM2 log: pid=135 msg=process killed
PM2        | 2023-08-07T16:57:15: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-07T16:57:15: PM2 log: pid=136 msg=process killed
PM2        | 2023-08-07T16:57:15: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-08-07T16:57:19: PM2 log: App [schedule:0] online
PM2        | 2023-08-07T16:57:20: PM2 log: Process 2 in a stopped status, starting it
PM2        | 2023-08-07T16:57:20: PM2 log: Stopping app:panel id:2
PM2        | 2023-08-07T16:57:20: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-07T16:57:20: PM2 log: pid=22980 msg=process killed
PM2        | 2023-08-07T16:57:20: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-08-07T16:57:25: PM2 log: App [public:1] online
PM2        | 2023-08-07T16:57:30: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-08-07T16:57:19: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-07T16:57:19: info:    ✌️ Sentry loaded
1|public   | 2023-08-07T16:57:27: info:    ✌️ DB loaded
1|public   | 2023-08-07T16:57:27: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-07T16:57:25: info:    ✌️ DB loaded
2|panel    | 2023-08-07T16:57:25: info:    ✌️ Init file down
2|panel    | 2023-08-07T16:57:25: info:    ✌️ Sentry loaded
2|panel    | 2023-08-07T16:57:28: info:    ✌️ Dependency Injector loaded
2|panel    | 2023-08-07T16:57:28: [HPM] Proxy created: /  -> http://localhost:5400/api
2|panel    | 2023-08-07T16:57:28: [HPM] Proxy rewrite rule created: "/api/public" ~> ""
2|panel    | 2023-08-07T16:57:28: info:    ✌️ Express loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-07T16:57:28:   sql: 'UPDATE `Crontabs` SET `status`=$1,`updatedAt`=$2',
2|panel    | 2023-08-07T16:57:28:   parameters: {}
2|panel    | 2023-08-07T16:57:28: }
2|panel    | 2023-08-07T16:57:28: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2|panel    | 2023-08-07T16:57:28: Error: 
2|panel    | 2023-08-07T16:57:28:     at Database.<anonymous> (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:236:27)
2|panel    | 2023-08-07T16:57:28:     at /ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:234:50
2|panel    | 2023-08-07T16:57:28:     at new Promise (<anonymous>)
2|panel    | 2023-08-07T16:57:28:     at Query.run (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/query.js:234:12)
2|panel    | 2023-08-07T16:57:28:     at /ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/sequelize.js:650:28
2|panel    | 2023-08-07T16:57:28:     at SQLiteQueryInterface.bulkUpdate (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/abstract/query-interface.js:930:12)
2|panel    | 2023-08-07T16:57:28:     at Function.update (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/model.js:3351:28)
2|panel    | 2023-08-07T16:57:28:     at exports.default (/ql/back/loaders/initData.ts:33:3)
2|panel    | 2023-08-07T16:57:28:     at Object.exports.default (/ql/back/loaders/app.ts:16:3)
2|panel    | 2023-08-07T16:57:28:     at startServer (/ql/back/app.ts:16:3)
```

### Any additional comments?

无

**Comment by maizijuni** [comment]
这个怎么处理？？？

**Comment by whyour** [comment]
你这数据库文件好像有问题

**Comment by tommyhe1217** [comment]
解决不了，重装也不行，放弃了

whyour ***@***.***>于2023年8月11日 周五22:42写道：
