### ISSUE TITLE
青龙应用内更新后无法启动

### ISSUE THREAD

**Issue by lageev** [whyour/qinglong#2083]
### Qinglong version

 x

### Steps to reproduce

启动失败

### What is expected?

正常启动

### What is actually happening?

服务启动超时

### System Info

```shell
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-08-19T17:14:04: PM2 log: App [schedule:0] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-19T17:14:04: PM2 log: App [public:1] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-19T17:14:04: PM2 log: pid=765 msg=process killed
PM2        | 2023-08-19T17:14:04: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-08-19T17:14:04: PM2 log: pid=764 msg=process killed
PM2        | 2023-08-19T17:14:04: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-08-19T17:14:07: PM2 log: App [schedule:0] online
PM2        | 2023-08-19T17:14:07: PM2 log: Process 2 in a stopped status, starting it
PM2        | 2023-08-19T17:14:07: PM2 log: Stopping app:panel id:2
PM2        | 2023-08-19T17:14:07: PM2 log: pid=789 msg=failed to kill - retrying in 100ms
PM2        | 2023-08-19T17:14:07: PM2 log: App [panel:2] exited with code [0] via signal [SIGINT]
PM2        | 2023-08-19T17:14:07: PM2 log: pid=789 msg=process killed
PM2        | 2023-08-19T17:14:07: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-08-19T17:14:08: PM2 log: App [public:1] online
PM2        | 2023-08-19T17:14:17: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-08-19T17:14:07: debug:   ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-08-19T17:14:07: info:    ✌️ Sentry loaded
1|public   | 2023-08-19T17:14:08: info:    ✌️ DB loaded
1|public   | 2023-08-19T17:14:08: debug:   ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-08-19T17:14:10: info:    ✌️ DB loaded
2|panel    | 2023-08-19T17:14:10: info:    ✌️ Init file down
2|panel    | 2023-08-19T17:14:10: info:    ✌️ Sentry loaded

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-08-19T17:14:11: - /ql/static/build/api/system.js
2|panel    | 2023-08-19T17:14:11: - /ql/static/build/api/index.js
2|panel    | 2023-08-19T17:14:11: - /ql/static/build/loaders/express.js
2|panel    | 2023-08-19T17:14:11: - /ql/static/build/loaders/app.js
2|panel    | 2023-08-19T17:14:11: - /ql/static/build/app.js
2|panel    | 2023-08-19T17:14:11:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
2|panel    | 2023-08-19T17:14:11:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2|panel    | 2023-08-19T17:14:11:     at require (node:internal/modules/cjs/helpers:103:18)
2|panel    | 2023-08-19T17:14:11:     at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2|panel    | 2023-08-19T17:14:11:     at Module._compile (node:internal/modules/cjs/loader:1159:14)
2|panel    | 2023-08-19T17:14:11:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
2|panel    | 2023-08-19T17:14:11:     at Module.load (node:internal/modules/cjs/loader:1037:32)
2|panel    | 2023-08-19T17:14:11:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
2|panel    | 2023-08-19T17:14:11:     at Module.require (node:internal/modules/cjs/loader:1061:19)
2|panel    | 2023-08-19T17:14:11:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)
```

**Comment by lageev** [comment]
2023-08-19T17:14:11: Error: Cannot find module 'tar'
2023-08-19T17:14:11: Require stack:
2023-08-19T17:14:11: - /ql/static/build/services/system.js
2023-08-19T17:14:11: - /ql/static/build/api/system.js
2023-08-19T17:14:11: - /ql/static/build/api/index.js
2023-08-19T17:14:11: - /ql/static/build/loaders/express.js
2023-08-19T17:14:11: - /ql/static/build/loaders/app.js
2023-08-19T17:14:11: - /ql/static/build/app.js
2023-08-19T17:14:11: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
2023-08-19T17:14:11: at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-08-19T17:14:11: at require (node:internal/modules/cjs/helpers:103:18)
2023-08-19T17:14:11: at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2023-08-19T17:14:11: at Module._compile (node:internal/modules/cjs/loader:1159:14)
2023-08-19T17:14:11: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
2023-08-19T17:14:11: at Module.load (node:internal/modules/cjs/loader:1037:32)
2023-08-19T17:14:11: at Function.Module._load (node:internal/modules/cjs/loader:878:12)
2023-08-19T17:14:11: at Module.require (node:internal/modules/cjs/loader:1061:19)
2023-08-19T17:14:11: at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-08-19T17:14:11: code: 'MODULE_NOT_FOUND',
2023-08-19T17:14:11: requireStack: [
2023-08-19T17:14:11: '/ql/static/build/services/system.js',
2023-08-19T17:14:11: '/ql/static/build/api/system.js',
2023-08-19T17:14:11: '/ql/static/build/api/index.js',
2023-08-19T17:14:11: '/ql/static/build/loaders/express.js',
2023-08-19T17:14:11: '/ql/static/build/loaders/app.js',
2023-08-19T17:14:11: '/ql/static/build/app.js'
2023-08-19T17:14:11: ]
2023-08-19T17:14:11: }
2023-08-19T17:14:11: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-08-19T17:14:11: Error: Cannot find module 'tar'
2023-08-19T17:14:11: Require stack:
2023-08-19T17:14:11: - /ql/static/build/services/system.js
2023-08-19T17:14:11: - /ql/static/build/api/system.js
2023-08-19T17:14:11: - /ql/static/build/api/index.js
2023-08-19T17:14:11: - /ql/static/build/loaders/express.js
2023-08-19T17:14:11: - /ql/static/build/loaders/app.js
2023-08-19T17:14:11: - /ql/static/build/app.js
2023-08-19T17:14:11: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
2023-08-19T17:14:11: at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-08-19T17:14:11: at require (node:internal/modules/cjs/helpers:103:18)
2023-08-19T17:14:11: at Object.<anonymous> (/ql/back/services/system.ts:27:1)
2023-08-19T17:14:11: at Module._compile (node:internal/modules/cjs/loader:1159:14)
2023-08-19T17:14:11: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
2023-08-19T17:14:11: at Module.load (node:internal/modules/cjs/loader:1037:32)
2023-08-19T17:14:11: at Function.Module._load (node:internal/modules/cjs/loader:878:12)
2023-08-19T17:14:11: at Module.require (node:internal/modules/cjs/loader:1061:19)
2023-08-19T17:14:11: at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)

{"code":7,"killed":false,"signal":null,"cmd":"curl -s http://localhost:5600/api/system","stdout":"","stderr":""}

**Comment by whyour** [comment]
使用宿主机方式更新下

首先更新镜像，确保更新到了最新版镜像
确保原来映射了 data 目录
使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
