### ISSUE TITLE
docker-compose安装成功，服务启动超时

### ISSUE THREAD

**Issue by wan-null** [whyour/qinglong#2088]
### Qinglong version

2.15.20

### Steps to reproduce

使用docker-compose安装

### What is expected?

正常启动

### What is actually happening?

服务启动超时
请先按如下方式修复：
1. 宿主机执行 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名>
2. 容器内执行 ql -l check、ql -l update
3. 如果无法解决，容器内执行 pm2 logs，拷贝执行结果[提交 issue](https://github.com/whyour/qinglong/issues/new?assignees=&labels=&template=bug_report.yml)

### System Info

```shell
2023-08-26T21:19:05: Error: EACCES: permission denied, mkdir '/ql/data/db'
2023-08-26T21:19:05: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:19:05: at ConnectionManager.getConnection (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/sqlite/connection-manager.js:70:10)
2023-08-26T21:19:05: at /ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/sequelize.js:638:111
2023-08-26T21:19:05: at /ql/node_modules/.pnpm/retry-as-promised@7.0.4/node_modules/retry-as-promised/dist/index.js:59:25
2023-08-26T21:19:05: at new Promise (<anonymous>)
2023-08-26T21:19:05: at retryAsPromised (/ql/node_modules/.pnpm/retry-as-promised@7.0.4/node_modules/retry-as-promised/dist/index.js:48:12)
2023-08-26T21:19:05: at Sequelize.query (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/sequelize.js:631:12)
2023-08-26T21:19:05: at SQLiteQueryInterface.select (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/dialects/abstract/query-interface.js:1001:33)
2023-08-26T21:19:05: at Function.findAll (/ql/node_modules/.pnpm/sequelize@6.32.0_@whyour+sqlite3@1.0.3/node_modules/sequelize/src/model.js:1824:47)
2023-08-26T21:19:05: at processTicksAndRejections (node:internal/process/task_queues:95:5) {
2023-08-26T21:19:05: errno: -13,
2023-08-26T21:19:05: syscall: 'mkdir',
2023-08-26T21:19:05: code: 'EACCES',
2023-08-26T21:19:05: path: '/ql/data/db'
2023-08-26T21:19:05: }

2023-08-26T21:21:41: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:21:41: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:21:41: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:21:41: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:21:41: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:21:41: errno: -13,
2023-08-26T21:21:41: syscall: 'mkdir',
2023-08-26T21:21:41: code: 'EACCES',
2023-08-26T21:21:41: path: '/ql/data/config/'
2023-08-26T21:21:41: }
2023-08-26T21:21:48: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:21:48: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:21:48: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:21:48: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:21:48: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:21:48: errno: -13,
2023-08-26T21:21:48: syscall: 'mkdir',
2023-08-26T21:21:48: code: 'EACCES',
2023-08-26T21:21:48: path: '/ql/data/config/'
2023-08-26T21:21:48: }
2023-08-26T21:21:56: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:21:56: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:21:56: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:21:56: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:21:56: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:21:56: errno: -13,
2023-08-26T21:21:56: syscall: 'mkdir',
2023-08-26T21:21:56: code: 'EACCES',
2023-08-26T21:21:56: path: '/ql/data/config/'
2023-08-26T21:21:56: }
2023-08-26T21:22:04: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:22:04: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:22:04: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:22:04: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:22:04: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:22:04: errno: -13,
2023-08-26T21:22:04: syscall: 'mkdir',
2023-08-26T21:22:04: code: 'EACCES',
2023-08-26T21:22:04: path: '/ql/data/config/'
2023-08-26T21:22:04: }
2023-08-26T21:22:11: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:22:11: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:22:11: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:22:11: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:22:11: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:22:11: errno: -13,
2023-08-26T21:22:11: syscall: 'mkdir',
2023-08-26T21:22:11: code: 'EACCES',
2023-08-26T21:22:11: path: '/ql/data/config/'
2023-08-26T21:22:11: }
2023-08-26T21:22:18: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:22:18: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:22:18: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:22:18: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:22:18: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:22:18: errno: -13,
2023-08-26T21:22:18: syscall: 'mkdir',
2023-08-26T21:22:18: code: 'EACCES',
2023-08-26T21:22:18: path: '/ql/data/config/'
2023-08-26T21:22:18: }
2023-08-26T21:22:25: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:22:25: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:22:25: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:22:25: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:22:25: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:22:25: errno: -13,
2023-08-26T21:22:25: syscall: 'mkdir',
2023-08-26T21:22:25: code: 'EACCES',
2023-08-26T21:22:25: path: '/ql/data/config/'
2023-08-26T21:22:25: }
2023-08-26T21:22:33: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:22:33: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:22:33: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:22:33: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:22:33: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:22:33: errno: -13,
2023-08-26T21:22:33: syscall: 'mkdir',
2023-08-26T21:22:33: code: 'EACCES',
2023-08-26T21:22:33: path: '/ql/data/config/'
2023-08-26T21:22:33: }
2023-08-26T21:22:40: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:22:40: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:22:40: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:22:40: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:22:40: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:22:40: errno: -13,
2023-08-26T21:22:40: syscall: 'mkdir',
2023-08-26T21:22:40: code: 'EACCES',
2023-08-26T21:22:40: path: '/ql/data/config/'
2023-08-26T21:22:40: }
2023-08-26T21:22:48: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:22:48: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:22:48: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:22:48: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:22:48: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:22:48: errno: -13,
2023-08-26T21:22:48: syscall: 'mkdir',
2023-08-26T21:22:48: code: 'EACCES',
2023-08-26T21:22:48: path: '/ql/data/config/'
2023-08-26T21:22:48: }
2023-08-26T21:22:54: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:22:54: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:22:54: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:22:54: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:22:54: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:22:54: errno: -13,
2023-08-26T21:22:54: syscall: 'mkdir',
2023-08-26T21:22:54: code: 'EACCES',
2023-08-26T21:22:54: path: '/ql/data/config/'
2023-08-26T21:22:54: }
2023-08-26T21:23:01: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:01: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:01: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:01: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:01: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:01: errno: -13,
2023-08-26T21:23:01: syscall: 'mkdir',
2023-08-26T21:23:01: code: 'EACCES',
2023-08-26T21:23:01: path: '/ql/data/config/'
2023-08-26T21:23:01: }
2023-08-26T21:23:09: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:09: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:09: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:09: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:09: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:09: errno: -13,
2023-08-26T21:23:09: syscall: 'mkdir',
2023-08-26T21:23:09: code: 'EACCES',
2023-08-26T21:23:09: path: '/ql/data/config/'
2023-08-26T21:23:09: }
2023-08-26T21:23:17: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:17: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:17: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:17: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:17: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:17: errno: -13,
2023-08-26T21:23:17: syscall: 'mkdir',
2023-08-26T21:23:17: code: 'EACCES',
2023-08-26T21:23:17: path: '/ql/data/config/'
2023-08-26T21:23:17: }
2023-08-26T21:23:24: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:24: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:24: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:24: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:24: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:24: errno: -13,
2023-08-26T21:23:24: syscall: 'mkdir',
2023-08-26T21:23:24: code: 'EACCES',
2023-08-26T21:23:24: path: '/ql/data/config/'
2023-08-26T21:23:24: }
2023-08-26T21:23:31: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:31: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:31: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:31: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:31: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:31: errno: -13,
2023-08-26T21:23:31: syscall: 'mkdir',
2023-08-26T21:23:31: code: 'EACCES',
2023-08-26T21:23:31: path: '/ql/data/config/'
2023-08-26T21:23:31: }
2023-08-26T21:23:38: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:38: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:38: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:38: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:38: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:38: errno: -13,
2023-08-26T21:23:38: syscall: 'mkdir',
2023-08-26T21:23:38: code: 'EACCES',
2023-08-26T21:23:38: path: '/ql/data/config/'
2023-08-26T21:23:38: }
2023-08-26T21:23:45: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:45: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:45: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:45: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:45: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:45: errno: -13,
2023-08-26T21:23:45: syscall: 'mkdir',
2023-08-26T21:23:45: code: 'EACCES',
2023-08-26T21:23:45: path: '/ql/data/config/'
2023-08-26T21:23:45: }
2023-08-26T21:23:52: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:52: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:52: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:52: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:52: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:52: errno: -13,
2023-08-26T21:23:52: syscall: 'mkdir',
2023-08-26T21:23:52: code: 'EACCES',
2023-08-26T21:23:52: path: '/ql/data/config/'
2023-08-26T21:23:52: }
2023-08-26T21:23:59: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:23:59: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:23:59: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:23:59: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:23:59: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:23:59: errno: -13,
2023-08-26T21:23:59: syscall: 'mkdir',
2023-08-26T21:23:59: code: 'EACCES',
2023-08-26T21:23:59: path: '/ql/data/config/'
2023-08-26T21:23:59: }
2023-08-26T21:24:06: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:24:06: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:24:06: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:24:06: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:24:06: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:24:06: errno: -13,
2023-08-26T21:24:06: syscall: 'mkdir',
2023-08-26T21:24:06: code: 'EACCES',
2023-08-26T21:24:06: path: '/ql/data/config/'
2023-08-26T21:24:06: }
2023-08-26T21:24:14: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:24:14: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:24:14: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:24:14: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:24:14: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:24:14: errno: -13,
2023-08-26T21:24:14: syscall: 'mkdir',
2023-08-26T21:24:14: code: 'EACCES',
2023-08-26T21:24:14: path: '/ql/data/config/'
2023-08-26T21:24:14: }
2023-08-26T21:24:20: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:24:20: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:24:20: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:24:20: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:24:20: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:24:20: errno: -13,
2023-08-26T21:24:20: syscall: 'mkdir',
2023-08-26T21:24:20: code: 'EACCES',
2023-08-26T21:24:20: path: '/ql/data/config/'
2023-08-26T21:24:20: }
2023-08-26T21:24:28: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:24:28: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:24:28: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:24:28: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:24:28: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:24:28: errno: -13,
2023-08-26T21:24:28: syscall: 'mkdir',
2023-08-26T21:24:28: code: 'EACCES',
2023-08-26T21:24:28: path: '/ql/data/config/'
2023-08-26T21:24:28: }
2023-08-26T21:24:35: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:24:35: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:24:35: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:24:35: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:24:35: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:24:35: errno: -13,
2023-08-26T21:24:35: syscall: 'mkdir',
2023-08-26T21:24:35: code: 'EACCES',
2023-08-26T21:24:35: path: '/ql/data/config/'
2023-08-26T21:24:35: }
2023-08-26T21:24:42: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:24:42: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:24:42: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:24:42: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:24:42: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:24:42: errno: -13,
2023-08-26T21:24:42: syscall: 'mkdir',
2023-08-26T21:24:42: code: 'EACCES',
2023-08-26T21:24:42: path: '/ql/data/config/'
2023-08-26T21:24:42: }
2023-08-26T21:24:48: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:24:48: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:24:48: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:24:48: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:24:48: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:24:48: errno: -13,
2023-08-26T21:24:48: syscall: 'mkdir',
2023-08-26T21:24:48: code: 'EACCES',
2023-08-26T21:24:48: path: '/ql/data/config/'
2023-08-26T21:24:48: }
2023-08-26T21:24:55: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:24:55: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:24:55: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:24:55: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:24:55: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:24:55: errno: -13,
2023-08-26T21:24:55: syscall: 'mkdir',
2023-08-26T21:24:55: code: 'EACCES',
2023-08-26T21:24:55: path: '/ql/data/config/'
2023-08-26T21:24:55: }
2023-08-26T21:25:02: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:25:02: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:25:02: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:25:02: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:25:02: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:25:02: errno: -13,
2023-08-26T21:25:02: syscall: 'mkdir',
2023-08-26T21:25:02: code: 'EACCES',
2023-08-26T21:25:02: path: '/ql/data/config/'
2023-08-26T21:25:02: }
2023-08-26T21:25:09: Error: EACCES: permission denied, mkdir '/ql/data/config/'
2023-08-26T21:25:09: at Object.mkdirSync (node:fs:1398:3)
2023-08-26T21:25:09: at Object.exports.default (/ql/back/loaders/initFile.ts:49:8)
2023-08-26T21:25:09: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-26T21:25:09: at startServer (/ql/back/app.ts:12:3) {
2023-08-26T21:25:09: errno: -13,
2023-08-26T21:25:09: syscall: 'mkdir',
2023-08-26T21:25:09: code: 'EACCES',
2023-08-26T21:25:09: path: '/ql/data/config/'
2023-08-26T21:25:09: }

{"code":7,"killed":false,"signal":null,"cmd":"curl -s http://localhost:5600/api/system"}
```

**Comment by whyour** [comment]
是不是映射的目录有问题，映射 data 目录，你本机的目录没有修改权限？
