### ISSUE TITLE
Windows Docker部署无法打开页面

### ISSUE THREAD

**Issue by SZnAl** [whyour/qinglong#2102]
### Qinglong version

2.16.2

### Steps to reproduce

自上个版本更新后，无法打开页面，启动后进入localhost:5700便自动进入error页面，页面一直是loading状态
![image](https://github.com/whyour/qinglong/assets/19545460/b115c3f4-32a6-4ede-ac4b-bc7bb74ad009)

使用update与check均无法解决

### What is expected?

正常打开页面

### What is actually happening?

使用update指令更新内容如下
`## 开始执行... 2023-09-04 09:31:18

使用 github 源更新...

开始更新仓库：/ql
From https://github.com/whyour/qinglong
 * branch            master     -> FETCH_HEAD

更新青龙源文件成功...

开始拉取 https://github.com/whyour/qinglong-static.git 到 /ql/data/repo/static

Cloning into '/ql/data/repo/static'...

更新青龙静态资源成功...

重启面板中...
[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [schedule](0) ✓
[PM2] [public](1) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [panel](2) ✓
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 0        │ 0      │ 18   │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 0        │ 0      │ 18   │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 0        │ 0      │ 18   │ errored   │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

## 执行结束... 2023-09-04 09:31:45 耗时 27 秒`

当前使用check后检测内容如下
`## 开始执行... 2023-09-04 09:32:56

=====> 开始检测

changed 1 package in 564ms
检测到旧的db目录，拷贝到data目录...

检测到旧的scripts目录，拷贝到data目录...

检测到旧的log目录，拷贝到data目录...

检测到旧的config目录，拷贝到data目录...

fetch https://mirrors.aliyun.com/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
OK: 1010 MiB in 200 packages
Writing to /root/.config/pip/pip.conf
Lockfile is up to date, resolution step is skipped
Already up to date

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │                Update available! 8.3.1 → 8.7.1.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.7.1   │
   │                Run "pnpm add -g pnpm" to update.                │
   │                                                                 │
   │     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

Done in 1s
Progress: resolved 0, reused 1, downloaded 0, added 0
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
 WARN  deprecated har-validator@5.1.5: this library is no longer supported
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 341, reused 305, downloaded 2, added 0
 WARN  deprecated vm2@3.9.14: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
Progress: resolved 575, reused 549, downloaded 4, added 0
Packages: +4 -4
++++----
.../esbuild@0.18.20/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.18.20/node_modules/esbuild postinstall: Done

/root/.local/share/pnpm/global/5:
- tsx 3.12.7
+ tsx 3.12.8

Done in 3.5s
Progress: resolved 579, reused 553, downloaded 4, added 4, done
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...

devDependencies: skipped

> @ postinstall /ql
> max setup 2>/dev/null || true

Done in 795ms
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

安装 /ql/data/scripts 依赖包...

devDependencies: skipped

Done in 496ms
---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="https://qn.whyour.cn/favicon.svg">
<link rel="stylesheet" href="./umi.8a0eaca6.css">
<script src="./api/env.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>
<script src="./umi.92f2c6d2.js"></script>

</body></html>

=====> 面板服务启动正常

=====> 检测nginx服务
   76 nginx: master process nginx -c /etc/nginx/nginx.conf
  559 nginx: worker process
  560 nginx: worker process
  561 nginx: worker process
  562 nginx: worker process
  563 nginx: worker process
  564 nginx: worker process
  565 nginx: worker process
  566 nginx: worker process
  567 nginx: worker process
  568 nginx: worker process
  569 nginx: worker process
  570 nginx: worker process

=====> nginx服务正常

---> pm2日志
2023-09-04T09:31:36: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:36: Require stack:
2023-09-04T09:31:36: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:36: - /ql/static/build/app.js
2023-09-04T09:31:36:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:36:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:36:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:36:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:36:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:36:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:36:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:36:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:36:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:36:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:36:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:36:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:36: }
2023-09-04T09:31:36: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:36: Require stack:
2023-09-04T09:31:36: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:36: - /ql/static/build/app.js
2023-09-04T09:31:36:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:36:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:36:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:36:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:36:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:36:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:36:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:36:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:36:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:36:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:36:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:36:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:36: }
2023-09-04T09:31:36: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:36: Require stack:
2023-09-04T09:31:36: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:36: - /ql/static/build/app.js
2023-09-04T09:31:36:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:36:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:36:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:36:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:36:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:36:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:36:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:36:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:36:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:36:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:36:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:36:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:36: }
2023-09-04T09:31:36: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:36: Require stack:
2023-09-04T09:31:36: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:36: - /ql/static/build/app.js
2023-09-04T09:31:36:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:36:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:36:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:36:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:36:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:36:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:36:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:36:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:36:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:36:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:36:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:36:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:36: }
2023-09-04T09:31:37: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:37: Require stack:
2023-09-04T09:31:37: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:37: - /ql/static/build/app.js
2023-09-04T09:31:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:37:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:37:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:37:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:37:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:37:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:37:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:37:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:37:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:37: }
2023-09-04T09:31:37: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:37: Require stack:
2023-09-04T09:31:37: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:37: - /ql/static/build/app.js
2023-09-04T09:31:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:37:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:37:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:37:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:37:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:37:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:37:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:37:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:37:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:37: }
2023-09-04T09:31:37: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:37: Require stack:
2023-09-04T09:31:37: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:37: - /ql/static/build/app.js
2023-09-04T09:31:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:37:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:37:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:37:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:37:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:37:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:37:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:37:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:37:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:37: }
2023-09-04T09:31:38: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:38: Require stack:
2023-09-04T09:31:38: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:38: - /ql/static/build/app.js
2023-09-04T09:31:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:38:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:38:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:38:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:38:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:38:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:38:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:38:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:38:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:38: }
2023-09-04T09:31:38: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:38: Require stack:
2023-09-04T09:31:38: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:38: - /ql/static/build/app.js
2023-09-04T09:31:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:38:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:38:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:38:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:38:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:38:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:38:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:38:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:38:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:38: }
2023-09-04T09:31:38: Error: Cannot find module 'winston-daily-rotate-file'
2023-09-04T09:31:38: Require stack:
2023-09-04T09:31:38: - /ql/static/build/loaders/logger.js
2023-09-04T09:31:38: - /ql/static/build/app.js
2023-09-04T09:31:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-09-04T09:31:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2023-09-04T09:31:38:     at require (node:internal/modules/cjs/helpers:110:18)
2023-09-04T09:31:38:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2023-09-04T09:31:38:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-09-04T09:31:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-09-04T09:31:38:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-09-04T09:31:38:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2023-09-04T09:31:38:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-09-04T09:31:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2023-09-04T09:31:38:   code: 'MODULE_NOT_FOUND',
2023-09-04T09:31:38:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2023-09-04T09:31:38: }

=====> 检测后台

[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [schedule](0) ✓
[PM2] [public](1) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [panel](2) ✓
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 0        │ 0      │ 27   │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 0        │ 0      │ 27   │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 0        │ 0      │ 27   │ errored   │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

=====> 检测结束

## 执行结束... 2023-09-04 09:33:26 耗时 30 秒　　　　　
root@b758dca07597:/ql $ ql help
## 开始执行... 2023-09-04 09:36:13

命令输入错误...

ql命令使用方法：
1.  update                                                                  # 更新并重启青龙
2.  extra                                                                   # 运行自定义脚本
3.  raw <fileurl>                                                            # 更新单个脚本文件
4.  repo <repourl> <path> <blacklist> <dependence> <branch> <extensions>    # 更新单个仓库的脚本
5.  rmlog <days>                                                            # 删除旧日志
6.  bot                                                                     # 启动tg-bot
7.  check                                                                   # 检测青龙环境并修复
8.  resetlet                                                                # 重置登录错误次数
9.  resettfa                                                                # 禁用两步登录

**Comment by love520222** [comment]
同问题啊

**Comment by Van0313** [comment]
同问题啊,不过我上个月就发现了，今天试了一下还是一样，面板跑不起来。我是群晖的容器

**Comment by whyour** [comment]
使用宿主机方式更新下

首先更新镜像，确保更新到了最新版镜像
**确保原来映射了 data 目录**
使用 docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <容器名> 更新
