### ISSUE TITLE
一直存在的问题

### ISSUE THREAD

**Issue by dreamfly32** [whyour/qinglong#2147]
### Qinglong version

2.16.3

### Steps to reproduce

当配置了ALL_PROXY 变量，重启后进不去面板，注释后就可以了，代理没问题，无论socks5还是http，这个问题老早就提出来了
https://github.com/whyour/qinglong/issues/1932
https://github.com/whyour/qinglong/issues/1994

### What is expected?

。

### What is actually happening?

2023-09-26T11:45:29: Server need close, singal SIGINT
2023-09-26T11:47:21: ValidationError: The Express 'trust proxy' setting is true, which allows anyone to trivially bypass IP-based rate limiting. See https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/ for more information.
2023-09-26T11:47:21: at Object.trustProxy (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:148:13)
2023-09-26T11:47:21: at Object.wrappedValidations.<computed> [as trustProxy] (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:324:22)
2023-09-26T11:47:21: at Object.keyGenerator (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:582:20)
2023-09-26T11:47:21: at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:633:32
2023-09-26T11:47:21: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-26T11:47:21: at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:615:5 {
2023-09-26T11:47:21: code: 'ERR_ERL_PERMISSIVE_TRUST_PROXY',
2023-09-26T11:47:21: help: 'https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/'
2023-09-26T11:47:21: }
2023-09-26T11:52:09: ValidationError: The Express 'trust proxy' setting is true, which allows anyone to trivially bypass IP-based rate limiting. See https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/ for more information.
2023-09-26T11:52:09: at Object.trustProxy (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:148:13)
2023-09-26T11:52:09: at Object.wrappedValidations.<computed> [as trustProxy] (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:324:22)
2023-09-26T11:52:09: at Object.keyGenerator (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:582:20)
2023-09-26T11:52:09: at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:633:32
2023-09-26T11:52:09: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-26T11:52:09: at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:615:5 {
2023-09-26T11:52:09: code: 'ERR_ERL_PERMISSIVE_TRUST_PROXY',
2023-09-26T11:52:09: help: 'https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/'
2023-09-26T11:52:09: }
2023-09-26T13:17:56: ValidationError: The Express 'trust proxy' setting is true, which allows anyone to trivially bypass IP-based rate limiting. See https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/ for more information.
2023-09-26T13:17:56: at Object.trustProxy (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:148:13)
2023-09-26T13:17:56: at Object.wrappedValidations.<computed> [as trustProxy] (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:324:22)
2023-09-26T13:17:56: at Object.keyGenerator (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:582:20)
2023-09-26T13:17:56: at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:633:32
2023-09-26T13:17:56: at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-26T13:17:56: at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:615:5 {
2023-09-26T13:17:56: code: 'ERR_ERL_PERMISSIVE_TRUST_PROXY',
2023-09-26T13:17:56: help: 'https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/'
2023-09-26T13:17:56: }
2023-09-26T13:19:31:
2023-09-26T13:19:31: <--- Last few GCs --->
2023-09-26T13:19:31:
2023-09-26T13:19:31: [123:0x7f6087745310] 131187 ms: Scavenge 695.6 (804.2) -> 694.7 (804.2) MB, 4.3 / 0.0 ms (average mu = 0.896, current mu = 0.761) allocation failure;
2023-09-26T13:19:31: [123:0x7f6087745310] 135574 ms: Mark-sweep (reduce) 1047.0 (1149.4) -> 686.5 (1068.2) MB, 2240.7 / 0.0 ms (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2669 ms) (average mu = 0.694, current mu = 0.505
2023-09-26T13:19:31:
2023-09-26T13:19:31: <--- JS stacktrace --->
2023-09-26T13:19:31:
2023-09-26T13:19:31: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

{"code":52,"killed":false,"signal":null,"cmd":"curl -s http://0.0.0.0:5600/api/system","stdout":"","stderr":""}

**Comment by whyour** [comment]
2.16.4 已修复
