### ISSUE TITLE
pymssql 2.2.10 连接sql server数据库报错 

### ISSUE THREAD

**Issue by unika** [whyour/qinglong#2161]
### Qinglong version

v2.16.4

### Steps to reproduce

Traceback (most recent call last):
  File "/ql/data/scripts/gzl/user.py", line 335, in <module>
    run()
  File "/ql/data/scripts/gzl/user.py", line 280, in run
    userList = gzluser.get_user_list()
  File "/ql/data/scripts/gzl/user.py", line 58, in get_user_list
    res_json = self.sql_server.query_to_json(sql)
  File "/ql/data/scripts/gzl/MSSQL.py", line 54, in query_to_json
    cur = self.__get_connect()
  File "/ql/data/scripts/gzl/MSSQL.py", line 20, in __get_connect
    self.conn = pymssql.connect(host=self.host, user=self.user, password=self.pwd, database=self.db,charset="CP936")
  File "src/pymssql/_pymssql.pyx", line 653, in pymssql._pymssql.connect
pymssql._pymssql.OperationalError: (20002, b'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.10.253.11)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.10.253.11)\n')

### What is expected?

whyour/qinglong:debian  pymssql 2.2.10 连接数据库报错 

### What is actually happening?

whyour/qinglong:debian  pymssql 2.2.10 连接数据库报错

**Comment by unika** [comment]
修改pymssql为2.2.7版本 问题解决
