### ISSUE TITLE
docker部署的青龙突然无法启动，白屏报error

### ISSUE THREAD

**Issue by Asakushen** [whyour/qinglong#2207]
### Qinglong version

最新版（maybe）

### Steps to reproduce

前几天都用的好好的，今天想加个脚本发的进不去了，尝试过check和update 均报错Error: Cannot find module '/root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2'     MODULE_NOT_FOUND

### What is expected?

正常进入后台

### What is actually happening?

无法进入
日志如下：

root@qinglong:/ql $ ql check
## 开始执行... 2023-12-11 11:20:33

=====> 开始检测

changed 1 package in 6s
Writing to /root/.config/pip/pip.conf
Lockfile is up to date, resolution step is skipped
Already up to date
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/blessed. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/blessed/bin/tput.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/esbuild. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/esbuild/bin/esbuild does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/escodegen. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/escodegen/bin/escodegen.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/mkdirp. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/mkdirp/bin/cmd.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/needle. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/needle/bin/needle does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/resolve. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/resolve/bin/resolve does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/semver. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/semver/bin/semver.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/uuid. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/uuid/bin/uuid does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/esgenerate. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/escodegen/bin/esgenerate.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/esparse. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/esprima/bin/esparse.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/esvalidate. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/esprima/bin/esvalidate.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/yaml2json. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/yamljs/bin/yaml2json does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/json2yaml. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/yamljs/bin/json2yaml does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/node_modules/.bin/pm2. The source file at /root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2 does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/node_modules/.bin/pm2-dev. The source file at /root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2-dev does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/node_modules/.bin/pm2-docker. The source file at /root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2-docker does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/node_modules/.bin/pm2-runtime. The source file at /root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2-runtime does not exist.

Done in 6.6s
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 4, reused 1, downloaded 0, added 0
Progress: resolved 28, reused 6, downloaded 0, added 0
Progress: resolved 47, reused 13, downloaded 0, added 0
Progress: resolved 81, reused 20, downloaded 0, added 0
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 109, reused 27, downloaded 1, added 0
Progress: resolved 156, reused 28, downloaded 1, added 0
Progress: resolved 182, reused 36, downloaded 1, added 0
Packages: +1 -4
+----
Progress: resolved 182, reused 70, downloaded 1, added 1, done
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/blessed. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/blessed/bin/tput.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/esbuild. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/esbuild/bin/esbuild does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/escodegen. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/escodegen/bin/escodegen.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/mkdirp. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/mkdirp/bin/cmd.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/needle. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/needle/bin/needle does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/resolve. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/resolve/bin/resolve does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/semver. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/semver/bin/semver.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/uuid. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/uuid/bin/uuid does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/esgenerate. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/escodegen/bin/esgenerate.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/esparse. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/esprima/bin/esparse.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/esvalidate. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/esprima/bin/esvalidate.js does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/yaml2json. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/yamljs/bin/yaml2json does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/node_modules/.bin/json2yaml. The source file at /root/.local/share/pnpm/global/5/.pnpm/node_modules/yamljs/bin/json2yaml does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/global/5/.pnpm/tsx@4.6.2/node_modules/tsx/node_modules/.bin/esbuild. The source file at /root/.local/share/pnpm/global/5/.pnpm/esbuild@0.18.20/node_modules/esbuild/bin/esbuild does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/pm2. The source file at /root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2 does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/pm2-dev. The source file at /root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2-dev does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/pm2-docker. The source file at /root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2-docker does not exist.
 WARN  Failed to create bin at /root/.local/share/pnpm/pm2-runtime. The source file at /root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2-runtime does not exist.

/root/.local/share/pnpm/global/5:
- tsx 3.12.10
+ tsx 4.6.2

Done in 17.1s
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...

devDependencies: skipped

> @ postinstall /ql
> max setup 2>/dev/null || true

Done in 9s
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

安装 /ql/data/scripts 依赖包...

devDependencies: skipped

Done in 5.2s
---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="https://qn.whyour.cn/favicon.svg">
<link rel="stylesheet" href="./umi.8a0eaca6.css">
<script src="./api/env.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>
<script src="./umi.556f567f.js"></script>

</body></html>

=====> 面板服务启动正常

=====> 检测nginx服务
   68 nginx: master process nginx -c /etc/nginx/nginx.conf
   69 nginx: worker process
   70 nginx: worker process
   71 nginx: worker process
   72 nginx: worker process

=====> nginx服务正常

---> pm2日志
2023-12-01T20:13:39: ✌️ DB loaded
2023-12-01T20:13:39: ✌️ Init file down
2023-12-01T20:13:40: ✌️ Sentry loaded
2023-12-01T20:13:43: ✌️ Dependency Injector loaded
2023-12-01T20:13:44: ✌️ Express loaded
2023-12-01T20:13:44: ✌️ init data loaded
2023-12-01T20:13:45: ✌️ link deps loaded
2023-12-01T20:13:45: ✌️ init task loaded
2023-12-01T20:13:45: ✌️ 后端服务启动成功！
2023-12-02T06:03:01: ✌️ DB loaded
2023-12-02T06:03:01: ✌️ Init file down
2023-12-02T06:03:03: ✌️ Sentry loaded
2023-12-02T06:03:07: ✌️ Dependency Injector loaded
2023-12-02T06:03:08: ✌️ Express loaded
2023-12-02T06:03:09: ✌️ init data loaded
2023-12-02T06:03:09: ✌️ link deps loaded
2023-12-02T06:03:09: ✌️ init task loaded
2023-12-02T06:03:10: ✌️ 后端服务启动成功！
2023-12-03T06:02:50: ✌️ DB loaded
2023-12-03T06:02:50: ✌️ Init file down
2023-12-03T06:02:51: ✌️ Sentry loaded
2023-12-03T06:02:55: ✌️ Dependency Injector loaded
2023-12-03T06:02:56: ✌️ Express loaded
2023-12-03T06:02:58: ✌️ init data loaded
2023-12-03T06:02:58: ✌️ link deps loaded
2023-12-03T06:02:58: ✌️ init task loaded
2023-12-03T06:02:59: ✌️ 后端服务启动成功！
2023-12-04T06:02:51: ✌️ DB loaded
2023-12-04T06:02:51: ✌️ Init file down
2023-12-04T06:02:52: ✌️ Sentry loaded
2023-12-04T06:02:58: ✌️ Dependency Injector loaded
2023-12-04T06:02:58: ✌️ Express loaded
2023-12-04T06:03:00: ✌️ init data loaded
2023-12-04T06:03:00: ✌️ link deps loaded
2023-12-04T06:03:00: ✌️ init task loaded
2023-12-04T06:03:01: ✌️ 后端服务启动成功！
2023-12-05T06:02:49: ✌️ DB loaded
2023-12-05T06:02:49: ✌️ Init file down
2023-12-05T06:02:50: ✌️ Sentry loaded
2023-12-05T06:02:56: ✌️ Dependency Injector loaded
2023-12-05T06:02:57: ✌️ Express loaded
2023-12-05T06:02:59: ✌️ init data loaded
2023-12-05T06:02:59: ✌️ link deps loaded
2023-12-05T06:02:59: ✌️ init task loaded
2023-12-05T06:03:00: ✌️ 后端服务启动成功！
2023-12-06T06:03:01: ✌️ DB loaded
2023-12-06T06:03:01: ✌️ Init file down
2023-12-06T06:03:03: ✌️ Sentry loaded
2023-12-06T06:03:07: ✌️ Dependency Injector loaded
2023-12-06T06:03:08: ✌️ Express loaded
2023-12-06T06:03:09: ✌️ init data loaded
2023-12-06T06:03:10: ✌️ link deps loaded
2023-12-06T06:03:10: ✌️ init task loaded
2023-12-06T06:03:10: ✌️ 后端服务启动成功！
2023-12-07T06:02:59: ✌️ DB loaded
2023-12-07T06:02:59: ✌️ Init file down
2023-12-07T06:03:00: ✌️ Sentry loaded
2023-12-07T06:03:07: ✌️ Dependency Injector loaded
2023-12-07T06:03:07: ✌️ Express loaded
2023-12-07T06:03:09: ✌️ init data loaded
2023-12-07T06:03:10: ✌️ link deps loaded
2023-12-07T06:03:10: ✌️ init task loaded
2023-12-07T06:03:11: ✌️ 后端服务启动成功！
2023-12-08T01:24:24: ✌️ DB loaded
2023-12-08T01:24:24: ✌️ Init file down
2023-12-08T01:24:25: ✌️ Sentry loaded
2023-12-08T01:24:29: ✌️ Dependency Injector loaded
2023-12-08T01:24:29: ✌️ Express loaded
2023-12-08T01:24:31: ✌️ init data loaded
2023-12-08T01:24:31: ✌️ link deps loaded
2023-12-08T01:24:31: ✌️ init task loaded
2023-12-08T01:24:32: ✌️ 后端服务启动成功！
2023-12-08T06:03:29: ✌️ DB loaded
2023-12-08T06:03:29: ✌️ Init file down
2023-12-08T06:03:30: ✌️ Sentry loaded
2023-12-08T06:03:35: ✌️ Dependency Injector loaded
2023-12-08T06:03:36: ✌️ Express loaded
2023-12-08T06:03:37: ✌️ init data loaded
2023-12-08T06:03:37: ✌️ link deps loaded
2023-12-08T06:03:37: ✌️ init task loaded
2023-12-08T06:03:38: ✌️ 后端服务启动成功！
2023-12-09T06:03:02: ✌️ DB loaded
2023-12-09T06:03:02: ✌️ Init file down
2023-12-09T06:03:04: ✌️ Sentry loaded
2023-12-09T06:03:10: ✌️ Dependency Injector loaded
2023-12-09T06:03:10: ✌️ Express loaded
2023-12-09T06:03:11: ✌️ init data loaded
2023-12-09T06:03:12: ✌️ link deps loaded
2023-12-09T06:03:12: ✌️ init task loaded
2023-12-09T06:03:12: ✌️ 后端服务启动成功！
2023-12-10T06:03:01: ✌️ DB loaded
2023-12-10T06:03:01: ✌️ Init file down
2023-12-10T06:03:03: ✌️ Sentry loaded
2023-12-10T06:03:10: ✌️ Dependency Injector loaded
2023-12-10T06:03:10: ✌️ Express loaded
2023-12-10T06:03:12: ✌️ init data loaded
2023-12-10T06:03:12: ✌️ link deps loaded
2023-12-10T06:03:12: ✌️ init task loaded
2023-12-10T06:03:13: ✌️ 后端服务启动成功！
2023-12-01T20:13:17: Server need close, singal SIGINT
2023-12-01T20:14:38: ValidationError: The Express 'trust proxy' setting is true, which allows anyone to trivially bypass IP-based rate limiting. See https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/ for more information.
2023-12-01T20:14:38:     at Object.trustProxy (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:148:13)
2023-12-01T20:14:38:     at Object.wrappedValidations.<computed> [as trustProxy] (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:324:22)
2023-12-01T20:14:38:     at Object.keyGenerator (/ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:582:20)
2023-12-01T20:14:38:     at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:633:32
2023-12-01T20:14:38:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-01T20:14:38:     at /ql/node_modules/.pnpm/express-rate-limit@7.0.0_express@4.18.2/node_modules/express-rate-limit/dist/index.cjs:615:5 {
2023-12-01T20:14:38:   code: 'ERR_ERL_PERMISSIVE_TRUST_PROXY',
2023-12-01T20:14:38:   help: 'https://express-rate-limit.github.io/ERR_ERL_PERMISSIVE_TRUST_PROXY/'
2023-12-01T20:14:38: }

=====> 检测后台

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.17.1

=====> 检测结束

## 执行结束... 2023-12-11 11:21:31 耗时 58 秒　　　　　
root@qinglong:/ql $ ^C
root@qinglong:/ql $ ql update
## 开始执行... 2023-12-11 11:26:24

使用 github 源更新...

更新青龙源文件成功...

更新青龙静态资源成功...

开始检测依赖...

安装 /ql/.tmp/qinglong-master 依赖包...

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
.../node_modules/protobufjs postinstall$ node scripts/postinstall
.../node_modules/protobufjs postinstall: Done
.../node_modules/@whyour/sqlite3 install$ node-pre-gyp install --fallback-to-build
.../node_modules/@whyour/sqlite3 install: [@whyour/sqlite3] Success: "/ql/.tmp/qinglong-master/node_modules/.pnpm/github.com+whyour+node-sqlite3@3a00af0b5d7603b7f1b290032507320b18a6b741/node_modules/@whyour/sqlite3/lib/binding/napi-v6-linux-arm64/node_sqlite3.node" is installed via remote
.../node_modules/@whyour/sqlite3 install: Done

dependencies:
+ @grpc/grpc-js 1.8.15
+ @otplib/preset-default 12.0.1
+ @sentry/node 7.54.0
+ @sentry/tracing 7.54.0
+ body-parser 1.20.2
+ celebrate 15.0.1
+ chokidar 3.5.3
+ cors 2.8.5
+ cron-parser 4.8.1
+ cross-spawn 7.0.3
+ dayjs 1.11.8
+ dotenv 16.1.4
+ express 4.18.2
+ express-jwt 6.1.2
+ express-rate-limit 7.0.0
+ express-urlrewrite 1.4.0
+ form-data 4.0.0
+ got 11.8.6
+ hpagent 1.2.0
+ http-proxy-middleware 2.0.6
+ iconv-lite 0.6.3
+ js-yaml 4.1.0
+ jsonwebtoken 8.5.1
+ lodash 4.17.21
+ multer 1.4.4
+ nedb 1.8.0
+ node-schedule 2.1.1
+ nodemailer 6.9.3
+ p-queue-cjs 7.3.4
+ protobufjs 7.2.3
+ pstree.remy 1.1.8
+ reflect-metadata 0.1.13
+ sequelize 6.32.0
+ serve-handler 6.1.5
+ sockjs 0.3.24
+ sqlite3 <- @whyour/sqlite3 1.0.3
+ tar 6.1.15
+ toad-scheduler 1.6.1
+ typedi 0.10.0
+ uuid 8.3.2
+ winston 3.9.0
+ winston-daily-rotate-file 4.7.1
+ yargs 17.7.2

devDependencies: skipped

> @ postinstall /ql/.tmp/qinglong-master
> max setup 2>/dev/null || true

Done in 1m 2.5s

依赖检测安装成功...

更新包下载成功...
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.17.1

## 执行结束... 2023-12-11 11:28:07 耗时 103 秒　　　　　
/usr/local/bin/ql: line 568: h: command not found
/usr/local/bin/ql: line 569: syntax error near unexpected token `fi'
/usr/local/bin/ql: line 569: `  fi'
root@qinglong:/ql $

**Comment by abpbipg** [comment]
差不多报错  重装了

**Comment by Ifover** [comment]
今天又遇到了，上次瞎搞最后只能重装
这次的话，因为我是装在群晖上的所以备份了一下data文件夹。停止容器，重置容器 然后启动又正常了。
出错前的操作
1. 本地电脑运行了clash of windows，不是群晖那台就打开群晖网站的那台，平时这个软件都没有开。然后把群晖设置的代理改成了这台电脑。
2. 群晖的Container Manager 注册表切换来切换去（因为一直不行）

大概就这两步 不知道有没有影响

**Comment by xiaoheiyo** [comment]
data放外面，然后把scripts下的文件删完（删个node_modules和pack也许），然后重新docker部署就好拉，之前的部署的一下也不会有问题，nodejs的依赖可能需要重新装下，后面把这个文件一备份，有问题还原就行

**Comment by MUskby** [comment]
我也是，重新部署了

**Comment by QYG2297248353** [comment]
[解决方案](https://github.com/whyour/qinglong/issues/2229#issuecomment-1874794141)

**Comment by QYG2297248353** [comment]
#2229 @QYG2297248353 
[解决方案 【Docker安装】](https://github.com/whyour/qinglong/issues/2229#issuecomment-1874794141)

**Comment by whyour** [comment]
宿主机执行 `docker run --rm -v  /var/run/docker.sock:/var/run/docker.sock  containrrr/watchtower -cR <容器名>`
确保有映射 data 目录
