### ISSUE TITLE
重启后面板页面跳error一直启动中，更新后也不行

### ISSUE THREAD

**Issue by him95** [whyour/qinglong#2229]
### Qinglong version

2.15.*

### Steps to reproduce

-

### What is expected?

-

### What is actually happening?

root@ql:/ql $ ql update
## 开始执行... 2024-01-02 23:20:16

使用 gitee 源更新...

开始更新仓库：/ql
From https://gitee.com/whyour/qinglong
 * branch            master     -> FETCH_HEAD

更新青龙源文件成功...

开始拉取 https://gitee.com/whyour/qinglong-static.git 到 /ql/data/repo/static

Cloning into '/ql/data/repo/static'...

更新青龙静态资源成功...

重启面板中...
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.1

**Comment by QYG2297248353** [comment]
相同问题，一直没动过，自己更新了吗？！
尝试重启过，一直提示 pm2 进程守护丢失
下面日志是最后一次正常到异常的日志
```
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================2. 安装依赖========================

Writing to /root/.config/pip/pip.conf

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动pm2服务========================

[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][WARN] App schedule has option 'wait_ready' set, waiting for app to be ready...
[PM2][WARN] App public has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [schedule] launched (1 instances)
[PM2][WARN] App panel has option 'wait_ready' set, waiting for app to be ready...
[PM2] App [public] launched (1 instances)
[PM2] App [panel] launched (1 instances)
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 148      │ 5s     │ 0    │ online    │ 0%       │ 117.0mb  │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 117      │ 13s    │ 0    │ online    │ 0%       │ 93.2mb   │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 116      │ 13s    │ 0    │ online    │ 0%       │ 75.1mb   │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
====================6. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...
############################################################

crond[197]: crond (busybox 1.36.1) started, log level 8
crond[197]: USER root pid 11873 cmd no_tee=true ID=345 task 0-8-4_miui-auto-tasks_master/miuitask.py
crond[197]: USER root pid 17190 cmd no_tee=true ID=4 task RayWangQvQ_BiliBiliToolPro/bili_task_liveFansMedal.sh
crond[197]: USER root pid 23101 cmd no_tee=true ID=10 task RayWangQvQ_BiliBiliToolPro/bili_task_vipBigPoint.sh
crond[197]: USER root pid 28154 cmd no_tee=true ID=297 task QYG2297248353_ql_sign_javbus/auto_sign_javbus.py
crond[197]: USER root pid 21116 cmd no_tee=true ID=324 task QYG2297248353_py_movie_db_download/auto_download_movie_db.py
crond[197]: USER root pid 24000 cmd no_tee=true ID=305 task custom_script/link-ai-sign.py
crond[197]: USER root pid 29700 cmd no_tee=true ID=7 task RayWangQvQ_BiliBiliToolPro/bili_task_test.sh
crond[197]: USER root pid 32613 cmd no_tee=true ID=336 task QYG2297248353_py_movie_db_download/auto_down_new_movie_db.py
crond[197]: USER root pid 3027 cmd no_tee=true ID=298 task mrabit_aliyundriveDailyCheck/autoSignin.js
crond[197]: USER root pid 3028 cmd no_tee=true ID=3 task RayWangQvQ_BiliBiliToolPro/bili_task_daily.sh
crond[197]: USER root pid 9770 cmd no_tee=true ID=335 task QYG2297248353_py_movie_db_download/audo_download_movie_info_db.py
crond[197]: USER root pid 25997 cmd no_tee=true ID=5 task RayWangQvQ_BiliBiliToolPro/bili_task_liveLottery.sh
crond[197]: USER root pid 31079 cmd no_tee=true ID=2 task RayWangQvQ_BiliBiliToolPro/bili_task_base.sh
crond[197]: USER root pid 10620 cmd no_tee=true ID=347 task QYG2297248353_py_movie_db_download/auto_import_movie_db_to_sql.py
crond[197]: USER root pid 19137 cmd no_tee=true ID=345 task 0-8-4_miui-auto-tasks_master/miuitask.py
crond[197]: USER root pid 24312 cmd no_tee=true ID=4 task RayWangQvQ_BiliBiliToolPro/bili_task_liveFansMedal.sh
crond[197]: USER root pid 30217 cmd no_tee=true ID=10 task RayWangQvQ_BiliBiliToolPro/bili_task_vipBigPoint.sh
crond[197]: USER root pid 2831 cmd no_tee=true ID=297 task QYG2297248353_ql_sign_javbus/auto_sign_javbus.py
crond[197]: USER root pid 28254 cmd no_tee=true ID=324 task QYG2297248353_py_movie_db_download/auto_download_movie_db.py
crond[197]: USER root pid 31138 cmd no_tee=true ID=305 task custom_script/link-ai-sign.py
crond[197]: USER root pid 4365 cmd no_tee=true ID=7 task RayWangQvQ_BiliBiliToolPro/bili_task_test.sh
crond[197]: USER root pid 7275 cmd no_tee=true ID=336 task QYG2297248353_py_movie_db_download/auto_down_new_movie_db.py
crond[197]: USER root pid 10156 cmd no_tee=true ID=298 task mrabit_aliyundriveDailyCheck/autoSignin.js
crond[197]: USER root pid 10157 cmd no_tee=true ID=3 task RayWangQvQ_BiliBiliToolPro/bili_task_daily.sh
crond[197]: USER root pid 16904 cmd no_tee=true ID=335 task QYG2297248353_py_movie_db_download/audo_download_movie_info_db.py
crond[197]: USER root pid 440 cmd no_tee=true ID=5 task RayWangQvQ_BiliBiliToolPro/bili_task_liveLottery.sh
crond[197]: USER root pid 5510 cmd no_tee=true ID=2 task RayWangQvQ_BiliBiliToolPro/bili_task_base.sh
crond[197]: USER root pid 17490 cmd no_tee=true ID=347 task QYG2297248353_py_movie_db_download/auto_import_movie_db_to_sql.py
crond[197]: USER root pid 26012 cmd no_tee=true ID=345 task 0-8-4_miui-auto-tasks_master/miuitask.py
crond[197]: USER root pid 30696 cmd no_tee=true ID=4 task RayWangQvQ_BiliBiliToolPro/bili_task_liveFansMedal.sh
crond[197]: USER root pid 4144 cmd no_tee=true ID=10 task RayWangQvQ_BiliBiliToolPro/bili_task_vipBigPoint.sh
crond[197]: USER root pid 9209 cmd no_tee=true ID=297 task QYG2297248353_ql_sign_javbus/auto_sign_javbus.py
crond[197]: USER root pid 2173 cmd no_tee=true ID=324 task QYG2297248353_py_movie_db_download/auto_download_movie_db.py
crond[197]: USER root pid 5059 cmd no_tee=true ID=305 task custom_script/link-ai-sign.py
crond[197]: USER root pid 10763 cmd no_tee=true ID=7 task RayWangQvQ_BiliBiliToolPro/bili_task_test.sh
crond[197]: USER root pid 13670 cmd no_tee=true ID=336 task QYG2297248353_py_movie_db_download/auto_down_new_movie_db.py
crond[197]: USER root pid 16559 cmd no_tee=true ID=298 task mrabit_aliyundriveDailyCheck/autoSignin.js
crond[197]: USER root pid 16560 cmd no_tee=true ID=3 task RayWangQvQ_BiliBiliToolPro/bili_task_daily.sh
crond[197]: USER root pid 23316 cmd no_tee=true ID=335 task QYG2297248353_py_movie_db_download/audo_download_movie_info_db.py
crond[197]: USER root pid 6907 cmd no_tee=true ID=5 task RayWangQvQ_BiliBiliToolPro/bili_task_liveLottery.sh
crond[197]: USER root pid 11984 cmd no_tee=true ID=2 task RayWangQvQ_BiliBiliToolPro/bili_task_base.sh
crond[197]: USER root pid 23993 cmd no_tee=true ID=347 task QYG2297248353_py_movie_db_download/auto_import_movie_db_to_sql.py
crond[197]: USER root pid 32517 cmd no_tee=true ID=345 task 0-8-4_miui-auto-tasks_master/miuitask.py
crond[197]: USER root pid 4759 cmd no_tee=true ID=4 task RayWangQvQ_BiliBiliToolPro/bili_task_liveFansMedal.sh
crond[197]: USER root pid 10663 cmd no_tee=true ID=10 task RayWangQvQ_BiliBiliToolPro/bili_task_vipBigPoint.sh
crond[197]: USER root pid 15731 cmd no_tee=true ID=297 task QYG2297248353_ql_sign_javbus/auto_sign_javbus.py
crond[197]: USER root pid 8661 cmd no_tee=true ID=324 task QYG2297248353_py_movie_db_download/auto_download_movie_db.py
crond[197]: USER root pid 11544 cmd no_tee=true ID=305 task custom_script/link-ai-sign.py
crond[197]: USER root pid 17250 cmd no_tee=true ID=7 task RayWangQvQ_BiliBiliToolPro/bili_task_test.sh
crond[197]: USER root pid 20166 cmd no_tee=true ID=336 task QYG2297248353_py_movie_db_download/auto_down_new_movie_db.py
crond[197]: USER root pid 23050 cmd no_tee=true ID=298 task mrabit_aliyundriveDailyCheck/autoSignin.js
crond[197]: USER root pid 23051 cmd no_tee=true ID=3 task RayWangQvQ_BiliBiliToolPro/bili_task_daily.sh
crond[197]: USER root pid 29804 cmd no_tee=true ID=335 task QYG2297248353_py_movie_db_download/audo_download_movie_info_db.py
crond[197]: USER root pid 13376 cmd no_tee=true ID=5 task RayWangQvQ_BiliBiliToolPro/bili_task_liveLottery.sh
crond[197]: USER root pid 18447 cmd no_tee=true ID=2 task RayWangQvQ_BiliBiliToolPro/bili_task_base.sh
crond[197]: USER root pid 30457 cmd no_tee=true ID=347 task QYG2297248353_py_movie_db_download/auto_import_movie_db_to_sql.py
crond[197]: USER root pid 6506 cmd no_tee=true ID=345 task 0-8-4_miui-auto-tasks_master/miuitask.py
crond[197]: USER root pid 10737 cmd no_tee=true ID=8 task RayWangQvQ_BiliBiliToolPro/bili_task_tryFix.sh
crond[197]: USER root pid 10738 cmd no_tee=true ID=6 task RayWangQvQ_BiliBiliToolPro/bili_task_login.sh
crond[197]: USER root pid 11388 cmd no_tee=true ID=4 task RayWangQvQ_BiliBiliToolPro/bili_task_liveFansMedal.sh
crond[197]: USER root pid 17305 cmd no_tee=true ID=10 task RayWangQvQ_BiliBiliToolPro/bili_task_vipBigPoint.sh
crond[197]: USER root pid 22384 cmd no_tee=true ID=297 task QYG2297248353_ql_sign_javbus/auto_sign_javbus.py
crond[197]: USER root pid 15359 cmd no_tee=true ID=324 task QYG2297248353_py_movie_db_download/auto_download_movie_db.py
crond[197]: USER root pid 18248 cmd no_tee=true ID=305 task custom_script/link-ai-sign.py
crond[197]: USER root pid 23960 cmd no_tee=true ID=7 task RayWangQvQ_BiliBiliToolPro/bili_task_test.sh
crond[197]: USER root pid 26879 cmd no_tee=true ID=336 task QYG2297248353_py_movie_db_download/auto_down_new_movie_db.py
crond[197]: USER root pid 29774 cmd no_tee=true ID=298 task mrabit_aliyundriveDailyCheck/autoSignin.js
crond[197]: USER root pid 29775 cmd no_tee=true ID=3 task RayWangQvQ_BiliBiliToolPro/bili_task_daily.sh
crond[197]: USER root pid 4052 cmd no_tee=true ID=335 task QYG2297248353_py_movie_db_download/audo_download_movie_info_db.py
crond[197]: USER root pid 14447 cmd no_tee=true ID=9 task RayWangQvQ_BiliBiliToolPro/bili_task_unfollowBatched.sh
crond[197]: USER root pid 20172 cmd no_tee=true ID=5 task RayWangQvQ_BiliBiliToolPro/bili_task_liveLottery.sh
crond[197]: USER root pid 25248 cmd no_tee=true ID=2 task RayWangQvQ_BiliBiliToolPro/bili_task_base.sh
crond[197]: USER root pid 4789 cmd no_tee=true ID=347 task QYG2297248353_py_movie_db_download/auto_import_movie_db_to_sql.py
crond[197]: USER root pid 13288 cmd no_tee=true ID=345 task 0-8-4_miui-auto-tasks_master/miuitask.py
crond[197]: USER root pid 17971 cmd no_tee=true ID=4 task RayWangQvQ_BiliBiliToolPro/bili_task_liveFansMedal.sh
crond[197]: USER root pid 23887 cmd no_tee=true ID=10 task RayWangQvQ_BiliBiliToolPro/bili_task_vipBigPoint.sh
crond[197]: USER root pid 28958 cmd no_tee=true ID=297 task QYG2297248353_ql_sign_javbus/auto_sign_javbus.py
crond[197]: USER root pid 21879 cmd no_tee=true ID=324 task QYG2297248353_py_movie_db_download/auto_download_movie_db.py
crond[197]: USER root pid 24765 cmd no_tee=true ID=305 task custom_script/link-ai-sign.py
crond[197]: USER root pid 30467 cmd no_tee=true ID=7 task RayWangQvQ_BiliBiliToolPro/bili_task_test.sh
crond[197]: USER root pid 915 cmd no_tee=true ID=336 task QYG2297248353_py_movie_db_download/auto_down_new_movie_db.py
crond[197]: USER root pid 3796 cmd no_tee=true ID=298 task mrabit_aliyundriveDailyCheck/autoSignin.js
crond[197]: USER root pid 3797 cmd no_tee=true ID=3 task RayWangQvQ_BiliBiliToolPro/bili_task_daily.sh
crond[197]: USER root pid 10545 cmd no_tee=true ID=335 task QYG2297248353_py_movie_db_download/audo_download_movie_info_db.py
crond[197]: USER root pid 26584 cmd no_tee=true ID=5 task RayWangQvQ_BiliBiliToolPro/bili_task_liveLottery.sh
crond[197]: USER root pid 31650 cmd no_tee=true ID=2 task RayWangQvQ_BiliBiliToolPro/bili_task_base.sh
crond[197]: USER root pid 11188 cmd no_tee=true ID=347 task QYG2297248353_py_movie_db_download/auto_import_movie_db_to_sql.py
crond[197]: USER root pid 19694 cmd no_tee=true ID=345 task 0-8-4_miui-auto-tasks_master/miuitask.py
crond[197]: USER root pid 24882 cmd no_tee=true ID=4 task RayWangQvQ_BiliBiliToolPro/bili_task_liveFansMedal.sh
crond[197]: USER root pid 30798 cmd no_tee=true ID=10 task RayWangQvQ_BiliBiliToolPro/bili_task_vipBigPoint.sh
crond[197]: USER root pid 3397 cmd no_tee=true ID=297 task QYG2297248353_ql_sign_javbus/auto_sign_javbus.py
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================2. 安装依赖========================

Writing to /root/.config/pip/pip.conf

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动pm2服务========================

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.2
====================6. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...
############################################################

crond[106]: crond (busybox 1.36.1) started, log level 8
crond[106]: USER root pid 8799 cmd no_tee=true ID=305 task custom_script/link-ai-sign.py
crond[106]: USER root pid 13760 cmd no_tee=true ID=7 task RayWangQvQ_BiliBiliToolPro/bili_task_test.sh
crond[106]: USER root pid 18760 cmd no_tee=true ID=298 task mrabit_aliyundriveDailyCheck/autoSignin.js
crond[106]: USER root pid 18761 cmd no_tee=true ID=3 task RayWangQvQ_BiliBiliToolPro/bili_task_daily.sh
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================2. 安装依赖========================

Writing to /root/.config/pip/pip.conf

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动pm2服务========================

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.2
====================6. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...
############################################################

crond[92]: crond (busybox 1.36.1) started, log level 8
======================1. 检测配置文件========================

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
======================2. 安装依赖========================

Writing to /root/.config/pip/pip.conf

======================3. 启动nginx========================

nginx启动成功...

======================4. 启动pm2服务========================

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/root/.local/share/pnpm/global/5/node_modules/pm2/bin/pm2'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.2
====================6. 执行自定义脚本========================

自定义脚本后台执行中...

############################################################

容器启动成功...
############################################################

crond[92]: crond (busybox 1.36.1) started, log level 8
[root@centos7 ~]# docker ps -a
CONTAINER ID   IMAGE                    COMMAND                   CREATED       STATUS                     PORTS     NAMES
1af7b199bcea   whyour/qinglong:latest   "./docker/docker-ent…"   7 weeks ago   Up 2 minutes (unhealthy)             qinglong
```

**Comment by QYG2297248353** [comment]
### 解决方案 【Docker安装】
提前获取 容器名称 或 容器ID

自行查看日志，与以下问题相同
![log](https://github.com/whyour/qinglong/assets/56836951/9e4e8350-fcf4-47c7-aa5b-3942934a87ab)


> 方案1

重新安装nodejs依赖

```sh
# 进入容器
docker exec -it qinglong /bin/bash

# 进入异常目录
cd /root/.local/share/pnpm/global/5/

# 重新安装依赖
pnpm install
```
+ 至此已解决无法启动
    + 重启面板后会识别nodejs依赖，但是会存在 md5@2.x 和 jsdom -g 两个依赖无法正常安装


> 方案2

完全重新安装nodejs依赖

```sh
# 进入容器
docker exec -it qinglong /bin/bash

# 进入异常目录
cd /root/.local/share/pnpm/global/5/

# 清除历史资源
pnpm config set virtual-store-dir /root/.local/share/pnpm/global/5/.pnpm
rm -rf /root/.local/share/pnpm/global/5/.pnpm/
rm -rf /root/.local/share/pnpm/global/5/node_modules/

# 重新安装依赖
pnpm install
```
+ 完美解决

**Comment by QYG2297248353** [comment]
后续请重启容器即可

**Comment by him95** [comment]
> 后续请重启容器即可，并且数据不会丢失，python linux均不受影响，不会二次识别依赖，js脚本等待依赖完成识别后可正常运行

感谢你的解答。我昨晚实在搞不定重装了，数据倒是没丢失，但是现在脚本都报这个错误

**Comment by him95** [comment]
> 后续请重启容器即可，并且数据不会丢失，python linux均不会，不会二次识别依赖，js脚本等待依赖完成识别后可正常运行

/ql/data/scripts/node_modules/got/dist/source/create.js:14
const p_cancelable_1 = require("p-cancelable");
                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.local/share/pnpm/global/5/.pnpm/registry.npmmirror.com+p-cancelable@4.0.1/node_modules/p-cancelable/index.js from /ql/data/scripts/node_modules/got/dist/source/create.js not supported.
Instead change the require of index.js in /ql/data/scripts/node_modules/got/dist/source/create.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/ql/data/scripts/node_modules/got/dist/source/create.js:14:24)
    at Object.<anonymous> (/ql/data/scripts/node_modules/got/dist/source/index.js:14:18)
    at Object.<anonymous> (/ql/data/scripts/meituan.js:20:955) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.1

**Comment by him95** [comment]
> 后续请重启容器即可，并且数据不会丢失，python linux均不会，不会二次识别依赖，js脚本等待依赖完成识别后可正常运行

我试试你上面提到的重装pnpm

**Comment by him95** [comment]
问题已解决，写点总结，以便日后遇到类似问题的哥们。
1.我是机器意外断电，重启后发现青龙跳error界面，一直加载中。我昨晚尝试很久没办法直接重装了，如果有遇到类似问题的，可以试试上面那位老哥的方法；
2.我重装后，数据是没有丢失的，剩下的就是脚本问题了。运行脚本都是报上述1080的错误。建议重装后遇到类似问题的老哥，重装能进面板后，先跑一次ql check；
3.check之后，再根据报错安装对应缺少的依赖，我是装了六七个依赖才恢复正常的，依赖尽量安装旧版本（我全部装的2021年的）。

**Comment by AFUL1991** [comment]
> ### 解决方案 【Docker安装】
> 提前获取 容器名称 或 容器ID
> 
> 自行查看日志，与以下问题相同 ![log](https://private-user-images.githubusercontent.com/56836951/293825159-9e4e8350-fcf4-47c7-aa5b-3942934a87ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjUzMTQsIm5iZiI6MTcwNDc2NTAxNCwicGF0aCI6Ii81NjgzNjk1MS8yOTM4MjUxNTktOWU0ZTgzNTAtZmNmNC00N2M3LWFhNWItMzk0MjkzNGE4N2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAxNTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhODY1MTEzNDBhNGQzNWY3YTIyNTk3NzQxZmUxNzU3YzY1OWNkMGFiMDc5ZGIxOTk4MDQ2MjhkYmU1MzM3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UhSxfAB_HqfOZG1O1qVadi7X1ddzxC8ZGGpxMXPufcQ)
> 
> > 方案1
> 
> 重新安装nodejs依赖
> 
> ```shell
> # 进入容器
> docker exec -it qinglong /bin/bash
> 
> # 进入异常目录
> cd /root/.local/share/pnpm/global/5/
> 
> # 重新安装依赖
> pnpm install
> ```
> 
> * 至此已解决无法启动
>   
>   * 重启面板后会识别nodejs依赖，但是会存在 [md5@2.x](mailto:md5@2.x) 和 jsdom -g 两个依赖无法正常安装
> 
> > 方案2
> 
> 完全重新安装nodejs依赖
> 
> ```shell
> # 进入容器
> docker exec -it qinglong /bin/bash
> 
> # 进入异常目录
> cd /root/.local/share/pnpm/global/5/
> 
> # 清除历史资源
> pnpm config set virtual-store-dir /root/.local/share/pnpm/global/5/.pnpm
> rm -rf /root/.local/share/pnpm/global/5/.pnpm/
> rm -rf /root/.local/share/pnpm/global/5/node_modules/
> 
> # 重新安装依赖
> pnpm install
> ```
> 
> * 完美解决

非常非常非常感谢！！！！！！！
完美解决！！！！
以前我都重装，重新配置很多东西，你这个解决方案非常优雅！

**Comment by iTofu** [comment]
docker 启动的，类似的问题，上述方式还是不行。

后来我直接把 data 文件夹备份（-> data-backup）了，然后起了个新的空白 data 文件夹，启动后过完初始化流程，然后依次复制相关配置：
```bash
cp -r data-backup/config/ data/
cp -r data-backup/db/ data/
cp -r data-backup/upload/ data/
```
然后重启下容器，搞定了。

**Comment by QYG2297248353** [comment]
> docker 启动的，类似的问题，上述方式还是不行。
> 
> 后来我直接把 data 文件夹备份（-> data-backup）了，然后起了个新的空白 data 文件夹，启动后过完初始化流程，然后依次复制相关配置：
> 
> ```shell
> cp -r data-backup/config/ data/
> cp -r data-backup/db/ data/
> cp -r data-backup/upload/ data/
> ```
> 
> 然后重启下容器，搞定了。
> 
> 补充下我的这个问题出现的背景：
> 
> 用的 1panel 管理面板，备份快照后重做了个 debian 再恢复后，跑 qinglong docker 就出现了上述问题……

1Panel 建议使用 [第三方应用仓库](https://github.com/QYG2297248353/appstore-1panel) 后续升级更加方便，主要是解决持久化的问题，官方持久化路径依靠容器自身或者安装目录完成，重装升级会有覆盖的可能性，会出现一些奇奇怪怪的Bug
默认安装在 /home/qinglong 目录下 因此官方的备份无法直接备份此目录，实在需要就只能另寻他法

**Comment by ioojcn** [comment]
> ```shell
> pnpm install
> ```

大喊一声解决了.NB

**Comment by ioojcn** [comment]
> ### 解决方案 【Docker安装】
> 提前获取 容器名称 或 容器ID
> 
> 自行查看日志，与以下问题相同 ![log](https://private-user-images.githubusercontent.com/56836951/293825159-9e4e8350-fcf4-47c7-aa5b-3942934a87ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDg4MTUsIm5iZiI6MTcyOTY0ODUxNSwicGF0aCI6Ii81NjgzNjk1MS8yOTM4MjUxNTktOWU0ZTgzNTAtZmNmNC00N2M3LWFhNWItMzk0MjkzNGE4N2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAxNTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMTk4NmQ0OTI5ZTQ5MzRmZmNmMGY1ZDJlZGE5NzE1NWVmN2U1Yzg3ZmE3OTM1NmJmODcyYTVhOWNlMDE2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SUF6Y07iK83m8JTUzSJU77ROhyX7IQ5HVOWaYjC5A5c)
> 
> > 方案1
> 
> 重新安装nodejs依赖
> 
> ```shell
> # 进入容器
> docker exec -it qinglong /bin/bash
> 
> # 进入异常目录
> cd /root/.local/share/pnpm/global/5/
> 
> # 重新安装依赖
> pnpm install
> ```
> 
> * 至此已解决无法启动
>   
>   * 重启面板后会识别nodejs依赖，但是会存在 [md5@2.x](mailto:md5@2.x) 和 jsdom -g 两个依赖无法正常安装
> 
> > 方案2
> 
> 完全重新安装nodejs依赖
> 
> ```shell
> # 进入容器
> docker exec -it qinglong /bin/bash
> 
> # 进入异常目录
> cd /root/.local/share/pnpm/global/5/
> 
> # 清除历史资源
> pnpm config set virtual-store-dir /root/.local/share/pnpm/global/5/.pnpm
> rm -rf /root/.local/share/pnpm/global/5/.pnpm/
> rm -rf /root/.local/share/pnpm/global/5/node_modules/
> 
> # 重新安装依赖
> pnpm install
> ```
> 
> * 完美解决

大喊一身完美解决了!!!

**Comment by Alicute** [comment]
建议进入终端后，使用ql命令修复一下，我在修复后成功进入页面了
