### ISSUE TITLE
telegram发送通知消息失败！！但是系统通知测试又是通的

### ISSUE THREAD

**Issue by D-Jie01** [whyour/qinglong#2290]
### Qinglong version

正式版 v2.17.1

### Steps to reproduce

1、青龙任务通知tg失败
2、我在青龙系统设置里面设置的tg，测试都能通
3、然后我在配置文件都设置了代理，也不行（这个代理保证能通，因为我系统通知里面就是设置的这个。）
错误代码：
telegram发送通知消息失败！！

RequestError: Timeout awaiting 'request' for 15000ms
    at ClientRequest.<anonymous> (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:65)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:530:35)
    at origin.emit (/ql/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (/ql/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1708995601558,
    socket: 1708995601560,
    lookup: 1708995601569,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1708995616567,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 9,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 15009
    }
  },
  event: 'request'
}

### What is expected?

可通知

### What is actually happening?

如题

**Comment by whyour** [comment]
使用最新版 通知文件，在对比工具看下
