### ISSUE TITLE
【依赖安装】opencv-python 与 canvas 无法安装

### ISSUE THREAD

**Issue by QYG2297248353** [whyour/qinglong#2296]
### Qinglong version

v2.17.1

### Steps to reproduce

无法安装`opencv-python` 脚本也无法运行，缺少`cv2`
```
Traceback (most recent call last):
  File "/ql/data/scripts/xxx_xxx/main.py", line 3, in <module>
    from core.core_data_file_processing import pdf_parsing
  File "/ql/data/scripts/xxx_xxx/core/core_data_file_processing.py", line 7, in <module>
    from utils.pdf.util_pdf_parsing_excel import parse_pdf_table
  File "/ql/data/scripts/xxx_xxx/utils/pdf/util_pdf_parsing_excel.py", line 3, in <module>
    import camelot
  File "/usr/local/lib/python3.11/site-packages/camelot/__init__.py", line 6, in <module>
    from .io import read_pdf
  File "/usr/local/lib/python3.11/site-packages/camelot/io.py", line 5, in <module>
    from .handlers import PDFHandler
  File "/usr/local/lib/python3.11/site-packages/camelot/handlers.py", line 9, in <module>
    from .parsers import Stream, Lattice
  File "/usr/local/lib/python3.11/site-packages/camelot/parsers/__init__.py", line 4, in <module>
    from .lattice import Lattice
  File "/usr/local/lib/python3.11/site-packages/camelot/parsers/lattice.py", line 25, in <module>
    from ..image_processing import (
  File "/usr/local/lib/python3.11/site-packages/camelot/image_processing.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

### What is expected?

升级Python版本

### What is actually happening?

我需要安装依赖

### Any additional comments?

或者说，内置conda,允许配置不同环境

**Comment by QYG2297248353** [comment]
解决方案，挂代理，多试几次，总有一次会成功。成功概率太低
