### ISSUE TITLE
qinglong:debian 后台检查更新后404

### ISSUE THREAD

**Issue by StartMoney** [whyour/qinglong#2311]
### Qinglong version

正式版 v2.17.2

### Steps to reproduce

后台-》系统设置-》检测更新-》更新或者重新安装

### What is expected?

不正常

### What is actually happening?

更新完后刷新页面，404。
进到容器里面，执行： ql update 后才恢复正常

## 开始执行... 2024-03-20 10:04:48

=====> 开始检测
npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.5.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
npm notice Run `npm install -g npm@10.5.0` to update!
npm notice 
npm ERR! code EINVAL
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/pm2/.gitattributes
npm ERR! dest /usr/local/lib/node_modules/.pm2-0kfCfexq/.gitattributes
npm ERR! errno -22
npm ERR! EINVAL: invalid argument, rename '/usr/local/lib/node_modules/pm2/.gitattributes' -> '/usr/local/lib/node_modules/.pm2-0kfCfexq/.gitattributes'

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-03-20T02_04_48_645Z-debug-0.log
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...

devDependencies: skipped

> @whyour/qinglong@0.16.0 postinstall /ql
> max setup 2>/dev/null || true

Done in 3.1s

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.3.1 → 8.15.5.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.15.5   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

---> 青龙依赖安装完成

---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

=====> 检测nginx服务
   48 nginx: master process nginx -c /etc/nginx/nginx.conf
   49 nginx: worker process
   50 nginx: worker process
   51 nginx: worker process
   52 nginx: worker process

=====> nginx服务正常

---> pm2日志
2024-03-20T09:55:37: }
2024-03-20T09:55:37: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:37:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:37:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:37:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:37:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:37:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:37:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:37:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:37:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:37:   requireStack: []
2024-03-20T09:55:37: }
2024-03-20T09:55:37: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:37:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:37:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:37:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:37:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:37:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:37:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:37:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:37:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:37:   requireStack: []
2024-03-20T09:55:37: }
2024-03-20T09:55:38: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:38:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:38:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:38:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:38:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:38:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:38:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:38:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:38:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:38:   requireStack: []
2024-03-20T09:55:38: }
2024-03-20T09:55:38: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:38:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:38:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:38:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:38:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:38:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:38:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:38:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:38:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:38:   requireStack: []
2024-03-20T09:55:38: }
2024-03-20T09:55:39: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:39:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:39:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:39:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:39:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:39:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:39:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:39:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:39:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:39:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:39:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:39:   requireStack: []
2024-03-20T09:55:39: }
2024-03-20T09:55:39: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:39:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:39:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:39:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:39:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:39:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:39:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:39:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:39:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:39:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:39:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:39:   requireStack: []
2024-03-20T09:55:39: }
2024-03-20T09:55:40: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:40:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:40:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:40:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:40:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:40:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:40:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:40:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:40:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:40:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:40:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:40:   requireStack: []
2024-03-20T09:55:40: }
2024-03-20T09:55:41: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:41:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:41:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:41:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:41:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:41:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:41:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:41:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:41:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:41:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:41:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:41:   requireStack: []
2024-03-20T09:55:41: }
2024-03-20T09:55:41: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:41:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:41:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:41:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:41:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:41:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:41:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:41:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:41:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:41:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:41:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:41:   requireStack: []
2024-03-20T09:55:41: }
2024-03-20T09:55:42: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:42:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:42:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:42:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:42:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:42:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:42:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:42:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:42:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:42:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:42:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:42:   requireStack: []
2024-03-20T09:55:42: }
2024-03-20T09:55:42: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:42:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:42:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:42:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:42:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:42:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:42:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:42:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:42:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:42:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:42:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:42:   requireStack: []
2024-03-20T09:55:42: }
2024-03-20T09:55:43: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:43:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:43:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:43:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:43:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:43:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:43:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:43:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:43:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:43:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:43:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:43:   requireStack: []
2024-03-20T09:55:43: }
2024-03-20T09:55:43: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:43:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:43:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:43:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:43:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:43:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:43:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:43:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:43:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:43:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:43:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:43:   requireStack: []
2024-03-20T09:55:43: }
2024-03-20T09:55:44: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:44:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:44:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:44:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:44:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:44:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:44:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:44:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:44:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:44:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:44:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:44:   requireStack: []
2024-03-20T09:55:44: }
2024-03-20T09:55:44: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:44:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:44:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:44:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:44:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:44:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:44:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:44:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:44:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:44:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:44:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:44:   requireStack: []
2024-03-20T09:55:44: }
2024-03-20T09:55:45: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:45:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:45:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:45:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:45:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:45:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:45:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:45:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:45:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:45:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:45:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:45:   requireStack: []
2024-03-20T09:55:45: }
2024-03-20T09:55:45: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:45:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:45:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:45:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:45:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:45:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:45:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:45:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:45:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:45:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:45:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:45:   requireStack: []
2024-03-20T09:55:45: }
2024-03-20T09:55:46: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:46:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:46:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:46:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:46:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:46:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:46:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:46:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:46:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:46:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:46:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:46:   requireStack: []
2024-03-20T09:55:46: }
2024-03-20T09:55:46: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:46:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:46:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:46:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:46:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:46:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:46:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:46:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:46:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:46:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:46:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:46:   requireStack: []
2024-03-20T09:55:46: }
2024-03-20T09:55:47: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:47:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:47:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:47:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:47:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:47:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:47:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:47:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:47:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:47:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:47:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:47:   requireStack: []
2024-03-20T09:55:47: }
2024-03-20T09:55:47: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:47:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:47:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:47:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:47:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:47:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:47:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:47:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:47:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:47:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:47:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:47:   requireStack: []
2024-03-20T09:55:47: }
2024-03-20T09:55:48: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:48:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:48:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:48:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:48:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:48:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:48:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:48:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:48:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:48:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:48:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:48:   requireStack: []
2024-03-20T09:55:48: }
2024-03-20T09:55:48: Error: Cannot find module '/ql/static/build/app.js'
2024-03-20T09:55:48:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
2024-03-20T09:55:48:     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
2024-03-20T09:55:48:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2024-03-20T09:55:48:     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-03-20T09:55:48:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-03-20T09:55:48:     at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-03-20T09:55:48:     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
2024-03-20T09:55:48:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
2024-03-20T09:55:48:     at node:internal/main/run_main_module:28:49 {
2024-03-20T09:55:48:   code: 'MODULE_NOT_FOUND',
2024-03-20T09:55:48:   requireStack: []
2024-03-20T09:55:48: }

=====> 检测后台

[PM2][WARN] Applications schedule, public, panel not running, starting...
[PM2][ERROR] Error: Script not found: /ql/static/build/schedule/index.js
[PM2][ERROR] Error: Script not found: /ql/static/build/public.js
[PM2][ERROR] Error: Script not found: /ql/static/build/app.js

=====> 检测结束

**Comment by whyour** [comment]
下个版本修复

**Comment by whyour** [comment]
2.17.3 已修复
