### ISSUE TITLE
Couldn't update after restarting, seems to be due to lack of dependencies?

### ISSUE THREAD

**Issue by s7lx** [whyour/qinglong#2333]
### Qinglong version

lastest ( update recently ）

### Steps to reproduce

1. ql update
2. ql check

### What is expected?

Expecting proper execution.

### What is actually happening?

root@qinglong:/ql $ ql check
## 开始执行... 2024-04-10 17:10:59

=====> 开始检测

changed 1 package in 491ms
检测到旧的db目录，拷贝到data目录...

检测到旧的scripts目录，拷贝到data目录...

检测到旧的log目录，拷贝到data目录...

检测到旧的config目录，拷贝到data目录...

OK: 139 MiB in 82 packages
Writing to /root/.config/pip/pip.conf
Recreating /root/.local/share/pnpm/global/5/node_modules
Lockfile is up to date, resolution step is skipped
Already up to date

/root/.local/share/pnpm/global/5:
+ axios 1.6.8
+ crypto-js 4.2.0
+ date-fns 3.6.0
+ jsdom 24.0.0
+ node-rsa 1.1.1
+ pm2 5.3.1
+ request 2.88.2
+ tsx 4.7.2

Done in 915ms
Progress: resolved 0, reused 1, downloaded 0, added 0
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  deprecated har-validator@5.1.5: this library is no longer supported
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 269, reused 246, downloaded 0, added 0
 WARN  deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
Already up to date

Done in 2s
Progress: resolved 287, reused 264, downloaded 0, added 0, done
---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

安装 /ql 依赖包...

devDependencies: skipped

> @ postinstall /ql
> max setup 2>/dev/null || true

Done in 746ms
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

安装 /ql/data/scripts 依赖包...

devDependencies: skipped

Done in 453ms
---> 脚本依赖安装完成

---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/data/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/data/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/data/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/data/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="shortcut icon" href="https://qn.whyour.cn/favicon.svg">
<link rel="stylesheet" href="./umi.8a0eaca6.css">
<script src="./api/env.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://gw.alipayobjects.com/os/lib/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
</head>
<body>
<div id="root"></div>
<script src="./umi.a237342f.js"></script>

</body></html>

=====> 面板服务启动正常

=====> 检测nginx服务
     47 nginx: master process nginx -c /etc/nginx/nginx.conf
  18493 nginx: worker process
  18494 nginx: worker process

=====> nginx服务正常

---> pm2日志
2024-04-10T17:07:37: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:37: Require stack:
2024-04-10T17:07:37: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:37: - /ql/static/build/app.js
2024-04-10T17:07:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:37:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:37:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:37:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:37:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:37:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:37:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:37:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:37:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:37: }
2024-04-10T17:07:37: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:37: Require stack:
2024-04-10T17:07:37: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:37: - /ql/static/build/app.js
2024-04-10T17:07:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:37:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:37:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:37:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:37:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:37:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:37:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:37:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:37:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:37: }
2024-04-10T17:07:37: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:37: Require stack:
2024-04-10T17:07:37: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:37: - /ql/static/build/app.js
2024-04-10T17:07:37:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:37:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:37:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:37:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:37:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:37:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:37:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:37:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:37:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:37:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:37:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:37: }
2024-04-10T17:07:38: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:38: Require stack:
2024-04-10T17:07:38: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:38: - /ql/static/build/app.js
2024-04-10T17:07:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:38:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:38:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:38:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:38:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:38:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:38:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:38:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:38:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:38: }
2024-04-10T17:07:38: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:38: Require stack:
2024-04-10T17:07:38: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:38: - /ql/static/build/app.js
2024-04-10T17:07:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:38:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:38:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:38:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:38:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:38:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:38:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:38:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:38:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:38: }
2024-04-10T17:07:38: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:38: Require stack:
2024-04-10T17:07:38: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:38: - /ql/static/build/app.js
2024-04-10T17:07:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:38:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:38:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:38:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:38:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:38:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:38:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:38:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:38:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:38: }
2024-04-10T17:07:38: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:38: Require stack:
2024-04-10T17:07:38: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:38: - /ql/static/build/app.js
2024-04-10T17:07:38:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:38:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:38:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:38:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:38:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:38:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:38:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:38:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:38:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:38:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:38:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:38: }
2024-04-10T17:07:39: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:39: Require stack:
2024-04-10T17:07:39: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:39: - /ql/static/build/app.js
2024-04-10T17:07:39:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:39:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:39:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:39:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:39:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:39:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:39:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:39:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:39:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:39:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:39:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:39:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:39: }
2024-04-10T17:07:39: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:39: Require stack:
2024-04-10T17:07:39: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:39: - /ql/static/build/app.js
2024-04-10T17:07:39:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:39:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:39:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:39:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:39:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:39:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:39:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:39:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:39:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:39:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:39:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:39:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:39: }
2024-04-10T17:07:39: Error: Cannot find module 'winston-daily-rotate-file'
2024-04-10T17:07:39: Require stack:
2024-04-10T17:07:39: - /ql/static/build/loaders/logger.js
2024-04-10T17:07:39: - /ql/static/build/app.js
2024-04-10T17:07:39:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2024-04-10T17:07:39:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:81:25)
2024-04-10T17:07:39:     at require (node:internal/modules/cjs/helpers:110:18)
2024-04-10T17:07:39:     at Object.<anonymous> (/ql/back/loaders/logger.ts:2:1)
2024-04-10T17:07:39:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2024-04-10T17:07:39:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2024-04-10T17:07:39:     at Module.load (node:internal/modules/cjs/loader:1117:32)
2024-04-10T17:07:39:     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
2024-04-10T17:07:39:     at Module.require (node:internal/modules/cjs/loader:1141:19)
2024-04-10T17:07:39:     at Module.Hook._require.Module.require (/root/.local/share/pnpm/global/5/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39) {
2024-04-10T17:07:39:   code: 'MODULE_NOT_FOUND',
2024-04-10T17:07:39:   requireStack: [ '/ql/static/build/loaders/logger.js', '/ql/static/build/app.js' ]
2024-04-10T17:07:39: }

=====> 检测后台

[PM2] Applying action reloadProcessId on app [schedule](ids: [ 0 ])
[PM2] Applying action reloadProcessId on app [public](ids: [ 1 ])
[PM2] [schedule](0) ✓
[PM2] [public](1) ✓
[PM2] Applying action reloadProcessId on app [panel](ids: [ 2 ])
[PM2] [panel](2) ✓
┌────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 2  │ panel       │ default     │ N/A     │ fork    │ 0        │ 0      │ 650  │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 1  │ public      │ default     │ N/A     │ fork    │ 0        │ 0      │ 64   │ errored   │ 0%       │ 0b       │ root     │ disabled │
│ 0  │ schedule    │ default     │ N/A     │ fork    │ 0        │ 0      │ 64   │ errored   │ 0%       │ 0b       │ root     │ disabled │
└────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

=====> 检测结束

### Any additional comments?
had run ```docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <container ID>```

**Comment by s7lx** [comment]
@whyour 能否看看。遵照之前的解决方法，并没得到解决

**Comment by whyour** [comment]
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR <container ID>` 没更新成功吧，删除容器、镜像，更新镜像重建下
