### ISSUE TITLE
新版本无法用host模式进入面板

### ISSUE THREAD

**Issue by Misaka09982** [whyour/qinglong#2349]
### Qinglong version

qinglong:python3.10

### Steps to reproduce

用host模式是面板报错，改用bridge成功进入面板

### What is expected?

希望修复host模式

### What is actually happening?

2024-04-27T20:29:56: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:29:56: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:29:56: at listenInCluster (node:net:1945:12)
2024-04-27T20:29:56: at Server.listen (node:net:2037:7)
2024-04-27T20:29:56: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:29:56: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:29:56: code: 'EADDRINUSE',
2024-04-27T20:29:56: errno: -98,
2024-04-27T20:29:56: syscall: 'listen',
2024-04-27T20:29:56: address: '::',
2024-04-27T20:29:56: port: 5600,
2024-04-27T20:29:56: level: 'error',
2024-04-27T20:29:56: [Symbol(level)]: 'error',
2024-04-27T20:29:56: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:29:56: }
2024-04-27T20:30:04: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:30:04: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:30:04: at listenInCluster (node:net:1945:12)
2024-04-27T20:30:04: at Server.listen (node:net:2037:7)
2024-04-27T20:30:04: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:30:04: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:30:04: code: 'EADDRINUSE',
2024-04-27T20:30:04: errno: -98,
2024-04-27T20:30:04: syscall: 'listen',
2024-04-27T20:30:04: address: '::',
2024-04-27T20:30:04: port: 5600,
2024-04-27T20:30:04: level: 'error',
2024-04-27T20:30:04: [Symbol(level)]: 'error',
2024-04-27T20:30:04: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:30:04: }
2024-04-27T20:30:11: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:30:11: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:30:11: at listenInCluster (node:net:1945:12)
2024-04-27T20:30:11: at Server.listen (node:net:2037:7)
2024-04-27T20:30:11: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:30:11: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:30:11: code: 'EADDRINUSE',
2024-04-27T20:30:11: errno: -98,
2024-04-27T20:30:11: syscall: 'listen',
2024-04-27T20:30:11: address: '::',
2024-04-27T20:30:11: port: 5600,
2024-04-27T20:30:11: level: 'error',
2024-04-27T20:30:11: [Symbol(level)]: 'error',
2024-04-27T20:30:11: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:30:11: }
2024-04-27T20:30:19: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:30:19: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:30:19: at listenInCluster (node:net:1945:12)
2024-04-27T20:30:19: at Server.listen (node:net:2037:7)
2024-04-27T20:30:19: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:30:19: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:30:19: code: 'EADDRINUSE',
2024-04-27T20:30:19: errno: -98,
2024-04-27T20:30:19: syscall: 'listen',
2024-04-27T20:30:19: address: '::',
2024-04-27T20:30:19: port: 5600,
2024-04-27T20:30:19: level: 'error',
2024-04-27T20:30:19: [Symbol(level)]: 'error',
2024-04-27T20:30:19: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:30:19: }
2024-04-27T20:30:27: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:30:27: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:30:27: at listenInCluster (node:net:1945:12)
2024-04-27T20:30:27: at Server.listen (node:net:2037:7)
2024-04-27T20:30:27: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:30:27: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:30:27: code: 'EADDRINUSE',
2024-04-27T20:30:27: errno: -98,
2024-04-27T20:30:27: syscall: 'listen',
2024-04-27T20:30:27: address: '::',
2024-04-27T20:30:27: port: 5600,
2024-04-27T20:30:27: level: 'error',
2024-04-27T20:30:27: [Symbol(level)]: 'error',
2024-04-27T20:30:27: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:30:27: }
2024-04-27T20:30:35: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:30:35: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:30:35: at listenInCluster (node:net:1945:12)
2024-04-27T20:30:35: at Server.listen (node:net:2037:7)
2024-04-27T20:30:35: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:30:35: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:30:35: code: 'EADDRINUSE',
2024-04-27T20:30:35: errno: -98,
2024-04-27T20:30:35: syscall: 'listen',
2024-04-27T20:30:35: address: '::',
2024-04-27T20:30:35: port: 5600,
2024-04-27T20:30:35: level: 'error',
2024-04-27T20:30:35: [Symbol(level)]: 'error',
2024-04-27T20:30:35: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:30:35: }
2024-04-27T20:30:42: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:30:42: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:30:42: at listenInCluster (node:net:1945:12)
2024-04-27T20:30:42: at Server.listen (node:net:2037:7)
2024-04-27T20:30:42: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:30:42: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:30:42: code: 'EADDRINUSE',
2024-04-27T20:30:42: errno: -98,
2024-04-27T20:30:42: syscall: 'listen',
2024-04-27T20:30:42: address: '::',
2024-04-27T20:30:42: port: 5600,
2024-04-27T20:30:42: level: 'error',
2024-04-27T20:30:42: [Symbol(level)]: 'error',
2024-04-27T20:30:42: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:30:42: }
2024-04-27T20:30:48: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:30:48: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:30:48: at listenInCluster (node:net:1945:12)
2024-04-27T20:30:48: at Server.listen (node:net:2037:7)
2024-04-27T20:30:48: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:30:48: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:30:48: code: 'EADDRINUSE',
2024-04-27T20:30:48: errno: -98,
2024-04-27T20:30:48: syscall: 'listen',
2024-04-27T20:30:48: address: '::',
2024-04-27T20:30:48: port: 5600,
2024-04-27T20:30:48: level: 'error',
2024-04-27T20:30:48: [Symbol(level)]: 'error',
2024-04-27T20:30:48: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:30:48: }
2024-04-27T20:30:56: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:30:56: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:30:56: at listenInCluster (node:net:1945:12)
2024-04-27T20:30:56: at Server.listen (node:net:2037:7)
2024-04-27T20:30:56: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:30:56: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:30:56: code: 'EADDRINUSE',
2024-04-27T20:30:56: errno: -98,
2024-04-27T20:30:56: syscall: 'listen',
2024-04-27T20:30:56: address: '::',
2024-04-27T20:30:56: port: 5600,
2024-04-27T20:30:56: level: 'error',
2024-04-27T20:30:56: [Symbol(level)]: 'error',
2024-04-27T20:30:56: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:30:56: }
2024-04-27T20:31:04: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:31:04: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:31:04: at listenInCluster (node:net:1945:12)
2024-04-27T20:31:04: at Server.listen (node:net:2037:7)
2024-04-27T20:31:04: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:31:04: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:31:04: code: 'EADDRINUSE',
2024-04-27T20:31:04: errno: -98,
2024-04-27T20:31:04: syscall: 'listen',
2024-04-27T20:31:04: address: '::',
2024-04-27T20:31:04: port: 5600,
2024-04-27T20:31:04: level: 'error',
2024-04-27T20:31:04: [Symbol(level)]: 'error',
2024-04-27T20:31:04: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:31:04: }
2024-04-27T20:31:10: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:31:10: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:31:10: at listenInCluster (node:net:1945:12)
2024-04-27T20:31:10: at Server.listen (node:net:2037:7)
2024-04-27T20:31:10: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:31:10: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:31:10: code: 'EADDRINUSE',
2024-04-27T20:31:10: errno: -98,
2024-04-27T20:31:10: syscall: 'listen',
2024-04-27T20:31:10: address: '::',
2024-04-27T20:31:10: port: 5600,
2024-04-27T20:31:10: level: 'error',
2024-04-27T20:31:10: [Symbol(level)]: 'error',
2024-04-27T20:31:10: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:31:10: }
2024-04-27T20:31:16: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:31:16: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:31:16: at listenInCluster (node:net:1945:12)
2024-04-27T20:31:16: at Server.listen (node:net:2037:7)
2024-04-27T20:31:16: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:31:16: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:31:16: code: 'EADDRINUSE',
2024-04-27T20:31:16: errno: -98,
2024-04-27T20:31:16: syscall: 'listen',
2024-04-27T20:31:16: address: '::',
2024-04-27T20:31:16: port: 5600,
2024-04-27T20:31:16: level: 'error',
2024-04-27T20:31:16: [Symbol(level)]: 'error',
2024-04-27T20:31:16: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:31:16: }
2024-04-27T20:31:24: Error: listen EADDRINUSE: address already in use :::5600
2024-04-27T20:31:24: at Server.setupListenHandle [as _listen2] (node:net:1897:16)
2024-04-27T20:31:24: at listenInCluster (node:net:1945:12)
2024-04-27T20:31:24: at Server.listen (node:net:2037:7)
2024-04-27T20:31:24: at Function.listen (/ql/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/application.js:635:24)
2024-04-27T20:31:24: at startServer (/ql/back/app.ts:18:6) {
2024-04-27T20:31:24: code: 'EADDRINUSE',
2024-04-27T20:31:24: errno: -98,
2024-04-27T20:31:24: syscall: 'listen',
2024-04-27T20:31:24: address: '::',
2024-04-27T20:31:24: port: 5600,
2024-04-27T20:31:24: level: 'error',
2024-04-27T20:31:24: [Symbol(level)]: 'error',
2024-04-27T20:31:24: [Symbol(message)]: '{"address":"::","code":"EADDRINUSE","errno":-98,"level":"error","port":5600,"syscall":"listen"}'
2024-04-27T20:31:24: }
这是面板报错
![image](https://github.com/whyour/qinglong/assets/41320755/bfe72139-8f3c-4fb6-9a48-66eeb4a5cddf)

**Comment by whyour** [comment]
这提示是端口已经占用了，host模式 多容器要使用 -e QlPort="5700" 指定不同的端口
