### ISSUE TITLE
bark通知一直出错

### ISSUE THREAD

**Issue by stvenshaw** [whyour/qinglong#2364]
### Qinglong version

2.17.4

### Steps to reproduce

bark 服务启动
Exception in thread bark:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/notify.py", line 158, in bark
    response = requests.get(url).json()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### What is expected?

这是要用旧版的通知文件吗，还是替换什么文件

### What is actually happening?

仓库订阅之类的bark推送能收到，定时任务的bark推送就收不到

**Comment by stvenshaw** [comment]
========================

 v2.1.1 开源 by https://github.com/RayWangQvQ/BiliBiliToolPro

[02:15:20 INF] ·开始推送·VipBigPoint任务·
[02:15:20 INF] 运行环境：Production
[02:15:20 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[02:15:20 INF] 运行结束

## 执行结束... 2024-05-14 02:15:21  耗时 188 秒　　　　　



另一个定时任务也是这样，显示开始推送，但手机端bark就是没收到

**Comment by whyour** [comment]
上面换最新的通知文件试试，看不到你通知的内容，无法判断是什么问题
下面的通知用的不是青龙的通知文件
