### ISSUE TITLE
面板内python运行selenium库会报错，直接docker内运行则正常

### ISSUE THREAD

**Issue by little6neko** [whyour/qinglong#2367]
### Qinglong version

2.17.4

### Steps to reproduce

Python依赖已安装selenium，Linux依赖已安装chromium和chromium-chromedriver
定时任务添加python脚本运行，脚本调用selenium库，会报错
使用docker exec -it qinglong bash进入容器，再python3 xxx.py则能正常运行

### What is expected?

N/A

### What is actually happening?

报错如下：错误信息看不全，不知道什么原因
Traceback (most recent call last):
  File "/ql/data/scripts/uu-gg-sign.py", line 28, in <module>
    driver = webdriver.Chrome(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message:

**Comment by little6neko** [comment]
已解决，selenium使用代理环境变量会报错

**Comment by Ohihahaha** [comment]
你好,请问你的带selenium的脚本能稳定运行吗,我这里测试代码能跑但是复杂一点的就报错,方便交流一下吗

**Comment by little6neko** [comment]
> 你好,请问你的带selenium的脚本能稳定运行吗,我这里测试代码能跑但是复杂一点的就报错,方便交流一下吗

docker反应慢一点，time.sleep要给大，比如在本地测试5秒的，docker那边最好给10秒以上，我遇到报错基本这样能解决
