### ISSUE TITLE
2.17.8和2.17.9中ts脚本中引入自定义模块报错

### ISSUE THREAD

**Issue by Firfr** [whyour/qinglong#2455]
### Qinglong version

2.17.8,2.17.9

### Steps to reproduce

下面语句报错
import { fnGet请求, fnGet请求_代理, fnGotify请求 } from './工具/请求.ts';
是在docker镜像从2.17.7升级到2.17.8和2.17.9这两个版本后发生的错误,在2.17.7和之前版本能正常运行,镜像版本退回到2.17.7之后,报错消失

### What is expected?

如何解决

### What is actually happening?

具体报错如下
## 开始执行... 2024-08-03 21:20:03

Error: Cannot find module 'tslib'
Require stack:
- /ql/data/scripts/0-我的任务/docker.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/usr/local/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/ql/data/scripts/0-我的任务/docker.ts:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/0-我的任务/docker.ts' ]
}

**Comment by whyour** [comment]
你的目录是有 tsconfig.json 文件？还是引用了什么 importHelp ?

**Comment by ydz777** [comment]
![image](https://github.com/user-attachments/assets/04319f3c-8c3c-4d2d-9c94-3b6afa48edaa)
佬 为啥要改这块呀
改了项目  package.json 配置  "type": "module", 后 就不识别.ts文件了

**Comment by whyour** [comment]
> ![image](https://private-user-images.githubusercontent.com/67778879/355031479-04319f3c-8c3c-4d2d-9c94-3b6afa48edaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTE4NzQsIm5iZiI6MTcyMjg1MTU3NCwicGF0aCI6Ii82Nzc3ODg3OS8zNTUwMzE0NzktMDQzMTlmM2MtOGMzYy00ZDJkLTljOTQtM2I2YWZhNDhlZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA5NTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0N2MyNmE5ZjI1YmUxOTYzYzczMjM5ZWUwMGUyMTNlZmRiMzdiNmVlNTNiNzgwZjVlODA0MWU1OGNkZmM3MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CkqSuphwJ0QDTV7Iro1qaPCkt9UciXNB0NvF_UgNo2s) 佬 为啥要改这块呀 改了项目 package.json 配置 "type": "module", 后 就不识别.ts文件了

tsx 执行有大环境变量的文件会报错，ts 文件为什么要加 type: module ?
