### ISSUE TITLE
无法连接chromedriver

### ISSUE THREAD

**Issue by huoshenw** [whyour/qinglong#2502]
### Qinglong version

2.17.11

### Steps to reproduce

[21:50:26 INFO] 启动 Selenium
[21:50:26 INFO] 初始化完成
Traceback (most recent call last):
  File "/ql/data/scripts/WowYiJiu_Linux.do-KeepAlive_main/Linux.do.py", line 459, in <module>
    linuxdo_browser.run()
  File "/ql/data/scripts/WowYiJiu_Linux.do-KeepAlive_main/Linux.do.py", line 266, in run
    self.driver = webdriver.Chrome(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 109, in start
    raise WebDriverException(f"Can not connect to the Service {self._path}")
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /usr/bin/chromedriver

### What is expected?

如何配置

### What is actually happening?

[21:50:26 INFO] 启动 Selenium
[21:50:26 INFO] 初始化完成
Traceback (most recent call last):
  File "/ql/data/scripts/WowYiJiu_Linux.do-KeepAlive_main/Linux.do.py", line 459, in <module>
    linuxdo_browser.run()
  File "/ql/data/scripts/WowYiJiu_Linux.do-KeepAlive_main/Linux.do.py", line 266, in run
    self.driver = webdriver.Chrome(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 109, in start
    raise WebDriverException(f"Can not connect to the Service {self._path}")
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /usr/bin/chromedriver

**Comment by whyour** [comment]
使用 whyour/qinglong:debain 镜像
