### ISSUE TITLE
页面点击运行任务正常，但是通过task path now出错

### ISSUE THREAD

**Issue by rollky** [whyour/qinglong#2518]
### Qinglong version

2.17.9

### Steps to reproduce

通过订阅拉取仓库，在定时任务页面点击运行，脚本正常运行，但是通过 task path now 来运行脚本出错。

### What is expected?

root@qinglong:/ql/data/scripts/9Rebels_jdmax $ task /ql/data/scripts/9Rebels_jdmax/jd_wxCollectionActivity.js now
## 开始执行... 2024-09-28 08:33:59

node:fs:1372
  const result = binding.mkdir(
                         ^

Error: ENOENT: no such file or directory, mkdir './utils/prize'
    at Object.mkdirSync (node:fs:1372:26)
    at Object.<anonymous> (/ql/data/scripts/9Rebels_jdmax/utils/Rebels_savePrize.js:5:3115)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/ql/data/scripts/9Rebels_jdmax/jd_wxCollectionActivity.js:19:1554)
    at Module._compile (node:internal/modules/cjs/loader:1358:14) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: './utils/prize'
}

Node.js v20.15.1

## 开始执行... 2024-09-28 08:35:39

初始化奖品记录文件成功

==========加购有礼（超级无线/超级会员）变量说明==========
jd_wxCollectionActivity_activityUrl // 活动链接
jd_wxCollectionActivity_opencard // 是否入会（true/false），默认不入会
==========加购有礼（超级无线/超级会员）提示结束==========

活动入口：https://cjhy-isv.isvjcloud.com/wxCollectionActivity/activity?activityId=f2e29b6157f5429b9719db3a55d51a5d

******开始【账号1】******

活动已结束

🔔加购有礼（超级无线/超级会员）, 结束! 🕛 4.207 秒

**Comment by whyour** [comment]
脚本使用问题
