### ISSUE TITLE
脚本运行报错，开始提示Error: Cannot find module 'tough-cookie'

### ISSUE THREAD

**Issue by MangoDong** [whyour/qinglong#252]
Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.initGotEnv (/ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:321:3721)
    at Object.get (/ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:321:4492)
    at /ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:114:7
    at new Promise (<anonymous>)
    at gambleHomePage (/ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:113:10)
    at main (/ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:75:11)
之前正常使用v3  但是 第一次使用青龙报错 求大佬给解答一下。

**Comment by MangoDong** [comment]
找不到模块的问题

**Comment by MangoDong** [comment]
`Error: Cannot find module 'tough-cookie'
Require stack:
- /ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.initGotEnv (/ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:321:3721)
    at Object.get (/ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:321:4492)
    at /ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:114:7
    at new Promise (<anonymous>)
    at gambleHomePage (/ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:113:10)
    at main (/ql/scripts/chinnkarahoi_jd_scripts_jd_big_winner.js:75:11)
`

**Comment by MangoDong** [comment]
我先拉取的备份仓库是
ql repo https://ghproxy.com/https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"

但是里面的报错，找不到。

**Comment by MangoDong** [comment]
然后自定义脚本了

#!/usr/bin/env bash

## 添加你需要重启自动执行的任意命令，比如 ql repo
ql repo https://ghproxy.com/https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"

ql repo https://ghproxy.com/https://github.com/monk-coder/dust.git "i-chenzhe|normal|member|car" "backup"

ql repo https://ghproxy.com/https://github.com/nianyuguai/longzhuzhu.git "qx"

ql repo https://ghproxy.com/https://github.com/whyour/hundun.git "quanx" "tokens|caiyun|didi|donate|fold|Env"

ql raw https://ghproxy.com/https://raw.githubusercontent.com/moposmall/Script/main/Me/jx_cfd.js

**Comment by MangoDong** [comment]
重复删掉脚本和容器，还是报错

**Comment by MangoDong** [comment]
看了一下目录下面，有这个模块，调用失败。

**Comment by whyour** [comment]
> 看了一下目录下面，有这个模块，调用失败。

删除scripts下的package.json 然后执行ql update

**Comment by MangoDong** [comment]
顺利解决。

**Comment by woboo110** [comment]
> > 看了一下目录下面，有这个模块，调用失败。
> 
> 删除scripts下的package.json 然后执行ql update

按照这个执行后，还是不行。。。
