### ISSUE TITLE
面板更新提示 ERR_INVALID_THIS  Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by sdgsgsdf** [whyour/qinglong#2525]
### Qinglong version

2.17.9

### Steps to reproduce

ql update

### What is expected?

正常更新

### What is actually happening?

使用 github 源更新...

更新青龙源文件成功...

更新青龙静态资源成功...

开始检测依赖...

安装 /ql/.tmp/qinglong-master 依赖包...

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
 ERR_INVALID_THIS  Value of "this" must be of type URLSearchParams

pnpm [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at Proxy.getAll (node:internal/url:535:13)
    at Proxy.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:59405:55)
    at /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:59467:31
    at Array.reduce (<anonymous>)
    at Proxy.raw (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:59466:33)
    at new Headers (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:59351:28)
    at getNodeRequestOptions (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:59700:23)
    at /usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:59757:25
    at new Promise (<anonymous>)
    at fetch (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:59755:14)

依赖检测安装失败，请检查网络...

**Comment by whyour** [comment]
这是 docker 部署的吗

**Comment by whyour** [comment]
> zerotermux

是用 docker run  还是 npm i @whyour/qinglong 装的

**Comment by Joackk** [comment]
> > zerotermux
> 
> 是用 docker run 还是 npm i @whyour/qinglong 装的

应该算是第二种?我是直接导入的就是别人做好的容器，更新时候就是ql update、ql check这种命令来运行的
