### ISSUE TITLE
脚本调用tg通知失败

### ISSUE THREAD

**Issue by FYboss** [whyour/qinglong#2539]
### Qinglong version

正式版V2.17.11

### Steps to reproduce

脚本无法调用tg机器人通知，config.sh里面有配置tg相关信息，一样的tg信息在系统设置-通知设置中是可以发送消息到tg机器人的，但到运行脚本的时候就报错，

加载通知服务成功！
tg 服务启动
Exception in thread telegram_bot:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/shell/preload/notify.py", line 601, in telegram_bot
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'api.telegram.org/bot**/sendMessage'

### What is expected?

请问要如何解决这个问题

### What is actually happening?

请问要如何解决这个问题

**Comment by whyour** [comment]
TG_API_HOST 环境变量配置问题

**Comment by FYboss** [comment]
没自定义api，是走代理的，今天啥都没搞，TG_BOT_TOKEN、TG_USER_ID、TG_PROXY_HOST、TG_PROXY_PORT都是跟前几天一样的参数，今天就可以发通知给tg机器人，前面连续几天都不行
