### ISSUE TITLE
Problems with updates

### ISSUE THREAD

**Issue by dinosaur168** [whyour/qinglong#2559]
### Qinglong version

v20.12.1

### Steps to reproduce

I click on update directly in the backend and then the ERROR page comes up

### What is expected?

Completion of the update

### What is actually happening?

I don't know.

### System Info

```shell
/root/.pm2/logs/panel-error.log last 15 lines:
6|panel    | 2024-11-12T10:07:16:     at startServer (/ql/back/app.ts:14:3)
6|panel    | 2024-11-12T10:07:16: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
6|panel    | 2024-11-12T10:07:16: TypeError: Sentry.setupExpressErrorHandler is not a function
6|panel    | 2024-11-12T10:07:16:     at exports.default (/ql/back/loaders/express.ts:136:10)
6|panel    | 2024-11-12T10:07:16:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
6|panel    | 2024-11-12T10:07:16:     at startServer (/ql/back/app.ts:14:3)
6|panel    | 2024-11-12T10:08:17: TypeError: Sentry.setupExpressErrorHandler is not a function
6|panel    | 2024-11-12T10:08:17:     at exports.default (/ql/back/loaders/express.ts:136:10)
6|panel    | 2024-11-12T10:08:17:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
6|panel    | 2024-11-12T10:08:17:     at startServer (/ql/back/app.ts:14:3)
6|panel    | 2024-11-12T10:08:17: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
6|panel    | 2024-11-12T10:08:17: TypeError: Sentry.setupExpressErrorHandler is not a function
6|panel    | 2024-11-12T10:08:17:     at exports.default (/ql/back/loaders/express.ts:136:10)
6|panel    | 2024-11-12T10:08:17:     at Object.exports.default (/ql/back/loaders/app.ts:26:16)
6|panel    | 2024-11-12T10:08:17:     at startServer (/ql/back/app.ts:14:3)
```

**Comment by whyour** [comment]
Update the image using docker, and then recreate the container
