### ISSUE TITLE
容器一直重启

### ISSUE THREAD

**Issue by chanda** [whyour/qinglong#280]
log如下 半分钟会重启一次

/usr/local/lib/node_modules/pm2/lib/API/UX/pm2-ls.js:448
      let use = sys_metrics[`fs:use:${fs}`].value
                                            ^

TypeError: Cannot read property 'value' of undefined
    at /usr/local/lib/node_modules/pm2/lib/API/UX/pm2-ls.js:448:45
    at Array.forEach (<anonymous>)
    at miniMonitBar (/usr/local/lib/node_modules/pm2/lib/API/UX/pm2-ls.js:447:11)
    at Object.module.exports [as list] (/usr/local/lib/node_modules/pm2/lib/API/UX/pm2-ls.js:474:5)
    at doList (/usr/local/lib/node_modules/pm2/lib/API.js:1761:12)
    at /usr/local/lib/node_modules/pm2/lib/API.js:1731:7
    at /usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:376:20)
    at Parser._write (/usr/local/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)

**Comment by whyour** [comment]
这个问题建议你使用最新镜像试试，看不出来是啥问题
