### ISSUE TITLE
telegram发送通知消息失败

### ISSUE THREAD

**Issue by ldcr1319** [whyour/qinglong#287]
请问设置了TG_BOT_TOKEN 和TG_USER_ID后执行脚本, 最后推送通知时报如下错误怎么处理,感谢

`HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1623218564739,
    socket: 1623218564741,
    lookup: 1623218564744,
    connect: 1623218564749,
    secureConnect: 1623218565380,
    upload: 1623218565380,
    response: 1623218565697,
    end: 1623218565701,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 3,
      tcp: 5,
      tls: 631,
      request: 0,
      firstByte: 317,
      download: 4,
      total: 962
    }
  }
}
`

**Comment by ldcr1319** [comment]
设置了2个TG_BOT_TOKEN
