### ISSUE TITLE
运行其它地方下载的js脚本报错

### ISSUE THREAD

**Issue by msn1983aa** [whyour/qinglong#314]
报错信息如下：
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/ql/scripts/jd_try.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

同样的脚本在jdv4下试过运行正常

**Comment by whyour** [comment]
不理解你其他地方下载是啥意思，用的什么命令下载的，你下载的文件名和你任务里执行的对应下

**Comment by msn1983aa** [comment]
> 不理解你其他地方下载是啥意思，用的什么命令下载的，你下载的文件名和你任务里执行的对应下

比如在tg群里下载的xxx.js
放在ql/scripts文件夹下
用ql ql/scripts/xxx.js去执行就会报以上的错
同样的在jdv4下用 jtask jdv4/scripts/xxx.js 执行就没有报错

**Comment by whyour** [comment]
@msn1983aa 不需要路径，  task xxx.js 就行
