### ISSUE TITLE
拉取脚本报错

### ISSUE THREAD

**Issue by kongren978** [whyour/qinglong#324]
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './jdCookie.js'
Require stack:
- /ql/scripts/whyour_hundun_jx_factory.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ql/scripts/whyour_hundun_jx_factory.js:30:35)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/whyour_hundun_jx_factory.js' ]
}

拉取命令docker exec -it qinglong ql repo https://ghproxy.com/https://github.com/whyour/hundun.git "quanx" "tokens|caiyun|didi|donate|fold|Env"

**Comment by anleihn** [comment]
我也是这个错误 第一次用

**Comment by kongren978** [comment]
拉取后手动运行日志里错误 描述错了

**Comment by whyour** [comment]
拉下下依赖的文件，按照频道的示例仓库拉取

**Comment by zhangslob** [comment]
@kongren978 你的可以了吗，我也是一直报着错误

**Comment by kongren978** [comment]
> 拉下下依赖的文件，按照频道的示例仓库拉取

我 ql update 然后重新ql repo 还是错误

**Comment by zhangslob** [comment]
> > 拉下下依赖的文件，按照频道的示例仓库拉取
> 
> 我 ql update 然后重新ql repo 还是错误

你可以了吗，能用的话告诉我
