### ISSUE TITLE
internal/modules/cjs/loader.js:888   throw err;   ^  Error: Cannot find module './jdCookie.js,无依赖文件导致脚本无法运行

### ISSUE THREAD

**Issue by aippnne** [whyour/qinglong#333]
`
🔔女装盲盒抽京豆, 开始!
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './jdCookie.js'
Require stack:
- /ql/scripts/chinnkarahoi_jd_scripts_jd_nzmh.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ql/scripts/chinnkarahoi_jd_scripts_jd_nzmh.js:26:35)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/chinnkarahoi_jd_scripts_jd_nzmh.js' ]`

PS:REPO地址为ql repo https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"

**Comment by whyour** [comment]
最新版已修复，执行下 ql update，然后执行 ql repo命令

**Comment by kongren978** [comment]
> `
> 🔔女装盲盒抽京豆, 开始!
> internal/modules/cjs/loader.js:888
> throw err;
> ^
> 
> Error: Cannot find module './jdCookie.js'
> Require stack:
> 
> * /ql/scripts/chinnkarahoi_jd_scripts_jd_nzmh.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:730:27)
>   at Module.require (internal/modules/cjs/loader.js:957:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at Object. (/ql/scripts/chinnkarahoi_jd_scripts_jd_nzmh.js:26:35)
>   at Module._compile (internal/modules/cjs/loader.js:1068:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>   at Module.load (internal/modules/cjs/loader.js:933:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:774:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/ql/scripts/chinnkarahoi_jd_scripts_jd_nzmh.js' ]`
> 
> PS:REPO地址为ql repo https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"

你现在解决了吗
