### ISSUE TITLE
gocq推送失败

### ISSUE THREAD

**Issue by z594024037** [whyour/qinglong#345]
日志如下：
发送go-cqhttp通知调用API失败！！

RequestError: Timeout awaiting 'request' for 15000ms
    at ClientRequest.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/core/index.js:956:65)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:388:22)
    at ClientRequest.origin.emit (/ql/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.5/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:498:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1623762168219,
    socket: 1623762168219,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1623762183222,
    abort: undefined,
    phases: {
      wait: 0,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 15003
    }
  },
  event: 'request'
}

**Comment by z594024037** [comment]
不
