### ISSUE TITLE
青龙运行脚本出错

### ISSUE THREAD

**Issue by yunv7** [whyour/qinglong#351]
拉取了zero205/JD_tencent_scf的库，Session里配置了cookie，运行时提示找不到'./jdCookie.js'

🔔口袋书店, 开始!
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './jdCookie.js'
Require stack:
- /ql/scripts/zero205_JD_tencent_scf_jd_bookshop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/ql/scripts/zero205_JD_tencent_scf_jd_bookshop.js:23:35)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/zero205_JD_tencent_scf_jd_bookshop.js' ]
}

这应该怎么改能用？

**Comment by yunv7** [comment]
解决了 关了吧

**Comment by jhondemon** [comment]
咋解决的，兄弟

**Comment by zhangslob** [comment]
同问

**Comment by TEAMO233** [comment]
> 解决了关对了

老哥怎么解决的？

**Comment by yunv7** [comment]
ql repo https://ghproxy.com/https://github.com/chinnkarahoi/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"
照这个格式拉就解决了
