### ISSUE TITLE
控制面板报错，userAPI502，页面空白

### ISSUE THREAD

**Issue by denzhengwei** [whyour/qinglong#425]
=====> nginx服务正常

---> pm2日志
    at Object.<anonymous> (/ql/back/app.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/build/app.js' ]
}

=====> 检测后台

=====> 后台服务异常，重启后台

=====> 检测结束

## 执行结束... 2021-06-29 10:25:10  耗时 17 秒

**Comment by whyour** [comment]
ql update 然后 ql check再贴下日志

**Comment by denzhengwei** [comment]
check多了一步ql reset，现在面板正常了
