### ISSUE TITLE
更新镜像后 脚本运行报错

### ISSUE THREAD

**Issue by wyap-echo** [whyour/qinglong#432]
重新安装了一下 还是一样的问题
## 开始执行... 2021-07-01 09:36:57

🔔京东多合一签到, 开始!

====================共2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/7/1 上午9:36:57=====================

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'download'
Require stack:
- /ql/scripts/chinnkarahoi_jd_scripts_jd_bean_sign.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/chinnkarahoi_jd_scripts_jd_bean_sign.js:16:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/chinnkarahoi_jd_scripts_jd_bean_sign.js' ]
}

## 执行结束... 2021-07-01 09:36:57  耗时 0 秒

**Comment by whyour** [comment]
@wyap-echo ql check
