### ISSUE TITLE
面板不能访问，成白板，shell命令ql update更新显示代码如下

### ISSUE THREAD

**Issue by hubing0917** [whyour/qinglong#610]
现在ql应该是v2.8.5-001
运行命令ql update，显示v2.8.4-004，运行过ql check也不行。
代码如下：

root@qinglong:/ql $ ql check
## 开始执行... 2021-08-26 17:19:07

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.78bd43a9.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.17
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.34/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.c8a4ac84.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   38 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
   41 nginx     0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-08-26T17:18:56: info:    ✌️ Express loaded
2021-08-26T17:18:58: info:    ✌️ DB loaded and connected!
2021-08-26T17:18:58: info:    ✌️ Dependency Injector loaded
2021-08-26T17:18:58: info:    ✌️ Express loaded
2021-08-26T17:19:00: info:    ✌️ DB loaded and connected!
2021-08-26T17:19:00: info:    ✌️ Dependency Injector loaded
2021-08-26T17:19:00: info:    ✌️ Express loaded
2021-08-26T17:19:01: info:    ✌️ DB loaded and connected!
2021-08-26T17:19:01: info:    ✌️ Dependency Injector loaded
2021-08-26T17:19:01: info:    ✌️ Express loaded
2021-08-26T17:19:03: info:    ✌️ DB loaded and connected!
2021-08-26T17:19:03: info:    ✌️ Dependency Injector loaded
2021-08-26T17:19:03: info:    ✌️ Express loaded
2021-08-26T17:19:05: info:    ✌️ DB loaded and connected!
2021-08-26T17:19:05: info:    ✌️ Dependency Injector loaded
2021-08-26T17:19:05: info:    ✌️ Express loaded
2021-08-26T17:19:06: info:    ✌️ DB loaded and connected!
2021-08-26T17:19:06: info:    ✌️ Dependency Injector loaded
2021-08-26T17:19:06: info:    ✌️ Express loaded
2021-08-26T17:19:08: info:    ✌️ DB loaded and connected!
2021-08-26T17:19:00: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (28925811312) is greater than 2 GB
2021-08-26T17:19:00:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
2021-08-26T17:19:00:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-08-26T17:19:00: }
2021-08-26T17:19:01: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (28925811312) is greater than 2 GB
2021-08-26T17:19:01:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
2021-08-26T17:19:01:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-08-26T17:19:01: }
2021-08-26T17:19:03: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (28925811312) is greater than 2 GB
2021-08-26T17:19:03:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
2021-08-26T17:19:03:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-08-26T17:19:03: }
2021-08-26T17:19:05: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (28925811312) is greater than 2 GB
2021-08-26T17:19:05:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
2021-08-26T17:19:05:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-08-26T17:19:05: }
2021-08-26T17:19:07: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (28925811312) is greater than 2 GB
2021-08-26T17:19:07:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
2021-08-26T17:19:07:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-08-26T17:19:07: }

=====> 检测后台

=====> 后台服务异常，重置基础环境并重启后台

---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

检测到 /ql 的依赖包有变化，运行 npm install...

Lockfile is up-to-date, resolution step is skipped
Already up-to-date

---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

检测到 /ql/scripts 的依赖包有变化，运行 npm install...

Progress: resolved 1, reused 0, downloaded 0, added 0
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
Packages: -1
-
Progress: resolved 22, reused 22, downloaded 0, added 0, done

dependencies:
+ crypto-js 4.1.1
- png-js

---> 脚本依赖安装完成

=====> 检测结束

## 执行结束... 2021-08-26 17:19:21  耗时 14 秒
root@qinglong:/ql $ ql update
fatal: Unable to create '/ql/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: Unable to create '/ql/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
## 开始执行... 2021-08-26 17:19:38

开始更新仓库：/ql

Fetching origin

更新/ql成功...

开始更新仓库：/ql/repo/static

Fetching origin
HEAD is now at 24b812e copy static at 2021-08-25 15:58:02
Already up to date.
Current branch master is up to date.

更新/ql/repo/static成功...

当前版本 v2.8.4-004...

重启面板中...

**Comment by whyour** [comment]
> > > ![image](https://user-images.githubusercontent.com/22700758/131080266-142eab2f-6362-46bd-844b-d2ccf7259b90.png)
> > > 哪个文件2G报错了，自己排查下
> > 
> > 
> > 哇，大佬来啦。
> > 请问怎么查文件的尺寸？我用window10+hyperv+Ubuntu，平时用finalshell管理，不过也只会些简单的命令，文件夹的操作还一直没有搞懂。
> 
> ql/db/中的crontab.db 有26.9G，正常吗？

不正常，远程下吧，你多少任务。目前用的数据库框架貌似有缺陷
