### ISSUE TITLE
2.9.1重启docker后添加的任务会消失

### ISSUE THREAD

**Issue by cilone** [whyour/qinglong#646]
2.9.1重启docker后添加的任务会消失

**Comment by zhangkeyanzky** [comment]
一样，任务也添加不了

**Comment by Huansheng1** [comment]
我这也是。。。

**Comment by Huansheng1** [comment]
## 开始执行... 2021-09-06 08:05:13

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.8b3a2272.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.17
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.34/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.9374af57.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   43 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
454603 root      0:00 nginx: worker process
454604 root      0:00 nginx: worker process
454605 root      0:00 nginx: worker process
454606 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-09-06T07:56:44:   code: 'EISDIR'
2021-09-06T07:56:44: }
2021-09-06T07:58:17: info:    ✌️ DB loaded and connected!
2021-09-06T07:58:17: info:    ✌️ Dependency Injector loaded
2021-09-06T07:58:17: info:    ✌️ Express loaded
2021-09-06T07:58:17: info:    ✌️ init data loaded
2021-09-06T07:58:17: info:
2021-09-06T07:58:17:       ################################################
2021-09-06T07:58:17:       🛡️  Server listening on port: 5600 🛡️
2021-09-06T07:58:17:       ################################################
2021-09-06T07:58:17:
2021-09-06T08:04:48: info:    ✌️ DB loaded and connected!
2021-09-06T08:04:48: info:    ✌️ Dependency Injector loaded
2021-09-06T08:04:48: info:    ✌️ Express loaded
2021-09-06T08:04:48: info:    ✌️ init data loaded
2021-09-06T08:04:48: info:
2021-09-06T08:04:48:       ################################################
2021-09-06T08:04:48:       🛡️  Server listening on port: 5600 🛡️
2021-09-06T08:04:48:       ################################################
2021-09-06T08:04:48:
2021-09-03T08:34:00:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-09-03T08:34:00:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2021-09-03T08:34:00:     at require (internal/modules/cjs/helpers.js:92:18)
2021-09-03T08:34:00:     at Object.<anonymous> (/ql/back/services/auth.ts:8:1)
2021-09-03T08:34:00:     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-09-03T08:34:00:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-09-03T08:34:00:     at Module.load (internal/modules/cjs/loader.js:937:32)
2021-09-03T08:34:00:     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-09-03T08:34:00:     at Module.require (internal/modules/cjs/loader.js:961:19)
2021-09-03T08:34:00:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39) {
2021-09-03T08:34:00:   code: 'MODULE_NOT_FOUND',
2021-09-03T08:34:00:   requireStack: [
2021-09-03T08:34:00:     '/ql/build/services/auth.js',
2021-09-03T08:34:00:     '/ql/build/api/auth.js',
2021-09-03T08:34:00:     '/ql/build/api/index.js',
2021-09-03T08:34:00:     '/ql/build/loaders/express.js',
2021-09-03T08:34:00:     '/ql/build/loaders/index.js',
2021-09-03T08:34:00:     '/ql/build/app.js'
2021-09-03T08:34:00:   ]
2021-09-03T08:34:00: }

=====> 检测后台

{"code":200,"data":{"username":"admin"}}

=====> 后台服务启动正常


=====> 检测结束


## 执行结束... 2021-09-06 08:05:14  耗时 1 秒

**Comment by gold2wave** [comment]
我也是，重启任务都没了

**Comment by ainioayi** [comment]
我也是，重启任务都没了
