### ISSUE TITLE
建议优化go-cqhttp发送消息时遇到百分号（%）发送异常的问题

### ISSUE THREAD

**Issue by SamDudu** [whyour/qinglong#658]
大佬，今天测出来一个bug，配置go-cqhttp后，如果发送的消息里包含百分号（%），就会报下面的错误，如果手动把发送数据里的百分号删了，就可以发送成功，期待后续更新里可以修复一下，感谢。
发送go-cqhttp通知调用API失败！！
qinglong版本：2.9.1
go-cqhttp: 1.0.0 beta6
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1630646083330,
    socket: 1630646083331,
    lookup: 1630646083334,
    connect: 1630646083334,
    secureConnect: undefined,
    upload: 1630646083335,
    response: 1630646083339,
    end: 1630646083339,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 3,
      tcp: 0,
      tls: undefined,
      request: 1,
      firstByte: 4,
      download: 0,
      total: 9
    }
  }

**Comment by a417707897** [comment]
我也遇到这种问题了，go日志显示【已拒绝客户端 ip地址:48516 的请求: invalid URL escape "%\xe6\x88"】错误

**Comment by chen8945** [comment]
确实，我也碰到了
