### ISSUE TITLE
更新2.9.5启动异常，回退2.9.3后日志实时显示失效

### ISSUE THREAD

**Issue by redcats2** [whyour/qinglong#735]
同样问题，故障复现步骤。
1 原始版本2.9.3。
2 ql update to 2.9.5.
3 reboot Alpine.
4 访问[ql ip]:5700, 无法访问。
5 docker rm id -> docker install 
6 ql 可以恢复访问，version变更回2.9.3.
7 【故障】日志停留在更新前，手动或自动执行新脚本，日志不会实时刷新。脚本运行完再点‘’日志‘’button也没有更新

**Comment by redcats2** [comment]
补充
8 经初步测试，日志虽然不刷新，但脚本运行尚未发现明显异常

**Comment by whyour** [comment]
更新最新版镜像，2.9.5启动异常是什么异常

**Comment by youshou1800** [comment]
面板自动更新禁用了，还是自动更新，这是哪里有问题

**Comment by redcats2** [comment]
> 更新最新版镜像，2.9.5启动异常是什么异常

暂无法更新到2.9.5，更新报错，ql check提示似乎找不到/ql/db/crontab.db，但数据库文件是正常的，理由是两天以来正常运行（除了日志显示异常）不是很明白这段报错的原因。
==================================================================================
root@qinglong:/ql/scripts $ ql update
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 11 (delta 8), reused 11 (delta 8), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://ghproxy.com/https://github.com/whyour/qinglong
   d537901..9fba2a8  develop    -> origin/develop
warning: ignoring broken ref refs/remotes/origin/master
warning: ignoring broken ref refs/remotes/origin/master
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: inflate: data stream error (unknown compression method)
error: unable to unpack c0e022d76b2dd8c8aa3453fec60e6b805402856a header
fatal: loose object c0e022d76b2dd8c8aa3453fec60e6b805402856a (stored in .git/objects/c0/e022d76b2dd8c8aa3453fec60e6b805402856a) is corrupt
warning: ignoring broken ref refs/remotes/origin/master
warning: ignoring broken ref refs/remotes/origin/master
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: cannot pull with rebase: You have unstaged changes.
error: inflate: data stream error (unknown compression method)
error: unable to unpack c0e022d76b2dd8c8aa3453fec60e6b805402856a header
error: inflate: data stream error (unknown compression method)
error: unable to unpack c0e022d76b2dd8c8aa3453fec60e6b805402856a header
fatal: loose object c0e022d76b2dd8c8aa3453fec60e6b805402856a (stored in .git/objects/c0/e022d76b2dd8c8aa3453fec60e6b805402856a) is corrupt
## 开始执行... 2021-09-28 10:32:10


开始更新仓库：/ql

Fetching origin
HEAD is now at d537901 测试动态加载
Already up to date.
Current branch master is up to date.

更新/ql成功...

开始更新仓库：/ql/repo/static


更新/ql失败，请检查原因...


## 执行结束... 2021-09-28 10:32:15  耗时 5 秒
root@qinglong:/ql/scripts $ ql check 
## 开始执行... 2021-09-28 10:32:19


=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.21e90bc2.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.19
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.34/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.343791c4.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   42 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
14522 root      0:01 nginx: worker process
14524 root      0:00 nginx: worker process
14526 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-09-28T08:58:43:   [stack]: "TypeError: Cannot read property 'lastIndexOf' of undefined\n" +
2021-09-28T08:58:43:     '    at CronService.getKey (/ql/back/services/cron.ts:357:15)\n' +
2021-09-28T08:58:43:     '    at CronService.log (/ql/back/services/cron.ts:335:24)\n' +
2021-09-28T08:58:43:     '    at /ql/back/api/cron.ts:137:22',
2021-09-28T08:58:43:   [message]: "Cannot read property 'lastIndexOf' of undefined"
2021-09-28T08:58:43: }
2021-09-28T08:58:46: info:    modifyScript.sh pid: 21249 closed 0
2021-09-28T09:02:57: error:   🔥 error: TypeError: Cannot read property 'lastIndexOf' of undefined
2021-09-28T09:02:57:     at CronService.getKey (/ql/back/services/cron.ts:357:15)
2021-09-28T09:02:57:     at CronService.log (/ql/back/services/cron.ts:335:24)
2021-09-28T09:02:57:     at /ql/back/api/cron.ts:137:22 {
2021-09-28T09:02:57:   [stack]: "TypeError: Cannot read property 'lastIndexOf' of undefined\n" +
2021-09-28T09:02:57:     '    at CronService.getKey (/ql/back/services/cron.ts:357:15)\n' +
2021-09-28T09:02:57:     '    at CronService.log (/ql/back/services/cron.ts:335:24)\n' +
2021-09-28T09:02:57:     '    at /ql/back/api/cron.ts:137:22',
2021-09-28T09:02:57:   [message]: "Cannot read property 'lastIndexOf' of undefined"
2021-09-28T09:02:57: }
2021-09-28T10:20:55: info:    task zero205_JD_tencent_scf_main_jd_superMarket.js pid: 23334 closed 0
2021-09-28T10:23:31: info:    task zero205_JD_tencent_scf_main_jd_superMarket.js pid: 23471 closed 0
2021-09-28T10:25:15: info:    task zero205_JD_tencent_scf_main_jd_superMarket.js pid: 23552 closed 0
2021-09-25T09:12:24: [Error: ENOENT: no such file or directory, rename '/ql/db/crontab.db~' -> '/ql/db/crontab.db'] {
2021-09-25T09:12:24:   errno: -2,
2021-09-25T09:12:24:   code: 'ENOENT',
2021-09-25T09:12:24:   syscall: 'rename',
2021-09-25T09:12:24:   path: '/ql/db/crontab.db~',
2021-09-25T09:12:24:   dest: '/ql/db/crontab.db'
2021-09-25T09:12:24: }

=====> 检测后台

{"code":200,"data":{"username":"admin"}}

=====> 后台服务启动正常


=====> 检测结束


## 执行结束... 2021-09-28 10:32:25  耗时 6 秒
