### ISSUE TITLE
青龙面板突然出现502

### ISSUE THREAD

**Issue by Yvan0329** [whyour/qinglong#740]
log如下：

[TAILING] Tailing last 15 lines for [panel] process (change the value with --lines option)
/root/.pm2/logs/panel-out.log last 15 lines:
0|panel    | 2021-09-27T13:22:14: info:    ✌️ DB loaded and connected!
0|panel    | 2021-09-27T13:22:14: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-09-27T13:22:14: info:    ✌️ Express loaded
0|panel    | 2021-09-27T13:22:15: info:    ✌️ DB loaded and connected!
0|panel    | 2021-09-27T13:22:15: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-09-27T13:22:15: info:    ✌️ Express loaded
0|panel    | 2021-09-27T13:22:16: info:    ✌️ DB loaded and connected!
0|panel    | 2021-09-27T13:22:16: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-09-27T13:22:16: info:    ✌️ Express loaded
0|panel    | 2021-09-27T13:22:16: info:    ✌️ DB loaded and connected!
0|panel    | 2021-09-27T13:22:16: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-09-27T13:22:16: info:    ✌️ Express loaded
0|panel    | 2021-09-27T13:22:17: info:    ✌️ DB loaded and connected!
0|panel    | 2021-09-27T13:22:17: info:    ✌️ Dependency Injector loaded
0|panel    | 2021-09-27T13:22:17: info:    ✌️ Express loaded

/root/.pm2/logs/panel-error.log last 15 lines:
0|panel    | 2021-09-27T13:22:15:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
0|panel    | 2021-09-27T13:22:15:   code: 'ERR_FS_FILE_TOO_LARGE'
0|panel    | 2021-09-27T13:22:15: }
0|panel    | 2021-09-27T13:22:16: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2960592375) is greater than 2 GB
0|panel    | 2021-09-27T13:22:16:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
0|panel    | 2021-09-27T13:22:16:   code: 'ERR_FS_FILE_TOO_LARGE'
0|panel    | 2021-09-27T13:22:16: }
0|panel    | 2021-09-27T13:22:16: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2960592375) is greater than 2 GB
0|panel    | 2021-09-27T13:22:16:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
0|panel    | 2021-09-27T13:22:16:   code: 'ERR_FS_FILE_TOO_LARGE'
0|panel    | 2021-09-27T13:22:16: }
0|panel    | 2021-09-27T13:22:17: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2960592375) is greater than 2 GB
0|panel    | 2021-09-27T13:22:17:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:303:11) {
0|panel    | 2021-09-27T13:22:17:   code: 'ERR_FS_FILE_TOO_LARGE'
0|panel    | 2021-09-27T13:22:17: }

**Comment by Yvan0329** [comment]
青龙不知道为啥一直添加同个库的文件，同个任务添加了几十次。。文件过大，直接崩了
