### ISSUE TITLE
更新2.9.5后出现白屏问题

### ISSUE THREAD

**Issue by Huiaei** [whyour/qinglong#746]
ql check 输出如下

```
## 开始执行... 2021-09-29 09:36:01


=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.f778bd55.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.19
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.34/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.69cd269c.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   77 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
 8928 root      0:00 nginx: worker process
 8930 root      0:00 nginx: worker process
 8931 root      0:00 nginx: worker process
 8932 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-09-29T09:29:54:       ################################################
2021-09-29T09:29:54:     
2021-09-29T09:30:07: info:    ✌️ DB loaded and connected!
2021-09-29T09:30:07: info:    ✌️ Dependency Injector loaded
2021-09-29T09:30:07: info:    ✌️ Express loaded
2021-09-29T09:30:09: info:    ✌️ init data loaded
2021-09-29T09:30:09: info:    
2021-09-29T09:30:09:       ################################################
2021-09-29T09:30:09:       🛡️  Server listening on port: 5600 🛡️
2021-09-29T09:30:09:       ################################################
2021-09-29T09:30:09:     
2021-09-29T09:35:03: info:    ✌️ DB loaded and connected!
2021-09-29T09:35:03: info:    ✌️ Dependency Injector loaded
2021-09-29T09:35:03: info:    ✌️ Express loaded
2021-09-29T09:35:04: info:    ✌️ init data loaded
2021-09-29T09:35:04: info:    
2021-09-29T09:35:04:       ################################################
2021-09-29T09:35:04:       🛡️  Server listening on port: 5600 🛡️
2021-09-29T09:35:04:       ################################################
2021-09-29T09:35:04:     
2021-09-29T09:20:03:   code: 'ERR_STRING_TOO_LONG'
2021-09-29T09:20:03: }
2021-09-29T09:25:03: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-09-29T09:25:03:     at Object.slice (buffer.js:605:37)
2021-09-29T09:25:03:     at Buffer.toString (buffer.js:804:14)
2021-09-29T09:25:03:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-09-29T09:25:03:   code: 'ERR_STRING_TOO_LONG'
2021-09-29T09:25:03: }
2021-09-29T09:30:06: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-09-29T09:30:06:     at Object.slice (buffer.js:605:37)
2021-09-29T09:30:06:     at Buffer.toString (buffer.js:804:14)
2021-09-29T09:30:06:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-09-29T09:30:06:   code: 'ERR_STRING_TOO_LONG'
2021-09-29T09:30:06: }
2021-09-29T09:35:02: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-09-29T09:35:02:     at Object.slice (buffer.js:605:37)
2021-09-29T09:35:02:     at Buffer.toString (buffer.js:804:14)
2021-09-29T09:35:02:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-09-29T09:35:02:   code: 'ERR_STRING_TOO_LONG'
2021-09-29T09:35:02: }

=====> 检测后台

{"code":200,"data":{"username":"hu"}}

=====> 后台服务启动正常


=====> 检测结束


## 执行结束... 2021-09-29 09:36:03  耗时 2 秒
```

**Comment by Huiaei** [comment]
搞了半天发现是网络问题，jsdelivr.net加载有点问题
