### ISSUE TITLE
青龙面板服务异常，ql check执行后没用

### ISSUE THREAD

**Issue by wxjbb** [whyour/qinglong#750]
更新最新镜像也不行，下面是ql check日志：

docker exec -it qinglong ql check
rm: cannot remove '/ql/node_modules': Is a directory
## 开始执行... 2021-10-01 14:10:14

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成

=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.f778bd55.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.20
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.34/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.30ff3b5c.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   86 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
   87 nginx     0:00 nginx: worker process
   88 nginx     0:00 nginx: worker process
   89 nginx     0:00 nginx: worker process
   90 nginx     0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-10-01T14:09:58: info:    ✌️ Dependency Injector loaded
2021-10-01T14:09:58: info:    ✌️ Express loaded
2021-10-01T14:09:59: info:    ✌️ DB loaded and connected!
2021-10-01T14:09:59: info:    ✌️ Dependency Injector loaded
2021-10-01T14:09:59: info:    ✌️ Express loaded
2021-10-01T14:09:59: info:    ✌️ DB loaded and connected!
2021-10-01T14:09:59: info:    ✌️ Dependency Injector loaded
2021-10-01T14:09:59: info:    ✌️ Express loaded
2021-10-01T14:10:00: info:    ✌️ DB loaded and connected!
2021-10-01T14:10:00: info:    ✌️ Dependency Injector loaded
2021-10-01T14:10:00: info:    ✌️ Express loaded
2021-10-01T14:10:01: info:    ✌️ DB loaded and connected!
2021-10-01T14:10:01: info:    ✌️ Dependency Injector loaded
2021-10-01T14:10:01: info:    ✌️ Express loaded
2021-10-01T14:10:02: info:    ✌️ DB loaded and connected!
2021-10-01T14:10:02: info:    ✌️ Dependency Injector loaded
2021-10-01T14:10:02: info:    ✌️ Express loaded
2021-10-01T14:10:02: info:    ✌️ DB loaded and connected!
2021-10-01T14:10:02: info:    ✌️ Dependency Injector loaded
2021-10-01T14:10:02: info:    ✌️ Express loaded
2021-10-01T14:10:00: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3820021171) is greater than 2 GB
2021-10-01T14:10:00:     at new NodeError (internal/errors.js:322:7)
2021-10-01T14:10:00:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:302:11) {
2021-10-01T14:10:00:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-10-01T14:10:00: }
2021-10-01T14:10:01: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3820021171) is greater than 2 GB
2021-10-01T14:10:01:     at new NodeError (internal/errors.js:322:7)
2021-10-01T14:10:01:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:302:11) {
2021-10-01T14:10:01:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-10-01T14:10:01: }
2021-10-01T14:10:02: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3820021171) is greater than 2 GB
2021-10-01T14:10:02:     at new NodeError (internal/errors.js:322:7)
2021-10-01T14:10:02:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:302:11) {
2021-10-01T14:10:02:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-10-01T14:10:02: }
2021-10-01T14:10:02: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3820021171) is greater than 2 GB
2021-10-01T14:10:02:     at new NodeError (internal/errors.js:322:7)
2021-10-01T14:10:02:     at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:302:11) {
2021-10-01T14:10:02:   code: 'ERR_FS_FILE_TOO_LARGE'
2021-10-01T14:10:02: }

=====> 检测后台

=====> 后台服务异常，重置基础环境并重启后台

---> 1. 开始检测配置文件

---> 配置文件检测完成

---> 2. 开始安装青龙依赖

检测到 /ql 的依赖包有变化，运行 npm install...

Lockfile is up-to-date, resolution step is skipped
Already up-to-date

 WARN  "prepare" script of "@" inside "/ql" is skipped as the working directory seems suspicious. To run this lifecycle script anyway, use "--unsafe-perm".
---> 青龙依赖安装完成

---> 3. 开始安装脚本依赖

检测到 /ql/scripts 的依赖包有变化，运行 npm install...

Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +210
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /ql/scripts/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ crypto-js 4.1.1
+ download 8.0.0
+ got 11.8.2
+ http-server 0.12.3
+ qrcode-terminal 0.12.0
+ request 2.88.2
+ tough-cookie 4.0.0
+ tunnel 0.0.6
+ ws 7.5.3

Progress: resolved 210, reused 210, downloaded 0, added 210, done
---> 脚本依赖安装完成

=====> 检测结束

**Comment by wxjbb** [comment]
找到问题了，crontab.db不知道什么原因暴涨到3G多，删了重新之后重启容器就行了
