### ISSUE TITLE
无法访问5700端口，显示拒绝访问

### ISSUE THREAD

**Issue by Huiaei** [whyour/qinglong#756]
RT，曾经也出现过一次，当时删除了/ql/db/app.db 重启就好了，这次就不行了。
```
root@0d5c8f9a8358:/ql/db $ ql check
## 开始执行... 2021-10-04 16:03:38

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.f778bd55.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.20
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.34/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.3a16d673.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   78 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
 4602 root      0:00 nginx: worker process
 4603 root      0:00 nginx: worker process
 4604 root      0:00 nginx: worker process
 4605 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-10-04T15:57:07:       ################################################
2021-10-04T15:57:07:
2021-10-04T16:00:19: info:    ✌️ DB loaded and connected!
2021-10-04T16:00:19: info:    ✌️ Dependency Injector loaded
2021-10-04T16:00:19: info:    ✌️ Express loaded
2021-10-04T16:00:19: info:    ✌️ init data loaded
2021-10-04T16:00:19: info:
2021-10-04T16:00:19:       ################################################
2021-10-04T16:00:19:       🛡️  Server listening on port: 5600 🛡️
2021-10-04T16:00:19:       ################################################
2021-10-04T16:00:19:
2021-10-04T16:00:32: info:    ✌️ DB loaded and connected!
2021-10-04T16:00:32: info:    ✌️ Dependency Injector loaded
2021-10-04T16:00:32: info:    ✌️ Express loaded
2021-10-04T16:00:33: info:    ✌️ init data loaded
2021-10-04T16:00:33: info:
2021-10-04T16:00:33:       ################################################
2021-10-04T16:00:33:       🛡️  Server listening on port: 5600 🛡️
2021-10-04T16:00:33:       ################################################
2021-10-04T16:00:33:
2021-09-29T09:54:08:   code: 'ERR_STRING_TOO_LONG'
2021-09-29T09:54:08: }
2021-09-29T09:55:03: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-09-29T09:55:03:     at Object.slice (buffer.js:605:37)
2021-09-29T09:55:03:     at Buffer.toString (buffer.js:804:14)
2021-09-29T09:55:03:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-09-29T09:55:03:   code: 'ERR_STRING_TOO_LONG'
2021-09-29T09:55:03: }
2021-09-29T09:55:20: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-09-29T09:55:20:     at Object.slice (buffer.js:605:37)
2021-09-29T09:55:20:     at Buffer.toString (buffer.js:804:14)
2021-09-29T09:55:20:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-09-29T09:55:20:   code: 'ERR_STRING_TOO_LONG'
2021-09-29T09:55:20: }
2021-09-29T09:55:35: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-09-29T09:55:35:     at Object.slice (buffer.js:605:37)
2021-09-29T09:55:35:     at Buffer.toString (buffer.js:804:14)
2021-09-29T09:55:35:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-09-29T09:55:35:   code: 'ERR_STRING_TOO_LONG'
2021-09-29T09:55:35: }

=====> 检测后台

{"code":200,"data":{"username":"hu"}}

=====> 后台服务启动正常


=====> 检测结束


## 执行结束... 2021-10-04 16:03:40  耗时 2 秒
root@0d5c8f9a8358:/ql/db $ curl http://127.0.0.1:5700
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.f778bd55.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.20
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4.9.34/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5.62.0/mode/javascript/javascript.js"></script>
    <script src="/umi.3a16d673.js"></script>
  </body>
</html>
```

**Comment by whyour** [comment]
服务器防火墙问题吧，青龙服务没问题

**Comment by ProfessorX** [comment]
我这边也是，感觉是防火墙的问题，本地搭建的都跑不起来。
