### ISSUE TITLE
小白问题

### ISSUE THREAD

**Issue by lijialei888** [whyour/qinglong#780]
Esxi虚拟机黑群，黑群安装Docker，dovcker下建立青龙容器
为啥很多任务出错，缺乏依赖
日志-jx_aid_cashback.js
## 开始执行... 2021-10-16 19:31:05

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './function/common'
Require stack:
- /ql/scripts/shufflewzc_faker2_jx_aid_cashback.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/ql/scripts/shufflewzc_faker2_jx_aid_cashback.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/shufflewzc_faker2_jx_aid_cashback.js' ]
}

## 执行结束... 2021-10-16 19:31:06 耗时 1 秒

🔔京东保价, 开始!

====================共46个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/10/16 下午1:21:58=====================

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'jsdom'
Require stack:
- /ql/scripts/yuannian1112_jd_scripts_jd_priceProtect.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/ql/scripts/yuannian1112_jd_scripts_jd_priceProtect.js:25:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/yuannian1112_jd_scripts_jd_priceProtect.js' ]
}

## 执行结束... 2021-10-16 13:21:58 耗时 1 秒

☞✔☞
根据网上提供的安装必要依赖，也没用呢，Error: Cannot find module './function/common'这一条提示是否拉库不完整？另外安装依赖是ssh群晖后台，sudo -i，dock exec it 青龙容器，进入容器再安装的么？用npm命令。

**Comment by whyour** [comment]
./function/common  这是仓库里的代码，你ql repo执行的时候要拉取依赖文件
