### ISSUE TITLE
发送通知调用API失败

### ISSUE THREAD

**Issue by yuntian123456** [whyour/qinglong#812]
有些脚本运行完后末尾会出现如下报错，有些脚本却不会。请问下是我网络的原因，还是脚本的原因？？

......(脚本运行内容此处省略）......
......
_Bark APP发送通知调用API失败！！

RequestError: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/ql/scripts/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/ql/scripts/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1570:19)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET',
  timings: {
    start: 1635431463195,
    socket: 1635431463195,
    lookup: 1635431463224,
    connect: 1635431463226,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1635431463684,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 29,
      tcp: 2,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 489
    }
  }
}_

**Comment by crazyPerject** [comment]
解决了吗?我也有这个问题

**Comment by Toylee2019** [comment]
同问RequestError: Client network socket disconnected before secure TLS connection was established
