### ISSUE TITLE
bot 启动直接报错

### ISSUE THREAD

**Issue by cytown** [whyour/qinglong#829]
bot的日志显示：

```
2021-11-04 16:38:23,994-jbot-INFO=> [load_module] Bot加载失败-->login.py-->database is locked 
2021-11-04 16:38:24,730-asyncio-ERROR=> [default_exception_handler] Task exception was never retrieved
future: <Task finished name='Task-15' coro=<new_ver() done, defined at /ql/jbot/__main__.py:21> exception=ValueError('Could not find the input entity for PeerUser(user_id=《我的id》) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.')> 
Traceback (most recent call last):
  File "/ql/jbot/__main__.py", line 37, in new_ver
    await jdbot.send_message(chat_id, f'[机器人上新了](https://github.com/SuMaiKaDe/jddockerbot/tree/master)\n{botlog}\n运行日志为log/bot/run.log\n\n\t{info}', link_preview=False)
  File "/usr/lib/python3.8/site-packages/telethon/client/messages.py", line 767, in send_message
    entity = await self.get_input_entity(entity)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 461, in get_input_entity
    raise ValueError(
ValueError: Could not find the input entity for PeerUser(user_id=《我的id。。。》) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
```

我确定我的ID、token、api_id/api_hash都正确设置了。

**Comment by cytown** [comment]
再次重启后好像不报错了。谢谢。
