### ISSUE TITLE
2.10.0提示需要ql check后ql check无效后升级为2.10.2，再次ql check输出如下

### ISSUE THREAD

**Issue by spiritLHL** [whyour/qinglong#850]
错误情况：2.10.0打开应用界面提示需要ql check，ql check和重启容器都无法补救后，我尝试升级，升级成功，但打开应用界面提示Error: Cannot create a string longer than 0x1fffffe8 characters，再次ql check输出如下

```
(base) ubuntu@VM-4-13-ubuntu:~$ sudo docker exec -it ql7 bash -c "ql check"
## 开始执行... 2021-11-08 09:53:37

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.53264bde.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.20
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/javascript/javascript.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js"></script>
    <script src="/umi.4f0dba8d.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   38 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
  468 root      0:00 nginx: worker process
  469 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-11-08T09:52:32: info:    ✌️ Dependency Injector loaded
2021-11-08T09:52:32: info:    ✌️ Express loaded
2021-11-08T09:52:32: info:    ✌️ init data loaded
2021-11-08T09:52:33: info:    ✌️ Sock loaded
2021-11-08T09:52:33: info:    
2021-11-08T09:52:33:       ################################################
2021-11-08T09:52:33:       🛡️  Server listening on port: 5600 🛡️
2021-11-08T09:52:33:       ################################################
2021-11-08T09:52:33:     
2021-11-08T09:52:54: info:    ✌️ Server need close
2021-11-08T09:52:56: info:    ✌️ Sentry loaded
2021-11-08T09:52:57: info:    ✌️ Dependency Injector loaded
2021-11-08T09:52:57: info:    ✌️ Express loaded
2021-11-08T09:52:57: info:    ✌️ init data loaded
2021-11-08T09:52:58: info:    ✌️ Sock loaded
2021-11-08T09:52:58: info:    
2021-11-08T09:52:58:       ################################################
2021-11-08T09:52:58:       🛡️  Server listening on port: 5600 🛡️
2021-11-08T09:52:58:       ################################################
2021-11-08T09:52:58:     
2021-11-08T09:13:25:   code: 'ERR_STRING_TOO_LONG'
2021-11-08T09:13:25: }
2021-11-08T09:20:16: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-11-08T09:20:16:     at Object.slice (buffer.js:605:37)
2021-11-08T09:20:16:     at Buffer.toString (buffer.js:804:14)
2021-11-08T09:20:16:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-11-08T09:20:16:   code: 'ERR_STRING_TOO_LONG'
2021-11-08T09:20:16: }
2021-11-08T09:44:59: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-11-08T09:44:59:     at Object.slice (buffer.js:605:37)
2021-11-08T09:44:59:     at Buffer.toString (buffer.js:804:14)
2021-11-08T09:44:59:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-11-08T09:44:59:   code: 'ERR_STRING_TOO_LONG'
2021-11-08T09:44:59: }
2021-11-08T09:46:34: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-11-08T09:46:34:     at Object.slice (buffer.js:605:37)
2021-11-08T09:46:34:     at Buffer.toString (buffer.js:804:14)
2021-11-08T09:46:34:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-11-08T09:46:34:   code: 'ERR_STRING_TOO_LONG'
2021-11-08T09:46:34: }

=====> 检测后台

{"code":200,"data":{"username":"xxxxx"}}

=====> 后台服务启动正常


=====> 检测结束


## 执行结束... 2021-11-08 09:53:39  耗时 2 秒
```

请问有方法补救吗？没法子只能重装了

**Comment by spiritLHL** [comment]
又看了一下，异常容器的app.db文件异常的大，583MB，尝试移除该db文件后再创建应用，然后再重启容器，应用使用正常了，虽然ql check还有以下报错：
```
2021-11-08T10:10:16:       ################################################
2021-11-08T10:10:16:       🛡️  Server listening on port: 5600 🛡️
2021-11-08T10:10:16:       ################################################
2021-11-08T10:10:16:     
2021-11-08T09:13:25:   code: 'ERR_STRING_TOO_LONG'
2021-11-08T09:13:25: }
2021-11-08T09:20:16: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-11-08T09:20:16:     at Object.slice (buffer.js:605:37)
2021-11-08T09:20:16:     at Buffer.toString (buffer.js:804:14)
2021-11-08T09:20:16:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-11-08T09:20:16:   code: 'ERR_STRING_TOO_LONG'
2021-11-08T09:20:16: }
2021-11-08T09:44:59: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-11-08T09:44:59:     at Object.slice (buffer.js:605:37)
2021-11-08T09:44:59:     at Buffer.toString (buffer.js:804:14)
2021-11-08T09:44:59:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-11-08T09:44:59:   code: 'ERR_STRING_TOO_LONG'
2021-11-08T09:44:59: }
2021-11-08T09:46:34: Error: Cannot create a string longer than 0x1fffffe8 characters
2021-11-08T09:46:34:     at Object.slice (buffer.js:605:37)
2021-11-08T09:46:34:     at Buffer.toString (buffer.js:804:14)
2021-11-08T09:46:34:     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:68:23) {
2021-11-08T09:46:34:   code: 'ERR_STRING_TOO_LONG'
2021-11-08T09:46:34: }
```
这部分报错在其他正常容器中没有的，不知道会不会影响后续容器使用

**Comment by spiritLHL** [comment]
升级后使用一天暂时正常
