### ISSUE TITLE
【2.10.5】脚本管理报错 ENOENT: no such file or directory, stat '/ql/scripts/node_modules/child_process'

### ISSUE THREAD

**Issue by Huiaei** [whyour/qinglong#883]
如题，一开始是升到2.10.3，然后更新到2.10.5 。因为2.10.3一直重启无法进入容器内更新，所以改了文件进入。

## 操作简述：

使用了以下方法来进入容器更新：

一开始复制 /shell/update.sh 和更改 /ql/docker/docker-entrypoint.sh 来执行update.sh的内容
之后更改 /ql/docker/docker-entrypoint.sh 注释掉两个判断，直接强行进入，之后在容器内执行 ql update

访问控制台--脚本管理报错 ENOENT: no such file or directory, stat '/ql/scripts/node_modules/child_process'

## docker 容器日志：
```
======================1. 检测配置文件========================


'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'

'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'


======================2. 安装依赖========================



======================3. 启动nginx========================


nginx启动成功...


======================4. 启动控制面板========================


[PM2] Starting /ql/build/app.js in fork_mode (1 instance)

[PM2] Done.

┌─────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐

│ id  │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │

├─────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤

│ 0   │ panel    │ default     │ N/A     │ fork    │ 107      │ 0s     │ 0    │ online    │ 0%       │ 30.4mb   │ root     │ disabled │

└─────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

控制面板启动成功...


======================5. 启动定时任务========================


[PM2] Starting /ql/build/schedule.js in fork_mode (1 instance)

[PM2] Done.

┌─────┬─────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐

│ id  │ name        │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │

├─────┼─────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤

│ 0   │ panel       │ default     │ N/A     │ fork    │ 107      │ 0s     │ 0    │ online    │ 100%     │ 62.1mb   │ root     │ disabled │

│ 1   │ schedule    │ default     │ N/A     │ fork    │ 148      │ 0s     │ 0    │ online    │ 0%       │ 23.2mb   │ root     │ disabled │

└─────┴─────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

定时任务启动成功...


======================7. 执行自定义脚本========================


自定义脚本后台执行中...


############################################################


容器启动成功...


请先访问5700端口，登录成功面板之后再执行添加定时任务...

############################################################


crond[157]: crond (busybox 1.31.1) started, log level 8

crond[157]: user root: parse error at 7

crond[157]: user root: parse error at 7

crond[157]: user root: parse error at 7

crond[157]: user root: parse error at 7

crond[157]: user root: parse error at 7

crond[157]: user root: parse error at 7

```

## ql check 结果：
```
## 开始执行... 2021-11-12 15:54:43

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.f778bd55.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.20
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/javascript/javascript.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js"></script>
    <script src="/umi.2f18fd93.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   76 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
 7655 root      0:00 nginx: worker process
 7656 root      0:00 nginx: worker process
 7657 root      0:00 nginx: worker process
 7658 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-11-12T15:52:32:     at next (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:137:13)
2021-11-12T15:52:32:     at Route.dispatch (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:112:3)
2021-11-12T15:52:32:     at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5) {
2021-11-12T15:52:32:   [stack]: "Error: ENOENT: no such file or directory, stat '/ql/scripts/node_modules/child_process'\n" +
2021-11-12T15:52:32:     '    at Object.statSync (fs.js:1131:3)\n' +
2021-11-12T15:52:32:     '    at /ql/back/api/script.ts:33:38\n' +
2021-11-12T15:52:32:     '    at Array.map (<anonymous>)\n' +
2021-11-12T15:52:32:     '    at /ql/back/api/script.ts:32:41\n' +
2021-11-12T15:52:32:     '    at Array.map (<anonymous>)\n' +
2021-11-12T15:52:32:     '    at /ql/back/api/script.ts:21:26\n' +
2021-11-12T15:52:32:     '    at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)\n' +
2021-11-12T15:52:32:     '    at next (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:137:13)\n' +
2021-11-12T15:52:32:     '    at Route.dispatch (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:112:3)\n' +
2021-11-12T15:52:32:     '    at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)',
2021-11-12T15:52:32:   [message]: "ENOENT: no such file or directory, stat '/ql/scripts/node_modules/child_process'",
2021-11-12T15:52:32:   errno: -2,
2021-11-12T15:52:32:   syscall: 'stat',
2021-11-12T15:52:32:   code: 'ENOENT',
2021-11-12T15:52:32:   path: '/ql/scripts/node_modules/child_process'
2021-11-12T15:52:32: }
2021-11-04T08:04:37:   requireStack: [
2021-11-04T08:04:37:     '/ql/build/loaders/sock.js',
2021-11-04T08:04:37:     '/ql/build/loaders/server.js',
2021-11-04T08:04:37:     '/ql/build/app.js'
2021-11-04T08:04:37:   ]
2021-11-04T08:04:37: }
2021-11-12T15:39:11: TypeError: Cannot read property 'headers' of null
2021-11-12T15:39:11:     at Server.<anonymous> (/ql/back/loaders/sock.ts:15:15)
2021-11-12T15:39:11:     at Server.emit (events.js:400:28)
2021-11-12T15:39:11:     at Server.emit (domain.js:475:12)
2021-11-12T15:39:11:     at App.emit (/ql/node_modules/.pnpm/sockjs@0.3.21/node_modules/sockjs/lib/sockjs.js:196:29)
2021-11-12T15:39:11:     at /ql/node_modules/.pnpm/sockjs@0.3.21/node_modules/sockjs/lib/transport.js:111:25
2021-11-12T15:39:11:     at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-11-12T15:39:11: TypeError: Cannot read property 'headers' of null
2021-11-12T15:39:11:     at Server.<anonymous> (/ql/back/loaders/sock.ts:15:15)
2021-11-12T15:39:11:     at Server.emit (events.js:400:28)
2021-11-12T15:39:11:     at Server.emit (domain.js:475:12)
2021-11-12T15:39:11:     at App.emit (/ql/node_modules/.pnpm/sockjs@0.3.21/node_modules/sockjs/lib/sockjs.js:196:29)
2021-11-12T15:39:11:     at /ql/node_modules/.pnpm/sockjs@0.3.21/node_modules/sockjs/lib/transport.js:111:25
2021-11-12T15:39:11:     at processTicksAndRejections (internal/process/task_queues.js:77:11)

=====> 检测后台

{"code":200,"data":{"username":"hu"}}

=====> 后台服务启动正常


=====> 检测结束


## 执行结束... 2021-11-12 15:54:46  耗时 3 秒
```

## /ql/docker/docker-entrypoint.sh :
```
#!/bin/bash

dir_shell=/ql/shell
. $dir_shell/share.sh
link_shell

echo -e "======================1. 检测配置文件========================\n"
make_dir /etc/nginx/conf.d
cp -fv $nginx_conf /etc/nginx/nginx.conf
cp -fv $nginx_app_conf /etc/nginx/conf.d/front.conf
pm2 l &>/dev/null
echo

echo -e "======================2. 安装依赖========================\n"
update_depend
echo

echo -e "======================3. 启动nginx========================\n"
nginx -s reload 2>/dev/null || nginx -c /etc/nginx/nginx.conf
echo -e "nginx启动成功...\n"

echo -e "======================4. 启动控制面板========================\n"
pm2 delete panel &>/dev/null
pm2 start $dir_root/build/app.js -n panel --source-map-support --time
echo -e "控制面板启动成功...\n"

echo -e "======================5. 启动定时任务========================\n"
pm2 delete schedule &>/dev/null
pm2 start $dir_root/build/schedule.js -n schedule --source-map-support --time
echo -e "定时任务启动成功...\n"

if [[ $AutoStartBot == true ]]; then
  echo -e "======================6. 启动bot========================\n"
  nohup ql bot >>$dir_log/start.log 2>&1 &
  echo -e "bot后台启动中...\n"
fi

if [[ $EnableExtraShell == true ]]; then
  echo -e "======================7. 执行自定义脚本========================\n"
  nohup ql extra >>$dir_log/start.log 2>&1 &
  echo -e "自定义脚本后台执行中...\n"
fi

echo -e "############################################################\n"
echo -e "容器启动成功..."
echo -e "\n请先访问5700端口，登录成功面板之后再执行添加定时任务..."
echo -e "############################################################\n"

crond -f >/dev/null

exec "$@"
```

**Comment by librec** [comment]
青龙版本 2.10.5
环境 docker in openwrt
脚本管理看不到脚本文件
ENOENT: no such file or directory, stat '/ql/scripts/node_modules/download'

**Comment by cs0663c** [comment]
青龙版本 2.10.5
环境 docker in openwrt
脚本管理看不到脚本文件.
EISDIR: illegal operation on a directory, read

**Comment by librec** [comment]
更新到2.10.6，发现修好了

**Comment by Huiaei** [comment]
2.10.6 好像修好了，暂时没发现这个问题了
