### ISSUE TITLE
"脚本管理"功能有两个问题

### ISSUE THREAD

**Issue by requireCool** [whyour/qinglong#885]
1. 进入脚本管理页面后最上方会提示`EISDIR: illegal operation on a directory, read`
![image](https://user-images.githubusercontent.com/55184050/141449146-180326c3-625c-45e5-acb2-bc40de9a45b3.png)

2. 打开一个文件夹后，里面的sendNotify.js缩进有问题
关闭文件夹后，树状图里出现了残留的sendNotify.js

**Comment by yduis6554** [comment]
半成品，已经退回去了

**Comment by cs0663c** [comment]
root@qinglong:/ql $ ql check
## 开始执行... 2021-11-12 21:17:26

=====> 开始检测
---> 1. 复制通知文件

---> 复制一份 /ql/sample/notify.py 为 /ql/scripts/notify.py

'/ql/sample/notify.py' -> '/ql/scripts/notify.py'

---> 复制一份 /ql/sample/notify.js 为 /ql/scripts/sendNotify.js

'/ql/sample/notify.js' -> '/ql/scripts/sendNotify.js'
---> 通知文件复制完成

---> 2. 复制nginx配置文件

'/ql/docker/nginx.conf' -> '/etc/nginx/nginx.conf'
'/ql/docker/front.conf' -> '/etc/nginx/conf.d/front.conf'
---> 配置文件复制完成


=====> 检测面板

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="shortcut icon" type="image/x-icon" href="/images/g5.ico" />
    <link rel="stylesheet" href="/umi.f778bd55.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.5.20
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/lib/react-dom/16.13.1/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkreader@4/darkreader.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/lib/codemirror.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/shell/shell.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/python/python.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/codemirror@5/mode/javascript/javascript.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.min.js"></script>
    <script src="/umi.2f18fd93.js"></script>
  </body>
</html>

=====> 面板服务启动正常

=====> 检测nginx服务
   44 root      0:00 nginx: master process nginx -c /etc/nginx/nginx.conf
 2846 root      0:00 nginx: worker process
 2847 root      0:00 nginx: worker process

=====> nginx服务正常

---> pm2日志
2021-11-12T21:14:00:     at next (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:137:13)
2021-11-12T21:14:00:     at Route.dispatch (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:112:3)
2021-11-12T21:14:00:     at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)
2021-11-12T21:14:00:     at /ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/index.js:281:22 {
2021-11-12T21:14:00:   [stack]: 'Error: EISDIR: illegal operation on a directory, read\n' +
2021-11-12T21:14:00:     '    at Object.readSync (fs.js:617:3)\n' +
2021-11-12T21:14:00:     '    at tryReadSync (fs.js:382:20)\n' +
2021-11-12T21:14:00:     '    at Object.readFileSync (fs.js:419:19)\n' +
2021-11-12T21:14:00:     '    at Object.getFileContentByName (/ql/back/config/util.ts:8:15)\n' +
2021-11-12T21:14:00:     '    at /ql/back/api/script.ts:62:25\n' +
2021-11-12T21:14:00:     '    at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)\n' +
2021-11-12T21:14:00:     '    at next (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:137:13)\n' +
2021-11-12T21:14:00:     '    at Route.dispatch (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/route.js:112:3)\n' +
2021-11-12T21:14:00:     '    at Layer.handle [as handle_request] (/ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/layer.js:95:5)\n' +
2021-11-12T21:14:00:     '    at /ql/node_modules/.pnpm/express@4.17.1/node_modules/express/lib/router/index.js:281:22',
2021-11-12T21:14:00:   [message]: 'EISDIR: illegal operation on a directory, read',
2021-11-12T21:14:00:   errno: -21,
2021-11-12T21:14:00:   syscall: 'read',
2021-11-12T21:14:00:   code: 'EISDIR'
2021-11-12T21:14:00: }
2021-11-08T17:35:14:   code: 'MODULE_NOT_FOUND',
2021-11-08T17:35:14:   requireStack: [ '/ql/build/loaders/sentry.js', '/ql/build/app.js' ]
2021-11-08T17:35:14: }
2021-11-08T17:35:18: Error: Cannot find module '@sentry/node'
2021-11-08T17:35:18: Require stack:
2021-11-08T17:35:18: - /ql/build/loaders/sentry.js
2021-11-08T17:35:18: - /ql/build/app.js
2021-11-08T17:35:18:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
2021-11-08T17:35:18:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2021-11-08T17:35:18:     at require (internal/modules/cjs/helpers.js:93:18)
2021-11-08T17:35:18:     at Object.<anonymous> (/ql/back/loaders/sentry.ts:2:1)
2021-11-08T17:35:18:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-11-08T17:35:18:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-11-08T17:35:18:     at Module.load (internal/modules/cjs/loader.js:950:32)
2021-11-08T17:35:18:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2021-11-08T17:35:18:     at Module.require (internal/modules/cjs/loader.js:974:19)
2021-11-08T17:35:18:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:80:39) {
2021-11-08T17:35:18:   code: 'MODULE_NOT_FOUND',
2021-11-08T17:35:18:   requireStack: [ '/ql/build/loaders/sentry.js', '/ql/build/app.js' ]
2021-11-08T17:35:18: }

=====> 检测后台

{"code":200,"data":{"username":"admin"}}

=====> 后台服务启动正常


=====> 检测结束


## 执行结束... 2021-11-12 21:17:30  耗时 4 秒

**Comment by DarkAge2018** [comment]
脚本管理搜索不到scripts子目录里面的文件，只能搜scripts下的文件，这是我个人的问题吗？
是不是权限有问题？
