### ISSUE TITLE
有没有回退的方法,更新了2.10.11之后就进不了后台了

### ISSUE THREAD

**Issue by lancer-wang** [whyour/qinglong#981]
然后cpu和内存双拉满,不知道什么原因
![image](https://user-images.githubusercontent.com/69783837/144804227-65c536f9-4934-4572-9183-1c37c9be0575.png)

**Comment by Kaol-Fu** [comment]
出现了同样的问题，ql check显示：
```
2021-11-28T17:39:58:     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
2021-11-28T17:39:58:   code: 'MODULE_NOT_FOUND',
2021-11-28T17:39:58:   requireStack: [ '/ql/build/app.js' ]
2021-11-28T17:39:58: }
2021-11-28T17:39:59: Error: Cannot find module 'reflect-metadata'
2021-11-28T17:39:59: Require stack:
2021-11-28T17:39:59: - /ql/build/app.js
2021-11-28T17:39:59:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2021-11-28T17:39:59:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
2021-11-28T17:39:59:     at require (node:internal/modules/cjs/helpers:102:18)
2021-11-28T17:39:59:     at Object.<anonymous> (/ql/back/app.ts:1:1)
2021-11-28T17:39:59:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
2021-11-28T17:39:59:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2021-11-28T17:39:59:     at Module.load (node:internal/modules/cjs/loader:981:32)
2021-11-28T17:39:59:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2021-11-28T17:39:59:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.2/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
2021-11-28T17:39:59:     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
2021-11-28T17:39:59:   code: 'MODULE_NOT_FOUND',
2021-11-28T17:39:59:   requireStack: [ '/ql/build/app.js' ]
2021-11-28T17:39:59: }
```

请问，该如何解决，谢谢！

**Comment by lancer-wang** [comment]
> 出现了同样的问题，ql check显示：
> 
> ```
> 2021-11-28T17:39:58:     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
> 2021-11-28T17:39:58:   code: 'MODULE_NOT_FOUND',
> 2021-11-28T17:39:58:   requireStack: [ '/ql/build/app.js' ]
> 2021-11-28T17:39:58: }
> 2021-11-28T17:39:59: Error: Cannot find module 'reflect-metadata'
> 2021-11-28T17:39:59: Require stack:
> 2021-11-28T17:39:59: - /ql/build/app.js
> 2021-11-28T17:39:59:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
> 2021-11-28T17:39:59:     at Module.Hook._require.Module.require (/usr/local/pnpm-global/5/node_modules/.pnpm/require-in-the-middle@5.1.0/node_modules/require-in-the-middle/index.js:61:29)
> 2021-11-28T17:39:59:     at require (node:internal/modules/cjs/helpers:102:18)
> 2021-11-28T17:39:59:     at Object.<anonymous> (/ql/back/app.ts:1:1)
> 2021-11-28T17:39:59:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
> 2021-11-28T17:39:59:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> 2021-11-28T17:39:59:     at Module.load (node:internal/modules/cjs/loader:981:32)
> 2021-11-28T17:39:59:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> 2021-11-28T17:39:59:     at Object.<anonymous> (/usr/local/pnpm-global/5/node_modules/.pnpm/pm2@5.1.2/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
> 2021-11-28T17:39:59:     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
> 2021-11-28T17:39:59:   code: 'MODULE_NOT_FOUND',
> 2021-11-28T17:39:59:   requireStack: [ '/ql/build/app.js' ]
> 2021-11-28T17:39:59: }
> ```
> 
> 手动执行了，node install reflect-metadata也没用。请问，该如何解决，谢谢！

重装吧,我全删,重装解决了
